### ISSUE TITLE
Time for completion of the rewrite

### ISSUE THREAD

**Issue by MrAppu** [nilaoda/N_m3u8DL-RE#1]
Hi nilaoda, I just like to know how long will it take to complete the rewrite of the N_m3u8DL? Thanks!

**Comment by nilaoda** [comment]
I need to rewrite most of code, maybe cost more than one month😂

**Comment by sting8k** [comment]
Can you build ARM64 binary?

**Comment by nilaoda** [comment]
> Can you build ARM64 binary?

Windows? macOS? Linux?

**Comment by sting8k** [comment]
> > Can you build ARM64 binary?
> 
> 
> 
> Windows? macOS? Linux?

Linux pls 😁

**Comment by zjkzwh** [comment]
> > Can you build ARM64 binary?
> 
> Windows? macOS? Linux?

Dalao,can you build a Macos version?

**Comment by nilaoda** [comment]
@sting8k @zjkzwh I will add workflow to auto build latest verison for all platforms.
