### ISSUE TITLE
[Test] Run N_m3u8DL-RE on Android-arm64 with Termux

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/N_m3u8DL-RE#10]
## Install Termux

* https://github.com/termux/termux-app/releases/download/v0.118.0/termux-app_v0.118.0+github-debug_universal.apk

## Termux Get Storage Access

```sh
termux-setup-storage
```

Allow prompt, then restart Termux.

## Config Ubuntu

```sh
pkg up -y
pkg install proot-distro
proot-distro install ubuntu
proot-distro login ubuntu
```

## Get Apps

On Ubuntu:

* mkdir
```sh
mkdir /RE
cd /RE
```

* requirements
```sh
apt update
apt install wget
apt install unzip
apt-get install libicu-dev
```

* ffmpeg
```sh
wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-arm64-static.tar.xz
tar -xvf ffmpeg-release-arm64-static.tar.xz --wildcards '*/ffmpeg' -O > ./ffmpeg
chmod +x ./ffmpeg
```

* RE
```sh
wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/2905367163/N_m3u8DL-RE_Beta_linux-arm64.zip
unzip N_m3u8DL-RE_Beta_linux-arm64.zip
chmod +x ./N_m3u8DL-RE
```

**Note**: replace `2905367163` with latest id ([Actions](https://github.com/nilaoda/N_m3u8DL-RE/actions))

## Test

```sh
./N_m3u8DL-RE --tmp-dir /sdcard/Download --save-dir /sdcard/Download --save-name TEST "http://playertest.longtailvideo.com/adaptive/oceans_aes/oceans_aes.m3u8"
```

![ZVJRK)VM(TGE6Z1PF G12(A](https://user-images.githubusercontent.com/20772925/185760910-fbfd97e1-7389-4418-9dcb-8ff297428dd3.png)

**Comment by xhlove** [comment]
如果想用电脑远程操作，`termux`配合`ttyd`可以获得更好的使用体验（

- https://github.com/tsl0922/ttyd

```bash
ttyd -t fontSize=22 -t 'theme={"background": "#282A36", "foreground": "#F8F8F2", "cursor": "#F8F8F2", "selection": "#44475A"}' bash
```

![image](https://user-images.githubusercontent.com/48152166/186069768-7b8223da-905c-412f-a9b6-95873d280f3e.png)

**Comment by popsc30** [comment]
Have tried release version of "https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/3307213970"; [Version month Oct]
Neither work in "termux" nor "termux-proot-ubuntu-distro"; 
And here is the issue in termux:
when I exec the `./N_m3u8DL-RE`, it returned nothing;
in termux-proot-ubuntu-distro
when I exec the `./N_m3u8DL-RE`, it returned `segment fault`;

while I tried N_m3u8DL-RE (Beta version) 20220914 of "https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/3052755353" 
It works, but when ffmpeg merging, and the end, it showed the "Too many open files" error;

**Comment by nilaoda** [comment]
@popsc30 I also just realized this problem and will solve it later

**Comment by yf718** [comment]
大佬，v0.1.5.3-beta还能用，v0.2.0-beta无法使用，也没报错信息 @nilaoda

**Comment by Rshman21** [comment]
> 大佬，v0.1.5.3-beta还能用，v0.2.0-beta无法使用，也没报错信息，但我改用net7.0打包就好了 @nilaoda

你好，我也发现 .NET 8.0编译的无法运行，能否提供.NET 7.0打包的可执行文件，多谢

**Comment by nilaoda** [comment]
> 大佬，v0.1.5.3-beta还能用，v0.2.0-beta无法使用，也没报错信息，但我改用net7.0打包就好了 @nilaoda

等有空我搞一个安卓静态编译的吧

**Comment by A-nglea** [comment]
Followed test example precisely and not working with Latest Android V14. When run from the command line gives no response to N_m3u8DL-RE --help. 
Would really value a specific build for Termux or proot-distro Ubuntu

**Comment by A-nglea** [comment]
~ $ proot-distro login ubuntu
root@localhost:~# wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/6656210042/N_m3u8DL-RE_Beta_linux-arm64.zip
--2023-11-05 11:21:07--  https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/6656210042/N_m3u8DL-RE_Beta_linux-arm64.zip
Resolving nightly.link (nightly.link)... 2001:19f0:5001:3a1:5400:ff:fe59:31d1, 45.32.185.199
Connecting to nightly.link (nightly.link)|2001:19f0:5001:3a1:5400:ff:fe59:31d1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://pipelinesghubeus10.actions.githubusercontent.com/VxtghUz2kNT0fliRIayK9Q9TeJXB8SOy6yioO9dq8pS0r23g7d/_apis/pipelines/1/runs/140/signedartifactscontent?artifactName=N_m3u8DL-RE_Beta_linux-arm64&urlExpires=2023-11-05T11%3A22%3A06.9118961Z&urlSigningMethod=HMACV2&urlSignature=Qeq%2FHT0uYjK423Gmvu7cBBKxLf6otaCjW5ORHy7b2GI%3D [following]
--2023-11-05 11:21:08--  https://pipelinesghubeus10.actions.githubusercontent.com/VxtghUz2kNT0fliRIayK9Q9TeJXB8SOy6yioO9dq8pS0r23g7d/_apis/pipelines/1/runs/140/signedartifactscontent?artifactName=N_m3u8DL-RE_Beta_linux-arm64&urlExpires=2023-11-05T11%3A22%3A06.9118961Z&urlSigningMethod=HMACV2&urlSignature=Qeq%2FHT0uYjK423Gmvu7cBBKxLf6otaCjW5ORHy7b2GI%3D
Resolving pipelinesghubeus10.actions.githubusercontent.com (pipelinesghubeus10.actions.githubusercontent.com)... 20.102.38.122
Connecting to pipelinesghubeus10.actions.githubusercontent.com (pipelinesghubeus10.actions.githubusercontent.com)|20.102.38.122|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘N_m3u8DL-RE_Beta_linux-arm64.zip’

N_m3u8DL-RE_Beta_linux-     [        <=>                   ]   7.87M  5.28MB/s    in 1.5s    

2023-11-05 11:21:10 (5.28 MB/s) - ‘N_m3u8DL-RE_Beta_linux-arm64.zip’ saved [8253983]

root@localhost:~# unzip N_m3u8DL-RE_Beta_linux-arm64.zip 
Archive:  N_m3u8DL-RE_Beta_linux-arm64.zip
  inflating: N_m3u8DL-RE             
root@localhost:~# chmod +x N_m3u8DL-RE
root@localhost:~# ./N_m3u8DL-RE

**Comment by A-nglea** [comment]
~ $ proot-distro login ubuntu
root@localhost:~# wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/6656210042/N_m3u8DL-RE_Beta_linux-arm64.zip
--2023-11-05 11:21:07--  https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/6656210042/N_m3u8DL-RE_Beta_linux-arm64.zip
Resolving nightly.link (nightly.link)... 2001:19f0:5001:3a1:5400:ff:fe59:31d1, 45.32.185.199
Connecting to nightly.link (nightly.link)|2001:19f0:5001:3a1:5400:ff:fe59:31d1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://pipelinesghubeus10.actions.githubusercontent.com/VxtghUz2kNT0fliRIayK9Q9TeJXB8SOy6yioO9dq8pS0r23g7d/_apis/pipelines/1/runs/140/signedartifactscontent?artifactName=N_m3u8DL-RE_Beta_linux-arm64&urlExpires=2023-11-05T11%3A22%3A06.9118961Z&urlSigningMethod=HMACV2&urlSignature=Qeq%2FHT0uYjK423Gmvu7cBBKxLf6otaCjW5ORHy7b2GI%3D [following]
--2023-11-05 11:21:08--  https://pipelinesghubeus10.actions.githubusercontent.com/VxtghUz2kNT0fliRIayK9Q9TeJXB8SOy6yioO9dq8pS0r23g7d/_apis/pipelines/1/runs/140/signedartifactscontent?artifactName=N_m3u8DL-RE_Beta_linux-arm64&urlExpires=2023-11-05T11%3A22%3A06.9118961Z&urlSigningMethod=HMACV2&urlSignature=Qeq%2FHT0uYjK423Gmvu7cBBKxLf6otaCjW5ORHy7b2GI%3D
Resolving pipelinesghubeus10.actions.githubusercontent.com (pipelinesghubeus10.actions.githubusercontent.com)... 20.102.38.122
Connecting to pipelinesghubeus10.actions.githubusercontent.com (pipelinesghubeus10.actions.githubusercontent.com)|20.102.38.122|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘N_m3u8DL-RE_Beta_linux-arm64.zip’

N_m3u8DL-RE_Beta_linux-     [        <=>                   ]   7.87M  5.28MB/s    in 1.5s    

2023-11-05 11:21:10 (5.28 MB/s) - ‘N_m3u8DL-RE_Beta_linux-arm64.zip’ saved [8253983]

root@localhost:~# unzip N_m3u8DL-RE_Beta_linux-arm64.zip 
Archive:  N_m3u8DL-RE_Beta_linux-arm64.zip
  inflating: N_m3u8DL-RE             
root@localhost:~# chmod +x N_m3u8DL-RE
root@localhost:~# ./N_m3u8DL-RE

**Comment by vigilantejustice15** [comment]
wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/6851479504/N_m3u8DL-RE_Beta_linux-arm64.zip
unzip N_m3u8DL-RE_Beta_linux-arm64.zip
sudo chmod +x ./N_m3u8DL-RE
--2024-02-19 12:12:13--  https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/6851479504/N_m3u8DL-RE_Beta_linux-arm64.zip
Resolving nightly.link (nightly.link)... 2001:19f0:5001:3a1:5400:ff:fe59:31d1, 45.32.185.199
Connecting to nightly.link (nightly.link)|2001:19f0:5001:3a1:5400:ff:fe59:31d1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-19 12:12:14 ERROR 404: Not Found.

unzip:  cannot find or open N_m3u8DL-RE_Beta_linux-arm64.zip, N_m3u8DL-RE_Beta_linux-arm64.zip.zip or N_m3u8DL-RE_Beta_linux-arm64.zip.ZIP.
chmod: cannot access './N_m3u8DL-RE': No such file or directory

Help, can't download it, i use the latest id.

**Comment by vigilantejustice15** [comment]
Help, can't download it, i use the latest id.

**Comment by vigilantejustice15** [comment]
wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/6851479504/N_m3u8DL-RE_Beta_linux-arm64.zip
unzip N_m3u8DL-RE_Beta_linux-arm64.zip
sudo chmod +x ./N_m3u8DL-RE
--2024-02-19 12:12:13--  https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/6851479504/N_m3u8DL-RE_Beta_linux-arm64.zip
Resolving nightly.link (nightly.link)... 2001:19f0:5001:3a1:5400:ff:fe59:31d1, 45.32.185.199
Connecting to nightly.link (nightly.link)|2001:19f0:5001:3a1:5400:ff:fe59:31d1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-02-19 12:12:14 ERROR 404: Not Found.

unzip:  cannot find or open N_m3u8DL-RE_Beta_linux-arm64.zip, N_m3u8DL-RE_Beta_linux-arm64.zip.zip or N_m3u8DL-RE_Beta_linux-arm64.zip.ZIP.
chmod: cannot access './N_m3u8DL-RE': No such file or directory

**Comment by vigilantejustice15** [comment]
> > Help, can't download it, i use the latest id.
> > EDIT: nevermind, i download again from different links.
> 
> Hey I'm having same issue mind if u tell which link you used or maybe what exactly you replaced in wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/2905367163/N_m3u8DL-RE_Beta_linux-arm64.zip unzip N_m3u8DL-RE_Beta_linux-arm64.zip chmod +x ./N_m3u8DL-RE

If i'am not wrong i tried download using this link. You can tried it.

https://github.com/nilaoda/N_m3u8DL-RE/releases

I'm using the "Beta linux arm64".

**Comment by vigilantejustice15** [comment]
> > > > Help, can't download it, i use the latest id.
> > > > EDIT: nevermind, i download again from different links.
> > > 
> > > 
> > > Hey I'm having same issue mind if u tell which link you used or maybe what exactly you replaced in wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/2905367163/N_m3u8DL-RE_Beta_linux-arm64.zip unzip N_m3u8DL-RE_Beta_linux-arm64.zip chmod +x ./N_m3u8DL-RE
> > 
> > 
> > If i'am not wrong i tried download using this link. You can tried it.
> > https://github.com/nilaoda/N_m3u8DL-RE/releases
> > I'm using the "Beta linux arm64".
> 
> Hey thanks Really helped me well I'm not a tech guy i just follow the guide but I not sure what to do next
> 
> You see..
> 
> I did replace "wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/2905367163/N_m3u8DL-RE_Beta_linux-arm64.zip" with "wget https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.2.0-beta/N_m3u8DL-RE_Beta_linux-arm64_20230628.tar.gz" ignoring the ID thing they ask to update
> 
> Plus link was in "tar.gz" so I used "tar -xvf" to unzip it and it did.
> 
> But the when I tried to run "chmod +x ./N_m3u8DL-RE" it's says "cannot access './N_m3u8DL-RE': No such file or directory"![Screenshot_2024-02-25-07-54-55-22_84d3000e3f4017145260f7618db1d683.jpg](https://private-user-images.githubusercontent.com/70976714/307562043-912bcc8f-4699-46d5-b3d9-62ba152a52ab.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4Mzc0OTYsIm5iZiI6MTcwODgzNzE5NiwicGF0aCI6Ii83MDk3NjcxNC8zMDc1NjIwNDMtOTEyYmNjOGYtNDY5OS00NmQ1LWIzZDktNjJiYTE1MmE1MmFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA0NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NjllOWI1OGJkNTQyOGNiNDAwYWFmNTRlZDVlODQxYWUwNjk5ZDkxZTdhMDc3NzZmYzE3YmQ4YjE4NzEyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nydbXcao4se7a3bAv0wtbqgFDKzL3RcliMQyAVwAE04) It would a big help if you tell me a bit more

there's still a folder in there you can try this command.

cd N_m3u8DL-RE_Beta_linux-arm64
chmod +x ./N_m3u8DL-RE

**Comment by RAGAVANM1** [comment]
> > > > > > Help, can't download it, i use the latest id.
> > > > > > EDIT: nevermind, i download again from different links.
> > > > > 
> > > > > 
> > > > > Hey I'm having same issue mind if u tell which link you used or maybe what exactly you replaced in wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/2905367163/N_m3u8DL-RE_Beta_linux-arm64.zip unzip N_m3u8DL-RE_Beta_linux-arm64.zip chmod +x ./N_m3u8DL-RE
> > > > 
> > > > 
> > > > If i'am not wrong i tried download using this link. You can tried it.
> > > > https://github.com/nilaoda/N_m3u8DL-RE/releases
> > > > I'm using the "Beta linux arm64".
> > > 
> > > 
> > > Hey thanks Really helped me well I'm not a tech guy i just follow the guide but I not sure what to do next
> > > You see..
> > > I did replace "wget https://nightly.link/nilaoda/N_m3u8DL-RE/actions/runs/2905367163/N_m3u8DL-RE_Beta_linux-arm64.zip" with "wget https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.2.0-beta/N_m3u8DL-RE_Beta_linux-arm64_20230628.tar.gz" ignoring the ID thing they ask to update
> > > Plus link was in "tar.gz" so I used "tar -xvf" to unzip it and it did.
> > > But the when I tried to run "chmod +x ./N_m3u8DL-RE" it's says "cannot access './N_m3u8DL-RE': No such file or directory"![Screenshot_2024-02-25-07-54-55-22_84d3000e3f4017145260f7618db1d683.jpg](https://private-user-images.githubusercontent.com/70976714/307562043-912bcc8f-4699-46d5-b3d9-62ba152a52ab.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4Mzc0OTYsIm5iZiI6MTcwODgzNzE5NiwicGF0aCI6Ii83MDk3NjcxNC8zMDc1NjIwNDMtOTEyYmNjOGYtNDY5OS00NmQ1LWIzZDktNjJiYTE1MmE1MmFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA0NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NjllOWI1OGJkNTQyOGNiNDAwYWFmNTRlZDVlODQxYWUwNjk5ZDkxZTdhMDc3NzZmYzE3YmQ4YjE4NzEyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nydbXcao4se7a3bAv0wtbqgFDKzL3RcliMQyAVwAE04) It would a big help if you tell me a bit more
> > 
> > 
> > there's still a folder in there you can try this command.
> > cd N_m3u8DL-RE_Beta_linux-arm64
> > chmod +x ./N_m3u8DL-RE
> 
> Oh Thanks mate it worked appreciated 👍

Me Not working Why Bro?

**Comment by yffbit** [comment]
> 大佬，v0.1.5.3-beta还能用，v0.2.0-beta无法使用，也没报错信息，但我改用net7.0打包就好了 @nilaoda

`.bashrc`中添加`export DOTNET_GCHeapHardLimit=1C0000000`
如果不行，安装`apt install -y dotnet-sdk-8.0`后再试
参考
https://www.cnblogs.com/q-z-lin/p/18008593
https://github.com/dotnet/runtime/issues/85556#issuecomment-1532509992
https://github.com/termux/proot/issues/283#issuecomment-1688261712

**Comment by DecosSoft** [comment]
/data/data/com.termux/files/usr/bin » N_m3u8DL-RE
~» N_m3u8DL-RE: command not found

Nothing happens. Latest build

**Comment by RevealedSoulEven** [comment]
In proot ubuntu also it's neither giving any output nor any error.

**Comment by nilaoda** [comment]
请到 #516 讨论

Move to #516
