### ISSUE TITLE
请教下如果用这个录制电视直播的问题

### ISSUE THREAD

**Issue by oncebeloved** [nilaoda/N_m3u8DL-RE#102]
请教下如果用这个录制电视直播，电视台并不触发结束，如何自动合并，或者强制停止，自动或者用命令合并已经下载的TS片段呢？
![Screenshot_2023-01-15-15-57-03-122_com termux](https://user-images.githubusercontent.com/51181996/212529318-48122f39-43dd-4cd0-9514-58697e2942fe.jpg)
![Screenshot_2023-01-15-15-57-25-590_com termux](https://user-images.githubusercontent.com/51181996/212529322-8eb598aa-69d2-4bd3-b410-2f860687973d.jpg)

**Comment by nilaoda** [comment]
强制停止就行

**Comment by oncebeloved** [comment]
是的，我也知道我将强行中断，可我遇到的问题是"我需要如何来合并这些视频切片"

**Comment by oncebeloved** [comment]
是的，我也知道我将强行中断，可我遇到的问题是"我需要如何来合并这些视频切片"@nilaoda

**Comment by qwe199** [comment]
> 是的，我也知道我将强行中断，可我遇到的问题是"我需要如何来合并这些视频切片" @nilaoda

用ffmpeg可以实时混流成ts 不用再次合并

**Comment by hopradio** [comment]
ffmpeg就能做的事情……
"ffmpeg.exe" -i "in" -c copy "out.ts
