### ISSUE TITLE
ITV.COM failure to download init file

### ISSUE THREAD

**Issue by A-nglea** [nilaoda/N_m3u8DL-RE#111]
ITV.com is a major provider of free-to-air programming in the UK.

Recently it has encrypted all of its web output and has re-branded as ITVX. 

I have been unable to use N_m3u8DL-RE to download content; it always fails with 403 Forbidden and 'Download init file failed'

### Programme url: 
https://www.itv.com/watch/a-spy-among-friends/2a7931/2a7931a0001

### Typical mpd: 
https://itvpnpdotcom.blue.content.itv.com/2-7931-0001-001/34/3/VAR028-HD-s/2-7931-0001-001_34_3_VAR028-HD-s.ism/.mpd?filter=%28%28type%3D%3D%22video%22%26%26DisplayHeight%3C%3D720%29%7C%7C%28type%21%3D%22video%22%29%29&hdnea=st%3D1675598212~exp%3D1675619812~acl%3D/2-7931-0001-001/%2A~data%3Dnohubplus~hmac%3D21ee57ff69cb45e5e2b858138ea3b2fcd19f692e0a481d5539255448e91ff1ea

The site sets a cookie

 Netscape HTTP Cookie File
 https://curl.haxx.se/rfc/cookie_spec.html
This is a generated file! Do not edit.

.itv.com	TRUE	/	FALSE	1990955271	Itv.Cid	88d917c0-e889-40f4-b937-5ae045d82f89
.itv.com	TRUE	/	FALSE	1770203272	mid	15189771509219156656
.itv.com	TRUE	/	FALSE	1770203275	SyrenisGuid_213aea86-31e5-43f3-8d6b-e01ba0d420c7	a7a703ce-edc3-41f3-960c-1876a4fff2ef
.itv.com	TRUE	/	FALSE	1770203275	SyrenisCookieIDs_213aea86-31e5-43f3-8d6b-e01ba0d420c7	[]
.itv.com	TRUE	/	FALSE	1770203275	SyrenisCookieFormConsent_213aea86-31e5-43f3-8d6b-e01ba0d420c7	[{"FieldID":"s122_c113","IsChecked":1},{"FieldID":"s135_c126","IsChecked":1},{"FieldID":"s134_c125","IsChecked":1},{"FieldID":"s138_c129","IsChecked":1},{"FieldID":"s157_c147","IsChecked":1},{"FieldID":"s136_c127","IsChecked":1},{"FieldID":"s137_c128","IsChecked":1}]
.itv.com	TRUE	/	FALSE	1770203275	SyrenisCookiePrivacyLink_213aea86-31e5-43f3-8d6b-e01ba0d420c7	1
.itv.com	TRUE	/	FALSE	1770203275	SyrenisRunFirstCookieIDs_213aea86-31e5-43f3-8d6b-e01ba0d420c7	[]
.itv.com	TRUE	/	FALSE	1770203275	SyrenisCookieConsentDate_213aea86-31e5-43f3-8d6b-e01ba0d420c7	1675595277034.23
.itv.com	TRUE	/	FALSE	1770203275	SyrenisCustom_213aea86-31e5-43f3-8d6b-e01ba0d420c7	[]
.itv.com	TRUE	/	FALSE	0	Itv.Session	{"tokens":{"content":{"entitlement":{"purchased":[],"source":"","failed_availability_checks":[]},"email_verified":true,"token_type":"bearer","access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6IjIwYWYyOTExLTc1YmItNGMw....[snipped] ","refresh_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6IjIwYWYyOTEx[snipped]","profile_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6IjIwYWYyOTExLTc1YmItNGMwZi04YTM0LTE3MjYzYjRiMmFlOCIsImV4cCI6MTY3NTU5ODg4NywiaWF0IjoxNjc1NTk1Mjg3LCJub25jZSI6I...[snipped]"}},"sticky":false,"redirect":"/watch/a-spy-among-friends/2a7931/2a7931a0001"}

###Some of my python script's output :

------------------ license ------------------
https://itvpnp.live.ott.irdeto.com/Widevine/getlicense?CrmId=itvpnp&AccountId=itvpnp&ContentId=2-7931-0001-001_34

----------------- key found -----------------
--key 0da17078690242708324e51c0b678e41:12c129d75e62815207f57689d4d26ead

 command passed to subprocess.run()   is:

 ['N_m3u8DL-RE', 'https://itvpnpdotcom.blue.content.itv.com/2-7931-0001-001/34/3/VAR028-HD-s/2-7931-0001-001_34_3_VAR028-HD-s.ism/.mpd?filter=%28%28type%3D%3D%22video%22%26%26DisplayHeight%3C%3D720%29%7C%7C%28type%21%3D%22video%22%29%29&hdnea=st%3D1675598212~exp%3D1675619812~acl%3D/2-7931-0001-001/%2A~data%3Dnohubplus~hmac%3D21ee57ff69cb45e5e2b858138ea3b2fcd19f692e0a481d5539255448e91ff1ea', '--header', "'Accept': 'application/vnd.itv.vod.playlist.v2+json'", '--header', "'Content-Type': 'application/json'", '--header', 'Connection: keep-alive', '--header', 'Referer: https://www.itv.com/', '--header', "'data': '~nohubplus'", '--header', "'hmac': '~21ee57ff69cb45e5e2b858138ea3b2fcd19f692e0a481d5539255448e91ff1ea'", '--auto-select', '--header', "'Cookie': 'hdntl=exp=1675687732~acl=/2-7931-0001-001/*~data=hdntl,nohubplus~hmac=90d2b981b8d8c842bdc7c1bc3da893b4f990b0c99de17da6a9e70f6080cffc5d; Domain=itvpnpdotcom.blue.content.itv.com; Path=/; Expires=Mon, 06-Feb-2023 12:48:49 GMT'", '--save-name', 'spy', '--save-dir', './output', '--tmp-dir', './', '-mt', '--use-shaka-packager', '--key', '--key 0da17078690242708324e51c0b678e41:12c129d75e62815207f57689d4d26ead', '-M', 'format=mkv:muxer=mkvmerge']

13:18:31.002 INFO : N_m3u8DL-RE (Beta version) 20230111
13:18:31.011 INFO : Loading URL: https://itvpnpdotcom.blue.content.itv.com/2-7931-0001-001/34/3/VAR028-HD-s/2-7931-0001-001_34_3_VAR028-HD-s.ism/.mpd?filter=%28%28type%3D%3D%22video%22%26%26DisplayHeight%3C%3D720%29%7C%7C%28type%21%3D%22video%22%29%29&hdnea=st%3D1675598212~exp%3D1675619812~acl%3D/2-7931-0001-001/%2A~data%3Dnohubplus~hmac%3D21ee57ff69cb45e5e2b858138ea3b2fcd19f692e0a481d5539255448e91ff1ea
13:18:31.059 INFO : Content Matched: Dynamic Adaptive Streaming over HTTP
13:18:31.059 INFO : Parsing streams...
13:18:31.072 INFO : Extracted, there are 6 streams, with 5 basic streams, 1 audio streams, 0 subtitle streams
13:18:31.072 INFO : Vid *CENC 1280x720 | 1518 Kbps | video=1518278 | avc1.640028 | 554 Segments | ~55m19s
13:18:31.072 INFO : Vid *CENC 1024x576 | 664 Kbps | video=664434 | avc1.64001F | 554 Segments | ~55m19s
13:18:31.073 INFO : Vid *CENC 1024x576 | 443 Kbps | video=443535 | avc1.64001F | 554 Segments | ~55m19s
13:18:31.073 INFO : Vid *CENC 704x396 | 229 Kbps | video=229980 | avc1.64001F | 554 Segments | ~55m19s
13:18:31.073 INFO : Vid *CENC 704x396 | 220 Kbps | video=220313 | avc1.64001F | 554 Segments | ~55m19s
13:18:31.073 INFO : Aud *CENC audio=96000 | 96 Kbps | mp4a.40.2 | 2CH | 554 Segments | ~55m19s
13:18:31.073 INFO : Parsing streams...
13:18:31.073 INFO : Selected streams:
13:18:31.073 INFO : Vid *CENC 1280x720 | 1518 Kbps | video=1518278 | avc1.640028 | 554 Segments | ~55m19s
13:18:31.073 INFO : Aud *CENC audio=96000 | 96 Kbps | mp4a.40.2 | 2CH | 554 Segments | ~55m19s
13:18:31.073 INFO : Save Name: spy
13:18:31.073 INFO : Start downloading...Vid 1280x720 | 1518 Kbps | video=1518278 | avc1.640028
13:18:31.073 INFO : Start downloading...Aud audio=96000 | 96 Kbps | mp4a.40.2 | 2CH
13:18:31.074 WARN : When CENC encryption is detected, binary merging is automatically enabled
**13:18:34.130 WARN : Response status code does not indicate success: 403 (Forbidden).**          
13:18:34.169 WARN : Response status code does not indicate success: 403 (Forbidden).          
**13:18:34.170 ERROR: Download init file failed!**

So, it all works fine when N_m3u8DL-RE request the mpd the response is a 200 OK
and this header:

STATUS: 200 OK
HEADERS
accept-ranges:
bytes
access-control-allow-credentials:
true
access-control-allow-headers:
origin, range
access-control-allow-methods:
GET, HEAD, OPTIONS
access-control-allow-origin:
access-control-expose-headers:
Server,range
akamai-mon-iucid-del:
1307520
cache-control:
max-age=30408238
connection:
keep-alive
content-encoding:
gzip
content-length:
1181
content-type:
application/dash+xml
date:
Sun, 05 Feb 2023 13:08:30 GMT
etag:
"usp-0FD3C72C"
last-modified:
Tue, 20 Dec 2022 15:35:50 GMT
server:
openresty/1.19.3.1
set-cookie:
hdntl=exp=1675688910~acl=%2f2-7931-0001-001%2f*~data=hdntl,nohubplus~hmac=efe63245acf0035d46fa826aaa314341a6cca047e77ce250d6726d0493dc474b; Domain=itvpnpdotcom.blue.content.itv.com; Path=/; Expires=Mon, 06-Feb-2023 13:08:27 GMT
vary:
Accept-Encoding
x-handled-by:
origin
x-usp:
version=1.11.3 (24483)

After that any interaction results in a 403.   I've been attempting to get round this for quite a while with no luck. 
yt-dlp with their generic extractor works.

**Comment by nilaoda** [comment]
try `--append-url-params`

**Comment by A-nglea** [comment]
--append-url-params made no difference.

I ran yt-dlp while watching the exchanges with httptoolkit.
yt-dlp --allow-u "
https://itvpnpdotcom.blue.content.itv.com/2-7931-0001-001/34/3/VAR028-HD-s/2-7931-0001-001_34_3_VAR028-HD-s.ism/.mpd?filter=%28%28type%3D%3D%22video%22%26%26DisplayHeight%3C%3D720%29%7C%7C%28type%21%3D%22video%22%29%29&hdnea=st%3D1675681737~exp%3D1675703337~acl%3D/2-7931-0001-001/%2A~data%3Dnohubplus~hmac%3D79ffed3cdda7f29712fcd3f09a909157deda744bcf24a3a753541db74cc2d572
"

yt-dlp works without any extra parameters and with their generic extractor.
httptoolkit gives the * url and headers used by yt-dlp as:*


URL
https://itvpnpdotcom.blue.content.itv.com/2-7931-0001-001/34/3/VAR028-HD-s/2-7931-0001-001_34_3_VAR028-HD-s.ism/2-7931-0001-001_34_3_VAR028-HD-s-audio=96000-159264768.dash
HEADERS
accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
accept-encoding: identity
accept-language: en-us,en;q=0.5
connection: close
cookie:
hdntl=exp=1675769657~acl=%2f2-7931-0001-001%2f*~data=hdntl,nohubplus~hmac=34223768ec9e624b616e42fcffd49db73726e7496a5d12e1839809b9e21a11c5
host: itvpnpdotcom.blue.content.itv.com
sec-fetch-mode:
navigate
user-agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/90.0.4430.85 Safari/537.36

When duplicated in the N_m3u8DL-RE call it still failed with this command:-

['N_m3u8DL-RE', '
> https://itvpnpdotcom.blue.content.itv.com/2-7931-0001-001/34/3/VAR028-HD-s/2-7931-0001-001_34_3_VAR028-HD-s.ism/.mpd?filter=%28%28type%3D%3D%22video%22%26%26DisplayHeight%3C%3D720%29%7C%7C%28type%21%3D%22video%22%29%29&hdnea=st%3D1675681737~exp%3D1675703337~acl%3D/2-7931-0001-001/%2A~data%3Dnohubplus~hmac%3D79ffed3cdda7f29712fcd3f09a909157deda744bcf24a3a753541db74cc2d572',
> '--append-url-params', '--header', "'Accept':
> 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'",
> '--header', "'accept-encoding': 'identity'", '--header', "'Accept-Language:
> en-us,en;q=0.5'", '--header', "'connection': 'close'", '--header',
> "'Cookie':
> 'hdntl=exp=1675769657~acl=%2f2-7931-0001-001%2f*~data=hdntl,nohubplus~hmac=34223768ec9e624b616e42fcffd49db73726e7496a5d12e1839809b9e21a11c5'",
> '--header', "'Sec-Fetch-Mode': 'navigate'", '--header', "'host': '
> itvpnpdotcom.blue.content.itv.com'", '--header', "'User-Agent':
> 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
> Gecko) Chrome/91.0.4472.124 Safari/537.36'", '--auto-select',
> '--save-name', 'spy', '--save-dir', './output', '--tmp-dir', './', '-mt',
> '--use-shaka-packager', '--key',
> '0da17078690242708324e51c0b678e41:12c129d75e62815207f57689d4d26ead', '-M',
> 'format=mkv:muxer=mkvmerge']
>
