### ISSUE TITLE
[Question] --thread-count

### ISSUE THREAD

**Issue by 54m4d** [nilaoda/N_m3u8DL-RE#114]
Hi

`README.md`

<pre>--thread-count <number>                  设置下载线程数 [default: <b>16</b>]</pre>
<br />

`--help`

![Capture](https://user-images.githubusercontent.com/52612348/218146357-9e4eaf46-c5b0-4631-8f7c-8f9614b659b2.png)
Please which one is the correct default one?

**Comment by nilaoda** [comment]
This depends on the number of logical processors in your CPU.

You can see it in TaskMgr.

**Comment by 54m4d** [comment]
Ok, what happens if i increase it to e.g. 24?

**Comment by nilaoda** [comment]
> Ok, what happens if i increase it to e.g. 24?

Download 24 segments at same time
