### ISSUE TITLE
Subtitles language select

### ISSUE THREAD

**Issue by Cybasaint** [nilaoda/N_m3u8DL-RE#116]
>N_m3u8DL-RE.exe --sub-only --auto-subtitle-fix --sub-format SRT --select-subtitle name="English":for=all "https://cdn-videos.domestika.org/videos/000/059/278/80510e1bb5c0929825800e5b5432891e/master.m3u8?1674205390"

I have tried --select-subtitle name="en"; -ss name="English":for=all

This command still downloads all language streams. Is there way I can only download the english subtitle?

**Comment by nilaoda** [comment]
Remove `--sub-only` option.

**Comment by Cybasaint** [comment]
Thanks that works!
