### ISSUE TITLE
Question about --Save-Name

### ISSUE THREAD

**Issue by 54m4d** [nilaoda/N_m3u8DL-RE#122]
Hello,
 
When i save a file as for example: `Good Video` sometimes i get an error and sometimes the application just closes.

But if i save it as `GoodVideo` then it works normally, and i don't get any errors.

Is this expected? if yes, can you also add support for spaces in the name?

Thanks.

**Comment by nilaoda** [comment]
Add `"` like:
```
N_m3u8DL-RE --save-name "Good Video" https://example.com/master.m3u8
```

**Comment by 54m4d** [comment]
Yes, but in my batch file on Windows it works only if i use **`ExampleName`**, it doesn't work if i use **`"Example Name"`**, i don't know why?

This is my file:

```
@echo off
set /p URL=Video Link: 
set /p arguments=More commands?: 

if not "%arguments%"=="" echo More arguments provided!

N_m3u8DL-RE %arguments% "%URL%"
pause
```

More commands?: **`--save-name "Example Name"`**

After i enter this, the terminal just closes, but if i use **`--save-name ExampleName`** then it works well, i don't know why?

Can you please try it?

**Comment by nilaoda** [comment]
Delete line 5.

**Comment by 54m4d** [comment]
Please, i need this line, is it a bug in N_m3u8DL-RE?

**Comment by nilaoda** [comment]
@54m4d That's not a bug, your bat script thrown an error when input contains `"`. 

```bat
@echo off
set "arguments="
set /p URL=Video Link: 
set /p arguments=More commands?: 

if defined arguments echo More arguments provided!

N_m3u8DL-RE %arguments% "%URL%"
pause
```

**Comment by 54m4d** [comment]
I'm sorry, it was really a problem with my bat file, it conflicts when using `"`

Also, no need line 2.

Thank you very much Man.
