### ISSUE TITLE
(Question) MPD Live Stream

### ISSUE THREAD

**Issue by andremxmx** [nilaoda/N_m3u8DL-RE#126]
I try to download a mpd live streaming

and get this error

19:37:44.862 INFO : N_m3u8DL-RE (Beta version) 20230111
19:37:44.878 INFO : Loading URL: 'https://edge-vod01-sl.cvattv.com.ar/live/c7eds/America24/SA_Live_dash_enc_2A/America24.mpd'
19:37:44.883 ERROR: Object reference not set to an instance of an object.

`N_m3u8DL-RE.exe 'https://edge-vod01-sl.cvattv.com.ar/live/c7eds/America24/SA_Live_dash_enc_2A/America24.mpd' --save-name a24  --live-perform-as-vod true --key 45f75aacf06593c9b693fe427c67e5b8:3b1b027dd011af20fd9956c16dc084fb`

**Comment by ElCap13** [comment]
use double quotes (") instead of single quotes (')

**Comment by andremxmx** [comment]
Excelent, sorry for dat...

One more question it's possible to use this to get the live stream and decode online in ts? i was cheking the readme and code but not working my config sir

**Comment by andremxmx** [comment]
Working perfect now,

what just do


N_m3u8DL-RE.exe --save-name _TEST "XXXURLXXX" --live-real-time-merge  true --live-wait-time 1 --mp4-real-time-decryption true --tmp-dir TMP --live-pipe-mux --auto-select --key XXXXXXXXXXXXXXX:XXXXXXXXXXXXXX

thanks for the grate tool sir!

![image](https://user-images.githubusercontent.com/10226983/221742164-43a10e32-c97d-46ba-829b-0848a461c51e.png)
