### ISSUE TITLE
求自动读取txt中链接并开始下载的sh脚本

### ISSUE THREAD

**Issue by abe520** [nilaoda/N_m3u8DL-RE#131]
urls.txt
```
第05集$https://v.cc.cc/20230306/EFUX/index.m3u8
第06集$https://v.cc.cc/20230306/vRNn/index.m3u8
```
bat
```
@echo Off
for /f "tokens=1* delims=$" %%a in (urls.txt) do (N_m3u8DL-RE.exe "%%b" --auto-select true)
pause
```
Linux下实现类似功能

**Comment by abe520** [comment]
想要以某个字符分割行并识别文件名。

**Comment by nilaoda** [comment]
@abe520 

以下是将批处理脚本转换为 Shell 脚本的版本：
```bash
#!/bin/bash

while IFS='$' read -r token url; do
    ./N_m3u8DL-RE "$url" --auto-select true
done < urls.txt

read -p "Press any key to continue..." key
```

注意，在 Unix 系统中，换行符为 `\n` 而不是 Windows 下的 `\r\n`，因此需要将脚本保存为 Unix 格式（即使用 LF 换行符）。

此外，Shell 中的变量使用 `$` 前缀，因此在 `read` 命令中，我们将分隔符设置为 `$` 并使用 `IFS='$'` 来读取每行的两个字段。`read` 命令会将第一个字段读入到变量 `token` 中，但由于我们不需要它，因此忽略它。第二个字段被读入到变量 `url` 中，然后传递给 `N_m3u8DL-RE` 命令。

最后，我们在脚本末尾加上 `read` 命令以等待用户按下任意键继续。

**Comment by nilaoda** [comment]
以下是将脚本修改为根据 $ 分割文件名和 URL 的 Shell 版本：
```bash
#!/bin/bash

while IFS='$' read -r saveName url; do
    ./N_m3u8DL-RE "$url" --auto-select true --save-name "$saveName"
done < urls.txt

read -p "Press any key to continue..." key
```

类似之前的版本，我们使用 `read` 命令来读取每行的两个字段，以 `$` 作为分隔符。将第一个字段存储在变量 `saveName` 中，将第二个字段存储在变量 `url` 中，然后将这些变量传递给 `N_m3u8DL-RE` 命令。

请注意，我们在调用 `N_m3u8DL-RE` 命令时，使用 `--save-name` 参数将 `saveName` 变量传递给该命令。
