### ISSUE TITLE
能否加一个读取cookies的功能

### ISSUE THREAD

**Issue by CrymanChen** [nilaoda/N_m3u8DL-RE#135]
![20230310022803](https://user-images.githubusercontent.com/106590233/224121261-3c6a954f-66bd-48c7-b1fa-4eb5a6407857.png)
刚刚在解析DASH流的流媒体的时候，发现字幕不是普通的.srt或者.vtt格式，用本程序尝试下载，报错401
是否能增加一个读取浏览器的cookies的功能，类似https://github.com/yt-dlp/yt-dlp 的“--cookies-from-browser _YOUR BROWSER_ "功能

**Comment by nilaoda** [comment]
这个功能具有争议性，暂时不会支持。你可以手动设置Cookie：
```
N_m3u8DL-RE -H "Cookie: YOUR COOKIE"
```
