### ISSUE TITLE
关于派拉蒙+MPD的识别

### ISSUE THREAD

**Issue by suenley** [nilaoda/N_m3u8DL-RE#138]
派拉蒙+的mpd中，有好多各分组的内容，但是目前最新版的-re只能识别到其中一个组的内容。

**Comment by suenley** [comment]
https://pubads.g.doubleclick.net/ondemand/dash/content/2497752/vid/3D64D389-CF9A-45CA-AECE-6CAC486D4FE4/DLS/streams/c1302a90-90bb-4bda-b06d-74bf198a2972/manifest.mpd

不知道时效性多久。。。。刚抓的。

**Comment by nilaoda** [comment]
根据时间计算 RE已经获取到了配置相同的内容并将其合并

![image](https://user-images.githubusercontent.com/20772925/226108326-31bd645d-1f73-4b6d-ab8a-7d85179dd310.png)

**Comment by suenley** [comment]
这套视频它是有原始的>40min的英文音轨的，但是在这里只看到了2m23s ，在chrome浏览器进行播放的时候，是相同的mpd，en音轨是完全正常的。

**Comment by suenley** [comment]
我似乎被浏览器F12里的.mpd忽悠了，我在json里找到了一个其他的mpd，目前跑起来正常。。。感谢鸟大回复。
