### ISSUE TITLE
Broken Chinese subtitle after extracted.

### ISSUE THREAD

**Issue by pijanify** [nilaoda/N_m3u8DL-RE#141]
This tool is work perfectly. But, only Chinese subtitle is broken after extracted.

You can try it.
You'll need proxy to use because it's geolocked. 
Btw, you can use my proxies:
http://lolhager:LV73AzFAPt@103.235.64.214:49155/
http://lolhager:LV73AzFAPt@223.29.252.184:49155/

MPD Link:
https://vodejitp-asset-playback-b.astro.com.my/v2/default/dash-wv/vode/d2c9313e-8948-5340-97b5-62e4df00e775/default_primary.mpd

Thank you.

**Comment by nilaoda** [comment]
Goto [Actions](https://github.com/nilaoda/N_m3u8DL-RE/actions/workflows/build_latest.yml) download latest version.
