### ISSUE TITLE
希望支持解析AM地址

### ISSUE THREAD

**Issue by Unknow-404** [nilaoda/N_m3u8DL-RE#146]
示例下载地址：https://aod.itunes.apple.com/itunes-assets/HLSMusic126/v4/1d/eb/65/1deb6574-3330-f54f-3269-19b9a19b35ad/P541945692_default.m3u8

错误信息：
` ERROR: 获取KEY失败，忽略读取.: One or more errors occurred. (The 'skd' scheme is not supported.)`

**Comment by Unknow-404** [comment]
示例中的所有流均为音频流

**Comment by Unknow-404** [comment]
示例m3u8文件
[example.zip](https://github.com/nilaoda/N_m3u8DL-RE/files/11146548/example.zip)

**Comment by nilaoda** [comment]
忽略读取后，仍然可以下载。你需要自己解密。

**Comment by Unknow-404** [comment]
> 忽略读取后，仍然可以下载。你需要自己解密。

大佬可以指路一下有啥方法吗？
