### ISSUE TITLE
能否做个抖音直播检测，有直播直接调用下载直播文件；

### ISSUE THREAD

**Issue by talway** [nilaoda/N_m3u8DL-RE#15]
类似
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1468046
你看看

希望能监控主页直播状态，有直接下载；

用服务器监控下载有保障，本地win经常丢直播文件。

很多直播视频，需要二次剪辑

**Comment by nilaoda** [comment]
目前还不支持直播录制。

另外我认为监控这种事情，不应该由一个通用下载器完成

**Comment by talway** [comment]
确实
但是开个监控，再调用你这个下载器，配合使用，就强大了；
下载器已经非常好了

实际业务，都是下载直播流的
