### ISSUE TITLE
problem with ttml subtitles.

### ISSUE THREAD

**Issue by donniebdc** [nilaoda/N_m3u8DL-RE#150]
hi.
trying to download subtitles from a mpd file but subtitles codec is ttml and download status is giving this error.

21:57:06.666 INFO : Selected streams:
21:57:06.666 INFO : Sub subtitle=7 | tur | 1 Segment | ~50m21s
21:57:06.666 INFO : Sub subtitle=9 | eng | 1 Segment | ~50m21s
21:57:06.667 INFO : Sub subtitle=11 | spa | 1 Segment | ~50m21s
21:57:06.667 INFO : Sub subtitle=13 | ara | 1 Segment | ~50m21s
21:57:06.667 INFO : Save Name: manifest_mpm4sav_mvnumber_Auto_2023-04-07_21-57-06
21:57:06.668 INFO : Start downloading...Sub subtitle=7 | tur
21:57:06.905 WARN : Reading media info...
21:57:06.960 INFO : NaN: Unknown
21:57:06.962 WARN : Extracting TTML(raw) subtitle...
21:57:07.010 ERROR: The input string '1s' was not in a correct format.
21:57:09.109 WARN : Force Exit...

is there any solve about this?

**Comment by nilaoda** [comment]
Need mpd url to analyze

**Comment by donniebdc** [comment]
here is the url

https://exxen-vod.ercdn.net/otf/q/ab/gibi_s04b01_rev01/gibi_s04b01_rev01.smil/manifest_mpm4sav_mvnumber_Auto.mpd?userid=6105341&sid=yqbcbIcB1Jiyfas031Na&uid=7046122246915276646&reqid=3815381fe576acbd424f45297a1aa6ee&ct=episode&c=chrome&d=desktop&p=browser&t=gibi-s4-b1

here is the mpd

https://we.tl/t-V4UWuguzDy

**Comment by nilaoda** [comment]
019f403339df49d5ffdc777c32b383e1d761184b

**Comment by donniebdc** [comment]
so, where can i download the solved file for win64
