### ISSUE TITLE
--live-real-time-merge True --live-keep-segments False 一起使用会出错退出

### ISSUE THREAD

**Issue by golden777** [nilaoda/N_m3u8DL-RE#151]
ERROR: Could not find file 'C:\Users\**\****.m4s'.
应该是在还没有完成合并前就删除了临时文件导致的吧?

有的时候只想录制直播中的一段,所以要提前结束,而不是等到全部完成自动合并,如果使用过多次提前结束,会导致临时文件不会及时删除,会积累很多占用磁盘空间

**Comment by nilaoda** [comment]
142
