### ISSUE TITLE
下载后，视频文件和音频文件分离了，请问原因

### ISSUE THREAD

**Issue by dukoalad** [nilaoda/N_m3u8DL-RE#155]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/4963133/231459584-e18b0ff8-69b7-49c3-be34-6f4cd296b5f7.png">

**Comment by dukoalad** [comment]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/4963133/231459762-503298fb-1af4-41a6-be70-ed2a09eae5c7.png">

**Comment by dukoalad** [comment]
另外视频文件播放的时候 ，还遇到了图3这种问题

<img width="955" alt="image" src="https://user-images.githubusercontent.com/4963133/231460224-6e2e53a1-d3ed-437a-9690-3e2d14fed6e8.png">

**Comment by nilaoda** [comment]
该视频被加密了。本项目不提供密钥获取方式。
