### ISSUE TITLE
某站m3u8下载的视频播放显示花屏(声音正常)，这个能解决吗？谢谢！

### ISSUE THREAD

**Issue by git-070** [nilaoda/N_m3u8DL-RE#157]
如下两链接的视频，获取m3u8地址后，使用N_m3u8DL-RE／或N_m3u8DL-CLI下载后的视频，播放显示花屏(声音正常)，麻烦看看这个能解决吗？
据说是因为加密导致的，具体我也不清楚，如能解决有时间的话帮忙看看，如无法解决就算了。麻烦大神了，谢谢！
http://v.ccdi.gov.cn/2023/01/08/VIDEJkoXEd8osfH6MWxiHvYT230108.shtml#10006-weixin-1-52626-6b3bffd01fdde4900130bc5a2751b6d1
https://tv.cctv.com/2023/01/11/VIDE4RYyQJhc3fSX5oGfDTZ8230111.shtml

**Comment by 775405984** [comment]
你获取的是加密的，真正的视频藏在getHttpVideoInfo.do里面
![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/7196377/cb786910-b8b0-41b1-8862-1de08a11862e)
真地址是:
http://hls.cntv.myhwcdn.cn/asp/hls/main/0303000a/3/default/573210c36c154a7ab8897e4c99c044c7/main.m3u8?maxbr=2048

**Comment by cdtime** [comment]
> 你获取的是加密的，真正的视频藏在getHttpVideoInfo.do里面 ![image](https://user-images.githubusercontent.com/7196377/246104455-cb786910-b8b0-41b1-8862-1de08a11862e.png) 真地址是: http://hls.cntv.myhwcdn.cn/asp/hls/main/0303000a/3/default/573210c36c154a7ab8897e4c99c044c7/main.m3u8?maxbr=2048

你这个也是错的，吧

**Comment by 775405984** [comment]
![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/7196377/0b509add-7dd9-4ff7-98c1-a86e5df017a3)
![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/7196377/5628cd8a-4c83-452b-b110-55291aa1ea24)
亲测无误 @cdtime

**Comment by git-070** [comment]
> ![image](https://user-images.githubusercontent.com/7196377/246583925-0b509add-7dd9-4ff7-98c1-a86e5df017a3.png) ![image](https://user-images.githubusercontent.com/7196377/246583947-5628cd8a-4c83-452b-b110-55291aa1ea24.png)亲测无误

非常感谢！方法已试可以正常播放，再次感谢。
