### ISSUE TITLE
下载完M3U8没有自动合并。

### ISSUE THREAD

**Issue by yjiawqgj** [nilaoda/N_m3u8DL-RE#159]
linux系统
![image](https://user-images.githubusercontent.com/71002956/232466048-6f96af6a-86e7-4724-8adc-353be0bf6c46.png)
![image](https://user-images.githubusercontent.com/71002956/232466510-93a3b793-3d9f-48e4-9e97-844ee1034781.png)
显示：Too many open files

**Comment by nilaoda** [comment]
#50
