### ISSUE TITLE
Request RE to support m3u8dl:// protocol

### ISSUE THREAD

**Issue by zhangweildlh** [nilaoda/N_m3u8DL-RE#163]
Request RE to support m3u8dl:// protocol

**Comment by cocang** [comment]
我的自行解决方案是，自己写个简单的工具，支持注册自身为URL协议对象，接受参数后带着参数启动N_m3u8DL-RE.exe
这样不就达到了目的嘛，也很简单

**Comment by zhangweildlh** [comment]
> 我的自行解决方案是，自己写个简单的工具，支持注册自身为URL协议对象，接受参数后带着参数启动N_m3u8DL-RE.exe 这样不就达到了目的嘛，也很简单

大哥，我水平低，没您这能耐啊

**Comment by nilaoda** [comment]
#75
