### ISSUE TITLE
下载后视频画面是黑屏，音频打不开，求解决

### ISSUE THREAD

**Issue by yyxiaofeng** [nilaoda/N_m3u8DL-RE#164]
N_m3u8DL-RE.exe --save-name test1 --append-url-params --live-real-time-merge --key https://mammothtv.my.id/astro/1601 "https://daddyhd.mammothtv.workers.dev/dash-wv/linear/1601/default_primary.mpd"
下载后视频文件打开是黑屏，音频也打不开，求教

**Comment by nilaoda** [comment]
目测是DRM保护，你需要输入正确的KEY。格式如下：
```
--key 4412ed2b5ddd829548247f176def2f76:4a50a51995ee47fb34bb927d0c5dd7f5
```

Key的获取方式，可以自行上网查找。
