### ISSUE TITLE
Problem downloading subtitles

### ISSUE THREAD

**Issue by MagratG** [nilaoda/N_m3u8DL-RE#165]
Using the latest 0.1.6 version to download subtitles only just downloads the first line of any multi-line subtitles.  Using the previous, 0.1.5.3 version, downloads all subtitles correctly.

**Comment by nilaoda** [comment]
Any url for test?

**Comment by MagratG** [comment]
Thanks for looking at this.

Here’s a URL from UKYVPlay:

https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/1242911124001/1bd25b61-6ca2-41a6-bc45-ed5e81beb3a5/6s/manifest.mpd?fastly_token=NjRhODA4ZDRfYmI5NWJmNmEzYzVhOTQyMmY5ZjcwZjVjOTZmODI4NWE5MWFiZDMxZmM3ZGZmYzA0ZjVlOGJhNTU4YmJiYTEwNw%3D%3D

 

Here’s the first few subtitle lines using version 0.1.5.3:

1

00:00:07,200 --> 00:00:09,680

<c.white>The time now is 5:00.</c>

 

2

00:00:17,680 --> 00:00:19,240

<c.yellow>Trevor, it's on.</c>

 

3

00:00:22,120 --> 00:00:25,280

<c.white>TV:</c><c.cyan>Hello.</c><c.lime>Avast, ye landlubbers.</c>

 

4

00:00:26,720 --> 00:00:30,480

<c.white>Today, we're going to be looking</c>

<c.white>at making jelly eggs.</c><c.lime>Oh.</c>

 

 

….and here’s the same lines using version 0.1.6:

1

00:00:07,200 --> 00:00:09,680

The time now is 5:00.

 

2

00:00:17,680 --> 00:00:19,240

Trevor, it's on.

 

3

00:00:22,120 --> 00:00:25,280

TV:

 

4

00:00:26,720 --> 00:00:30,480

Today, we're going to be looking

 

 

As you can see the later software version only gets the first line and none of the colour styling information.

 

 

 

 

TTFN

Dennis Hartley
