### ISSUE TITLE
Regarding Termux Installation 

### ISSUE THREAD

**Issue by Karthik-20034** [nilaoda/N_m3u8DL-RE#166]
Hi Developer,

I’d like to install N_m3u8_DL-RE in termux.I’ve gone through instructions but I’m stuck with "replace number with current Build number under actions tab".but I can’t find any,I’ll be helpful if you provide the latest build number or ways to view the build number.Reference is attached with [this.](https://github.com/nilaoda/N_m3u8DL-RE/issues/10)
![IMG_2490](https://user-images.githubusercontent.com/83129674/235059382-6cbc57f9-184a-4acb-9aa9-59c7c8f373b6.jpeg)

I’m looking forward to hear from you.

Thanks.

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-RE/actions
