### ISSUE TITLE
Download multiple links

### ISSUE THREAD

**Issue by Worz01** [nilaoda/N_m3u8DL-RE#169]
Is there an argument that enables multiple links to be downloaded with a single command?

**Comment by Newbiect** [comment]
Yes you can, I did it by creating a .bat file putting the links one below the other.
`N_m3u8DL-RE.exe -ss all -sa lang="es|en":for=best2 -sv best -mt TRUE --thread-count 12 --save-name ".S01E01 - Enigma humano" "Your Link" --tmp-dir tmp --key-text-file "key.txt" -M format=mkv:muxer=mkvmerge`
`N_m3u8DL-RE.exe -ss all -sa lang="es|en":for=best2 -sv best -mt TRUE --thread-count 12 --save-name ".S01E02 - Enigma humano" "Your Link" --tmp-dir tmp --key-text-file "key.txt" -M format=mkv:muxer=mkvmerge`
`N_m3u8DL-RE.exe -ss all -sa lang="es|en":for=best2 -sv best -mt TRUE --thread-count 12 --save-name ".S01E01 - Enigma humano" "Your Link" --tmp-dir tmp --key-text-file "key.txt" -M format=mkv:muxer=mkvmerge`

**Comment by Worz01** [comment]
> Yes you can, I did it by creating a .bat file putting the links one below the other. `N_m3u8DL-RE.exe -ss all -sa lang="es|en":for=best2 -sv best -mt TRUE --thread-count 12 --save-name ".S01E01 - Enigma humano" "Your Link" --tmp-dir tmp --key-text-file "key.txt" -M format=mkv:muxer=mkvmerge` `N_m3u8DL-RE.exe -ss all -sa lang="es|en":for=best2 -sv best -mt TRUE --thread-count 12 --save-name ".S01E02 - Enigma humano" "Your Link" --tmp-dir tmp --key-text-file "key.txt" -M format=mkv:muxer=mkvmerge` `N_m3u8DL-RE.exe -ss all -sa lang="es|en":for=best2 -sv best -mt TRUE --thread-count 12 --save-name ".S01E01 - Enigma humano" "Your Link" --tmp-dir tmp --key-text-file "key.txt" -M format=mkv:muxer=mkvmerge`

Thanks Ill give it a try.
