### ISSUE TITLE
aes-ecb  及proxy 功能建议

### ISSUE THREAD

**Issue by laoweilove** [nilaoda/N_m3u8DL-RE#17]
个人的一些建议
Crypto.AESUtil.cs这个文件里可以加入  

AES-ECB-Decrypt 方法，C#不太了解，不过应该是在CipherMode这里改成CipherMode.ECB,再去掉iv选项应该可以做到
在args 里可以加入--use-AES-ECB参数，实现手动使用AES-ECB解密

还有就是可以加入proxy参数，使一些下载可以走代理

**Comment by nilaoda** [comment]
已经支持了，可以试试能否正常工作

**Comment by laoweilove** [comment]
> 

手头暂时没有需要这两种的链接，以前有遇到过，不过忘记是哪个站了
