### ISSUE TITLE
Remove media type on the save name

### ISSUE THREAD

**Issue by stickyfin** [nilaoda/N_m3u8DL-RE#18]
The saved name of the downloaded media contain the type of the media. Would like to remove it by default.

Command and flag used:
`~/m3u8/bin/./N_m3u8DL-RE "URL" --save-name "KL.Gangster.Underworld.S01E01" --ffmpeg-binary-path /usr/bin/ffmpeg --write-meta-json false --sub-format SRT --binary-merge`

Saved filename:
`KL.Gangster.Underwold.S01E01.VIDEO.ts`
`KL.Gangster.Underworld.S01E01.SUBTITLE.en.srt`

Can the media type like VIDEO and SUBTITLE be removed by default?

**Comment by nilaoda** [comment]
`KL.Gangster.Underwold.S01E01.ts`
`KL.Gangster.Underworld.S01E01.en.srt`

like that?

**Comment by stickyfin** [comment]
Yes. Thank you
