### ISSUE TITLE
关于硬盘写入量的问题

### ISSUE THREAD

**Issue by cyfex** [nilaoda/N_m3u8DL-RE#181]
不好意思，我在提问前并没有深入研究N_m3u8DL-RE的机制，也不知道目前实现方式如何。但我有一个问题，目前的下载方式对硬盘的写入是如何的呢？我猜测是先把每个ts下载下来再合并成一个文件？相当于至少写入两遍？由于我目前使用的是一块固态硬盘，我对写入的方式比较在意，如果能用内存替代的话更好了。

**Comment by nilaoda** [comment]
如果实在介意 可以使用其他工具虚拟一个内存盘
