### ISSUE TITLE
希望增加“自动读取配置文件”的功能

### ISSUE THREAD

**Issue by nonfdsaofd** [nilaoda/N_m3u8DL-RE#183]
在需要敲较多命令行参数时，每次都敲会比较麻烦。如果能默认从某个目录（比如home）读取配置文件（比如N_m3u8DL-RE.conf），那么将轻松许多。比如yt-dlp也有类似的功能。希望能增加此功能，感谢开发者。

**Comment by nilaoda** [comment]
现在默认从可执行文件同级目录读取配置文件

**Comment by nonfdsaofd** [comment]
@nilaoda 请问有文档吗？我找遍了readme.md没找到相关信息

**Comment by nilaoda** [comment]
> @nilaoda 请问有文档吗？我找遍了readme.md没找到相关信息

不好意思 我记混了 还以为是另一个项目的issues🤣

你可以这样使用配置文件：

创建任意文本文件，例如`config.txt`:
```
--write-meta-json

--skip-download
```

调用命令行时使用`@+文件名`：
```
N_m3u8DL-RE.exe @config.txt t.m3u8 
```

等效于：
```
N_m3u8DL-RE.exe --write-meta-json --skip-download t.m3u8 
```

**Comment by nonfdsaofd** [comment]
@nilaoda 感谢
