### ISSUE TITLE
录制直播时ts切片多数无法直接观看

### ISSUE THREAD

**Issue by ROCO-freedom** [nilaoda/N_m3u8DL-RE#184]
录制直播时下载的切片没法直接打开，只有添加实时合并和实时混流参数后最后录制的文件才可观看。由于直播时长不固定，因此无法确定录制时长，只能什么时候结束什么时候停止录制。切片打不开的原因是未进行混流吗？

**Comment by 775405984** [comment]
可以用老版本: https://github.com/nilaoda/N_m3u8DL-CLI/releases

什么时候关闭窗口，什么时候结束录制。
直接一个TS文件，录制过程中可以直接打开观看。

**Comment by ROCO-freedom** [comment]
> 可以用老版本: https://github.com/nilaoda/N_m3u8DL-CLI/releases
> 
> 什么时候关闭窗口，什么时候结束录制。 直接一个TS文件，录制过程中可以直接打开观看。

好的，谢谢~
