### ISSUE TITLE
How do I select the best track based on the length of the video?

### ISSUE THREAD

**Issue by strke2000** [nilaoda/N_m3u8DL-RE#188]
![Screenshot 2023-06-10 082533](https://github.com/nilaoda/N_m3u8DL-RE/assets/133670385/5ceedf3c-24c8-45f2-a570-68c94d6e3d82)

**Comment by nilaoda** [comment]
You can drop video using latest verison. To drop video no longer than 10 minutes:
```
N_m3u8DL-RE -dv plistDurMax="10m0s":for=all
```

**Comment by strke2000** [comment]
> You can drop video using latest verison. To drop video no longer than 10 minutes:
> 
> ```
> N_m3u8DL-RE -dv plistDurMax="10m0s":for=all
> ```

I think the best solution is to make the list order based on movie length and then Bandwidth and not limit or exclude this solution does not apply with all content
