### ISSUE TITLE
N_m3u8DL-RE_v0.1.7无法合并视频 

### ISSUE THREAD

**Issue by zhouqiaoqiao** [nilaoda/N_m3u8DL-RE#193]
提示报错 
索引超出了范围。 必须是非负的，并且小于收藏的大小。 （参数'索引'）
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

**Comment by nilaoda** [comment]
请提供详细场景

**Comment by zhouqiaoqiao** [comment]
最新更新的已经可以正常合并了谢谢作者

**Comment by zhouqiaoqiao** [comment]
现在我有一个新问题就是视频音轨下载合并本来是在downloads目录的合并完现在会出现在主目录 不在downloads里面

**Comment by nilaoda** [comment]
已修复

**Comment by zhouqiaoqiao** [comment]
经过测试一切正常了谢谢作者
