### ISSUE TITLE
这个不会用啊 能不能想3.02那样出个客户端啊 ，，

### ISSUE THREAD

**Issue by a447948814** [nilaoda/N_m3u8DL-RE#2]
如题。这个跨平台是啥意思？除了m3u8还能下载其他格式？磁力 迅雷？还是啥意思？。另外 能发个客户端吗  小白用户直接用 谢谢

**Comment by a447948814** [comment]
好的 谢谢，加油！大神



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月20日(周三) 晚上8:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nilaoda/N_m3u8DL-RE] 这个不会用啊 能不能想3.02那样出个客户端啊 ，， (Issue #2)




 
目前还是开发+测试阶段，等基本功能差不多的时候会发出来的

**Comment by SkyTeamWater** [comment]
> 如题。这个跨平台是啥意思？除了m3u8还能下载其他格式？磁力 迅雷？还是啥意思？。另外 能发个客户端吗 小白用户直接用 谢谢

跨平台就是win linux macos等等都能用，不调用某个系统的库
