### ISSUE TITLE
System.IO.FileNotFoundException: ffmpeg not found, please download at: https://ffmpeg.org/download.html

### ISSUE THREAD

**Issue by gilak11** [nilaoda/N_m3u8DL-RE#200]
System.IO.FileNotFoundException: ffmpeg not found, please download at: https://ffmpeg.org/download.html

**Comment by nilaoda** [comment]
?

**Comment by CrymanChen** [comment]
@gilak11 Based on the information you gave us, it may imply that ffmpeg is not found by the program itself.
You should go to ffmpeg official website and download the executable file in their releases.
The download link is <CODE>https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z</CODE> if you are using Windows.
Plus, adding the ffmpeg.exe into the environment variable would also be a good thing in case any problem or error occur.
