### ISSUE TITLE
mac 版本合并ts 文件

### ISSUE THREAD

**Issue by seqwait** [nilaoda/N_m3u8DL-RE#21]
N_m3u8DL-RE_Beta_osx-x64
e1c89de
下载完成后没有合并成MP4 就算指定参数 -M format=mp4 也没有合并需要手动用ffmpeg 合并
是现在暂时不支持吗 ?

**Comment by nilaoda** [comment]
`-M` 是混流分离的音视频轨道用的，不是合并ts分片的。默认情况下载m3u8时会自动使用ffmpeg合并为mp4，可以看看程序有没有什么异常输出
