### ISSUE TITLE
v0.1.8起报毒被阻挡，病毒类型:特洛伊木马，问题:严重，请检查程式码

### ISSUE THREAD

**Issue by SAOJSM** [nilaoda/N_m3u8DL-RE#214]
N_m3u8DL-RE_v0.1.9-beta:Windows Defender报毒，强制移除exe档，由于问题为严重，无法透过排除扫描来避免

N_m3u8DL-RE_v0.1.8-beta:Chrome报毒，一开始报出为不常被下载档案，后续改为含有病毒，直接不让下载

N_m3u8DL-RE_v0.1.6-beta:Asset Github Release只剩源码

目前解决方式为先回退到N_m3u8DL-RE_v0.1.5.3-beta
请原作者确认下问题点
若有推测可能点可回复于留言
我可以协助排查问题点

**Comment by nilaoda** [comment]
这个可能是因为 v0.1.8-beta 起升级到了 .NET8 引起的。

Windows Defender误报申请页面：https://www.microsoft.com/en-us/wdsi/filesubmission

---

我的 Chrome 表示没报毒

![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/20772925/08edf1cf-d144-4046-8268-c819356acf1d)

**Comment by SAOJSM** [comment]
检测是跳执行危险程式码，非套件问题
还是作者您有加密套壳？
可能会因此误报
微软部分要求软件作者自行申请误报

**Comment by SAOJSM** [comment]
目前更新v2.0.0 Windows defender检测没问题，跑沙盒未报毒

**Comment by nilaoda** [comment]
> 目前更新v2.0.0 Windows defender检测没问题，跑沙盒未报毒

然而打包流程没变……就很迷

**Comment by SAOJSM** [comment]
想问下作者是用哪个打包方式呢？

**Comment by nilaoda** [comment]
> 想问下作者是用哪个打包方式呢？

打包用的是GitHub Actions：
https://github.com/nilaoda/N_m3u8DL-RE/blob/main/.github/workflows/build_latest.yml

我猜想可能的地方有两个：
1. Native AOT本身的问题 
2. UPX压缩可执行文件时导致
