### ISSUE TITLE
跨平台 GUI 下载完毕无论下载是否成功,都会 return 0 所以造成了无法判断程序是否正常执行了

### ISSUE THREAD

**Issue by zerobiubiu** [nilaoda/N_m3u8DL-RE#216]
我封装了一个简易的 GUI 界面,各位可以看看[zerobiubiu/N_m3u8DL-RE-GUI](https://github.com/zerobiubiu/N_m3u8DL-RE-GUI.git)
同时也发现了一个小 BUG 就是下载完毕无论下载是否成功,都会 return 0 所以造成了无法判断程序是否正常执行了
<img width="795" alt="image" src="https://github.com/nilaoda/N_m3u8DL-RE/assets/57526439/0ec14bfa-0879-4b16-9342-7a42cdf0a9e1">

**Comment by nilaoda** [comment]
这个我有空优化一下

**Comment by lighall** [comment]
可以先尝试判断最后合并的文件是否存在。有save-dir/save-name.mp4就是执行成功。

**Comment by zerobiubiu** [comment]
> 

是个好方法，就是多一道检测，我想是，程序能给个异常码，哪里出错就返回个错误码，好处理问题

**Comment by nilaoda** [comment]
代码中已经优化了此问题 https://github.com/nilaoda/N_m3u8DL-RE/commit/8bf50a3f5a773cc24e7bead438a7f2a5da99e817
