### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by maijh** [nilaoda/N_m3u8DL-RE#224]
ffmpeg merging时报错Too many open files，应该怎么解决

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-RE/issues/159 https://github.com/nilaoda/N_m3u8DL-RE/issues/89 https://github.com/nilaoda/N_m3u8DL-RE/issues/50 https://github.com/nilaoda/N_m3u8DL-RE/issues/7
