### ISSUE TITLE
发现一个新问题，不知道是解密的bug还是啥。

### ISSUE THREAD

**Issue by dfvips** [nilaoda/N_m3u8DL-RE#225]
下载viki的时候，开实时解密，只有第一个分片正常解，后面都是0KB，两种解密工具解密方式都一样，只要开了实时解密，后面的分片全0字节，完整解密是正常的。
<img width="1440" alt="image" src="https://github.com/nilaoda/N_m3u8DL-RE/assets/21048630/f8116242-6160-435c-bd9a-5a6c4b2abb66">

**Comment by dfvips** [comment]
<img width="1242" alt="image" src="https://github.com/nilaoda/N_m3u8DL-RE/assets/21048630/99880366-1316-4508-9c0e-a237f5d73d05">
解密日志。

**Comment by nilaoda** [comment]
![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/20772925/a1ff97d7-f0c2-4bd4-87dd-de355be36edd)

单 mp4 整段，程序尝试切割为小分片并发下载，然而小分片不是真正的 m4s 片段，导致无法解密。

**Comment by dfvips** [comment]
所以说bug咯。
