### ISSUE TITLE
貌似现在还不支持嵌套地址？

### ISSUE THREAD

**Issue by j-wyatt-a** [nilaoda/N_m3u8DL-RE#23]
这是我的测试地址：https://new.qqaku.com/20220819/g63uLb7E/index.m3u8

它的内容里包含了另一个地址：https://new.qqaku.com/20220819/g63uLb7E/1100kb/hls/playlist_up.m3u8

这是控制台信息
> ./N_m3u8DL-RE https://new.qqaku.com/20220819/g63uLb7E/index.m3u8
07:20:30.059 INFO  : 加载URL: https://new.qqaku.com/20220819/g63uLb7E/index.m3u8
07:20:31.111 INFO  : 内容匹配: HTTP Live Streaming
07:20:31.111 INFO  : 正在解析媒体信息...
07:20:31.111 WARN  : 检测到Master列表，开始解析全部流信息
07:20:31.123 INFO  : 已解析, 共计 1 条媒体流, 基本流 1 条, 可选音频流 0 条, 可选字幕流 0 条
07:20:31.123 INFO  : Vid 960x540 | 1100 Kbps
07:20:31.138 ERROR : Object reference not set to an instance of an object.

**Comment by nilaoda** [comment]
此bug已修复，但由于他用了类似图床之类的东西传TS片段，目前RE尚未支持自动去除PNG header，可能无法合并
