### ISSUE TITLE
Possible bug with mp4decrypt and save-name

### ISSUE THREAD

**Issue by tarantn** [nilaoda/N_m3u8DL-RE#233]
I think there might be a bug when using mp4decrypt and a save-name with accented characters. 
This does not occur when using shaka-packager or a save-name without those accented characters and mp4decrypt.

Example of a command where no decryption happens:

N_m3u8DL-RE.exe  MPD_URL  --key KID:KEY  --save-name "étest" --mp4-real-time-decryption --live-real-time-merge

I know that shaka-packager should be prefered over mp4decrypt in this case as you show in the log
"WARN : When enabling real-time decryption, it is recommended to use shaka-packager instead of mp4decrypt"

**Comment by pmigue** [comment]
I also have this issue even if I use shaka-packager, if the name or the folder has accents it doesn't decrypt the file correctly.

**Comment by tintanto** [comment]
This bug is still there sadly.
