### ISSUE TITLE
另一种形式的广告，有没有办法跳过？

### ISSUE THREAD

**Issue by dupontjoy** [nilaoda/N_m3u8DL-RE#235]
视频原始m3u8：https://vip.lz-cdn1.com/20221219/19427_be648962/index.m3u8
不像另一个issue的那种广告，url里清楚写了/ad/
如图形式的广告比较隐蔽，151片段的url前缀变成了xxx11，其余正常影片为xxx10
像这种ad-keyword都不好设置，有没有办法？
![图片](https://github.com/nilaoda/N_m3u8DL-RE/assets/4965288/007f05f4-e62b-4b7d-be28-66d10898d7f5)

**Comment by yf718** [comment]
可以写正则的呀

**Comment by yf718** [comment]
--ad-keyword = o\d{3,4}.ts$
