### ISSUE TITLE
How to Download All Video Quality Audio and Subtitles

### ISSUE THREAD

**Issue by fruko321321** [nilaoda/N_m3u8DL-RE#238]
I tried with some codes, m3u8 didn't work when I clicked, how can I download it like in the source file
url :
https://video.gumlet.io/64b89649aefe6ff644827c6c/64b896fa2c2bc76a3c82150a/main.m3u8

**Comment by nilaoda** [comment]
```sh
N_m3u8DL-RE https://video.gumlet.io/64b89649aefe6ff644827c6c/64b896fa2c2bc76a3c82150a/main.m3u8 -sv all -sa all -ss all
```

**Comment by fruko321321** [comment]
mp4 srt downloaded as m4a, I want it to download as in the photo
https://imgur.com/a/VDuQizd
