### ISSUE TITLE
Memory Consumption when RE_LIVE_PIPE_OPTIONS=

### ISSUE THREAD

**Issue by andremxmx** [nilaoda/N_m3u8DL-RE#245]
RE_LIVE_PIPE_OPTIONS="-c copy -f hls -hls_time 8 -hls_flags append_list+delete_segments -hls_list_size 4 ' . $createDir .'/index.m3u8" ' .
    './N_m3u8DL-RE ' .
    '--live-real-time-merge 
xxxxxxxxxxxxxxxxxxxxxxxx  and more code
    
I have a program that use your N_m3u8DL-R, that generates M3U8 files for around 80 channels, and it's working well initially. However, as time passes, the RAM consumption steadily rises, leading to a crash after approximately 12 hours of continuous operation. My server has 32GB RAM and runs on AlmaLinux. When I start the program, the memory usage is only around 2%, but it keeps increasing until it reaches 96% after 12 hours, causing the server to crash.

Is there a way to limit the memory usage of the program while it's generating the M3U8 files to avoid the crash? I would greatly appreciate any suggestions or solutions to this issue. Thank you!

**Comment by xhlove** [comment]
increase to 128GB RAM and reboot everyday ~~

**Comment by nilaoda** [comment]
When the memory usage increases, is the generation of m3u8+ts still normal? Or has it stopped?

**Comment by andremxmx** [comment]
stop the m3u8 and ts generation when i almost run out of ram, with less channel the memory consumption is a lot less, so i only need to reboot every day like xhlove say, the case is i only wanna know if we can auto purge the ram with command or limit the "cache" of the program, if not i will just upgrade the vps, running in a ARM 6Cores 32 GB ram

> When the memory usage increases, is the generation of m3u8+ts still normal? Or has it stopped?

**Comment by andremxmx** [comment]
the problem solve with add swamp with nvme disk 

ONLY DO IT if you have fast nvme disk

sudo fallocate -l 256G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
echo 'vm.swappiness=80' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

now i can restream more than 300 channels in a thiny arm server with only 32 GB ram and 8 Vcpu but fast nvme disk
