### ISSUE TITLE
下载报错ERROR: Padding is invalid and cannot be removed.

### ISSUE THREAD

**Issue by boreasC** [nilaoda/N_m3u8DL-RE#246]
ERROR: Padding is invalid and cannot be removed.

**Comment by nilaoda** [comment]
可能是key有误

**Comment by boreasC** [comment]
> 可能是key有误

已解决，用CLI可以下载，感谢大佬的工具开发~

**Comment by nilaoda** [comment]
> > 可能是key有误
> 
> 已解决，用CLI可以下载，感谢大佬的工具开发~

CLI可以下载 RE不能下载也挺奇怪的。。
