### ISSUE TITLE
mac版下载的音频不完整

### ISSUE THREAD

**Issue by xiaotian-toby** [nilaoda/N_m3u8DL-RE#258]
视频部分是完整的，音频大概会丢失半分钟，一开始少半分钟，到最后半分钟没有声音

**Comment by nilaoda** [comment]
啊这 你提供的信息太少了 我无法判断是什么情况

**Comment by xiaotian-toby** [comment]
尝试了应该是mp4decrypt的问题,只有加密过的ts合并会有这样的问题,之前直接下载mp4decrypt的二进制文件会有这样的问题,后来通过  brew install bento4  安装的版本就正常了
