### ISSUE TITLE
ts文件合并异常,Too many open files

### ISSUE THREAD

**Issue by xiaotian-toby** [nilaoda/N_m3u8DL-RE#268]
异常信息如下:
concat:000.ts|001.ts|002.ts|003.ts|004.ts|005.ts|006.ts|007.ts|008.ts|009.ts|010.ts|011.ts|012.ts|013.ts|014.ts|015.ts|016.ts|017.ts|018.ts|019.ts|020.ts|021.ts|022.ts|023.ts|024.ts|025.ts|026.ts|027.ts|028.ts|029.ts|030.ts|031.ts|032.ts|033.ts|034.ts|035.ts|036.ts|037.ts|038.ts|039.ts|040.ts|041.ts|042.ts|043.ts|044.ts|045.ts|046.ts|047.ts|048.ts|049.ts|050.ts|051.ts|052.ts|053.ts|054.ts|055.ts|056.ts|057.ts|058.ts|059.ts|060.ts|061.ts|062.ts|063.ts|064.ts|065.ts|066.ts|067.ts|068.ts|069.ts|070.ts|071.ts|072.ts|073.ts|074.ts|075.ts|076.ts|077.ts|078.ts|079.ts|080.ts|081.ts|082.ts|083.ts|084.ts|085.ts|086.ts|087.ts|088.ts|089.ts|090.ts|091.ts|092.ts|093.ts|094.ts|095.ts|096.ts|097.ts|098.ts|099.ts|100.ts|101.ts|102.ts|103.ts|104.ts|105.ts|106.ts|107.ts|108.ts|109.ts|110.ts|111.ts|112.ts|113.ts|114.ts|115.ts|116.ts|117.ts|118.ts|119.ts|120.ts|121.ts|122.ts|123.ts|124.ts|125.ts|126.ts|127.ts|128.ts|129.ts|130.ts|131.ts|132.ts|133.ts|134.ts|135.ts|136.ts|137.ts|138.ts|139.ts|140.ts|141.ts|142.ts|143.ts|144.ts|145.ts|146.ts|147.ts|148.ts|149.ts|150.ts|151.ts|152.ts|153.ts|154.ts|155.ts|156.ts|157.ts|158.ts|159.ts|160.ts|161.ts|162.ts|163.ts|164.ts|165.ts|166.ts|167.ts|168.ts|169.ts|170.ts|171.ts|172.ts|173.ts|174.ts|175.ts|176.ts|177.ts|178.ts|179.ts|180.ts|181.ts|182.ts|183.ts|184.ts|185.ts|186.ts|187.ts|188.ts|189.ts|190.ts|191.ts|192.ts|193.ts|194.ts|195.ts|196.ts|197.ts|198.ts|199.ts|200.ts|201.ts|202.ts|203.ts|204.ts|205.ts|206.ts|207.ts|208.ts|209.ts|210.ts|211.ts|212.ts|213.ts|214.ts|215.ts|216.ts|217.ts|218.ts|219.ts|220.ts|221.ts|222.ts|223.ts|224.ts|225.ts|226.ts|227.ts|228.ts|229.ts|230.ts|231.ts|232.ts|233.ts|234.ts|235.ts|236.ts|237.ts|238.ts|239.ts|240.ts|241.ts|242.ts|243.ts|244.ts|245.ts|246.ts|247.ts|248.ts|249.ts|250.ts|251.ts|252.ts|253.ts|254.ts|255.ts|256.ts|257.ts|258.ts|259.ts|260.ts|261.ts|262.ts|263.ts|264.ts|265.ts|266.ts|267.ts|268.ts|269.ts|270.ts|271.ts|272.ts|273.ts|274.ts|275.ts|276.ts|277.ts|278.ts|279.ts|280.ts|281.ts|282.ts|283.ts|284.ts|285.ts|286.ts|287.ts|288.ts|289.ts|290.ts|291.ts|292.ts|293.ts|294.ts|295.ts|296.ts|297.ts|298.ts|299.ts|300.ts|301.ts|302.ts|303.ts|304.ts|305.ts|306.ts|307.ts|308.ts|309.ts|310.ts|311.ts|312.ts|313.ts|314.ts|315.ts|316.ts|317.ts|318.ts|319.ts|320.ts|321.ts|322.ts|323.ts|324.ts|325.ts|326.ts|327.ts|328.ts|329.ts|330.ts|331.ts|332.ts|333.ts|334.ts|335.ts|336.ts|337.ts|338.ts|339.ts|340.ts|341.ts|342.ts|343.ts|344.ts|345.ts|346.ts|347.ts|348.ts|349.ts|350.ts|351.ts|352.ts|353.ts|354.ts|355.ts|356.ts|357.ts|358.ts|359.ts|360.ts|361.ts|362.ts|363.ts|364.ts|365.ts|366.ts|367.ts|368.ts|369.ts|370.ts|371.ts|372.ts|373.ts|374.ts|375.ts|376.ts|377.ts|378.ts|379.ts|380.ts|381.ts|382.ts|383.ts|384.ts|385.ts|386.ts|387.ts|388.ts|389.ts|390.ts|391.ts|392.ts|393.ts|394.ts|395.ts|396.ts|397.ts|398.ts|399.ts|400.ts|401.ts|402.ts|403.ts|404.ts|405.ts|406.ts|407.ts|408.ts|409.ts|410.ts|411.ts|412.ts|413.ts|414.ts|415.ts|416.ts|417.ts|418.ts|419.ts|420.ts|421.ts|422.ts|423.ts|424.ts|425.ts|426.ts|427.ts|428.ts|429.ts|430.ts|431.ts|432.ts|433.ts|434.ts|435.ts|436.ts|437.ts|438.ts|439.ts|440.ts|441.ts|442.ts|443.ts|444.ts|445.ts|446.ts|447.ts|448.ts|449.ts|450.ts|451.ts|452.ts|453.ts|454.ts|455.ts|456.ts|457.ts|458.ts|459.ts|460.ts|461.ts|462.ts|463.ts|464.ts|465.ts|466.ts|467.ts|468.ts|469.ts|470.ts|471.ts|472.ts|473.ts|474.ts|475.ts|476.ts|477.ts|478.ts|479.ts|480.ts|481.ts|482.ts|483.ts|484.ts|485.ts|486.ts|487.ts|488.ts|489.ts|490.ts|491.ts|492.ts|493.ts|494.ts|495.ts|496.ts|497.ts|498.ts|499.ts|500.ts|501.ts|502.ts|503.ts|504.ts|505.ts|506.ts|507.ts|508.ts|509.ts|510.ts|511.ts|512.ts|513.ts|514.ts|515.ts|516.ts|517.ts|518.ts|519.ts|520.ts|521.ts|522.ts|523.ts|524.ts|525.ts|526.ts|527.ts|528.ts|529.ts|530.ts|531.ts|532.ts|533.ts|534.ts|535.ts|536.ts|537.ts|538.ts|539.ts|540.ts|541.ts|542.ts|543.ts|544.ts|545.ts|546.ts|547.ts|548.ts|549.ts|550.ts|551.ts|552.ts|553.ts|554.ts|555.ts|556.ts|557.ts|558.ts|559.ts|560.ts|561.ts|562.ts|563.ts|564.ts|565.ts|566.ts|567.ts|568.ts|569.ts|570.ts|571.ts|572.ts|573.ts|574.ts|575.ts|576.ts|577.ts|578.ts|579.ts|580.ts|581.ts|582.ts|583.ts|584.ts|585.ts|586.ts|587.ts|588.ts|589.ts|590.ts|591.ts|592.ts|593.ts|594.ts|595.ts|596.ts|597.ts|598.ts|599.ts|600.ts|601.ts|602.ts|603.ts|604.ts|605.ts|606.ts|607.ts|608.ts|609.ts|610.ts|611.ts|612.ts|613.ts|614.ts|615.ts|616.ts|617.ts|618.ts|619.ts|620.ts|621.ts|622.ts|623.ts|624.ts|625.ts|626.ts|627.ts|628.ts|629.ts|630.ts|631.ts|632.ts|633.ts|634.ts|635.ts|636.ts|637.ts|638.ts|639.ts|640.ts|641.ts|642.ts|643.ts|644.ts|645.ts|646.ts|647.ts|648.ts|649.ts|650.ts|651.ts|652.ts|653.ts|654.ts|655.ts|656.ts|657.ts|658.ts|659.ts|660.ts|661.ts|662.ts|663.ts|664.ts|665.ts|666.ts|667.ts|668.ts|669.ts|670.ts|671.ts|672.ts|673.ts|674.ts|675.ts|676.ts|677.ts|678.ts|679.ts|: Too many open files

**Comment by xiaotian-toby** [comment]
使用 ulimit -a 查询到的信息如下:

core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 5568
virtual memory          (kbytes, -v) unlimited

打开的文件数量默认限制是256个

建议动态配置分块合并的文件数量限制

**Comment by xiaotian-toby** [comment]
临时解决方案 
在环境变量里新增  ulimit -n <期望的文件打开数量限制>
比如
ulimit -n 10240

**Comment by nilaoda** [comment]
在打开一个issue前请先在现有issue中搜索你的问题。
