### ISSUE TITLE
请问为何会闪退

### ISSUE THREAD

**Issue by zcl92** [nilaoda/N_m3u8DL-RE#269]
我是win10用户，下载了N_m3u8DL-RE_Beta_win-x64，发现点击后闪退，是怎么回事？

另外有人知道从kanopy下载视频的办法吗？

**Comment by dupontjoy** [comment]
包里的只是命令行程序，要用其它方式调用
没有gui程序，可以手动在cmd里输入命令调用，也可以写批处理调用
