### ISSUE TITLE
这个直播源下载报错

### ISSUE THREAD

**Issue by yyxiaofeng** [nilaoda/N_m3u8DL-RE#27]
N_m3u8DL-RE.exe --save-name 6689.ts "http://59.49.41.44/live.aishang.ctlcdn.com/00000110240389_1/playlist.m3u8?CONTENTID=00000110240389_1" --append-url-params --live-real-time-merge 
https://pic.imgdb.cn/item/63291f6a16f2c2beb15c7f93.png

**Comment by nilaoda** [comment]
该源验证UA请求头，使用一下命令：
```
N_m3u8DL-RE.exe --save-name test_LIVE  --append-url-params --live-real-time-merge -H "User-Agent: vlc/3.0" "http://59.49.41.44/live.aishang.ctlcdn.com/00000110240389_1/playlist.m3u8?CONTENTID=00000110240389_1"
```

![image](https://user-images.githubusercontent.com/20772925/191154797-e8fa3bc5-f803-4069-8a7f-1112c6a8c3c0.png)

**Comment by yyxiaofeng** [comment]
好的，感谢老大
