### ISSUE TITLE
下载m3u8文件遇到两个错误

### ISSUE THREAD

**Issue by Wenboli11** [nilaoda/N_m3u8DL-RE#275]
error1:
21:08:10.581 INFO : 开始下载...Vid 1920x1080 | 3080 Kbps | 29.97 | 
avc1.640032,mp4a.40.2
Vid 1920x1080 | 3080 Kbps | 29.97: 0%
21:08:14.367 WARN : Response status code does not indicate success: 470.
21:08:14.368 ERROR: Download first segment failed!
'validto' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ipa' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'hdl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'hash' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

error2:
21:08:35.018 ERROR: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
'l' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ipa' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'hash' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

请问这是为什么？有解决办法吗？

**Comment by nilaoda** [comment]
你需要用英文引号`"`把你的链接包起来
