### ISSUE TITLE
Can not load invalid JSON data: "" 

### ISSUE THREAD

**Issue by Wenboli11** [nilaoda/N_m3u8DL-RE#279]
我用python调用程序下载一个m3u8文件，出现了错误，请问该怎样解决？
18:38:59.997 INFO : 内容匹配: HTTP Live Streaming
18:38:59.998 INFO : 正在解析媒体信息...
18:39:00.282 WARN : 写出meta json
18:39:00.285 INFO : 已解析, 共计 1 条媒体流, 基本流 1 条, 可选音频流 0 条, 可选字幕流 0 条
18:39:00.286 INFO : Vid *AES_128 Kbps | 1759 Segments | ~01h57m14s
18:39:00.290 INFO : 已选择的流:
18:39:00.291 INFO : Vid *AES_128 Kbps | 1759 Segments | ~01h57m14s
18:39:00.291 WARN : 写出meta json
18:39:00.294 INFO : 保存文件名: m3u8_To_MP4
18:39:00.295 INFO : 开始下载...Vid Kbps
Vid Kbps: 0%
18:39:01.489 WARN : 读取媒体信息...
18:39:01.720 INFO : [0x100]: Video, h264 (High) ([27][0][0][0]), 1280x720, 29.97
fps
18:39:01.720 INFO : [0x101]: Audio, aac (LC) ([15][0][0][0]), 131 kb/s
Vid Kbps: 25%
Vid Kbps: 46%
Vid Kbps: 50%
Vid Kbps: 69%
Vid Kbps: 75%
Vid Kbps: 95%
Vid Kbps: 96%
Vid Kbps: 97%
Vid Kbps: 98%
Vid Kbps: 99%
18:41:18.915 INFO : 调用ffmpeg合并中...
18:41:24.036 INFO : Done
Can not load invalid JSON data: ""

**Comment by nilaoda** [comment]
Key不对
