### ISSUE TITLE
希望支持非标m3u8格式解析下载

### ISSUE THREAD

**Issue by yyxiaofeng** [nilaoda/N_m3u8DL-RE#28]
现在好多国外的体育电视台直播流采用的是非标准M3U8直播流，例如http://superbits.tv:2095/live/kC6PZctg/hBbm57AG/11519.ts，希望老大在后面版本中支持该类型的直播流的解析与下载，感谢

**Comment by xhlove** [comment]
用curl挂着一直下载就行

**Comment by yyxiaofeng** [comment]
> 



> 用curl挂着一直下载就行
curl挂着下载也是一会就自己断了，有什么办法或代码让curl断掉重连吗？
