### ISSUE TITLE
ERROR: The input data is not a complete block.

### ISSUE THREAD

**Issue by wenbolics** [nilaoda/N_m3u8DL-RE#282]
09:25:26.954 INFO : Vid *AES_128 Kbps | 3153 Segments | ~03h30m13s
09:25:26.955 WARN : 写出meta json
09:25:26.955 INFO : 保存文件名: m3u8_To_MP4
09:25:26.955 INFO : 开始下载...Vid Kbps
09:25:26.962 ERROR: The input data is not a complete block.

大佬，请问这个问题怎么解决？

**Comment by nilaoda** [comment]
Key 不对或者算法不对
