### ISSUE TITLE
Mac端使用问题

### ISSUE THREAD

**Issue by ouyangcaike** [nilaoda/N_m3u8DL-RE#283]
芯片：Apple M1
系统：macOS 13.5.2 (22G91)
问题：

1. 需要在Terminal中使用`chmod +x N_m3u8DL-RE`命令后才可运行，即下载文件默认不是可执行文件。
2. ts文件过多时（估计超过200），合并视频文件会提示 “Too many open files” 。可能的原因在于合并文件采用了FFmpeg的concat协议，例如`ffmpeg -i "concat:input1.ts|input2.ts|input3.ts" -c copy output.ts`。使用此方式合并视频时，由于FFmpeg只允许有限数目的文件，超过一定数目便会报如上所示的错误。

**Comment by nilaoda** [comment]
2可以自行设置这个值的限制

**Comment by ouyangcaike** [comment]
> 2可以自行设置这个值的限制

请问是使用哪个命令行参数进行设置？

**Comment by nilaoda** [comment]
在 macOS 上，可以使用 `ulimit` 命令来设置打开文件数的限制。要增加打开文件数的限制，可以按照以下步骤操作：

1. 打开终端应用程序。
2. 运行以下命令以查看当前的打开文件数限制：

   ```shell
   ulimit -n
   ```

   这将显示当前的打开文件数限制。

3. 要增加打开文件数限制，可以使用以下命令：

   ```shell
   ulimit -n <new_limit>
   ```

   将 `<new_limit>` 替换为您想要设置的新限制值。请注意，您可能需要具有管理员权限（例如，使用 `sudo` 命令）才能更改限制。

4. 运行以下命令验证新的限制是否已应用：

   ```shell
   ulimit -n
   ```

   应该显示您刚刚设置的新限制值。

请注意，更改打开文件数限制可能会对系统性能产生影响，因此请谨慎调整限制值。确保将限制设置为适当的值，以避免系统资源耗尽或导致其他问题。

**Comment by ouyangcaike** [comment]
> 在 macOS 上，可以使用 `ulimit` 命令来设置打开文件数的限制。要增加打开文件数的限制，可以按照以下步骤操作：
> 
> 1. 打开终端应用程序。
> 2. 运行以下命令以查看当前的打开文件数限制：
>    ```shell
>    ulimit -n
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    这将显示当前的打开文件数限制。
> 3. 要增加打开文件数限制，可以使用以下命令：
>    ```shell
>    ulimit -n <new_limit>
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    将 `<new_limit>` 替换为您想要设置的新限制值。请注意，您可能需要具有管理员权限（例如，使用 `sudo` 命令）才能更改限制。
> 4. 运行以下命令验证新的限制是否已应用：
>    ```shell
>    ulimit -n
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    应该显示您刚刚设置的新限制值。
> 
> 请注意，更改打开文件数限制可能会对系统性能产生影响，因此请谨慎调整限制值。确保将限制设置为适当的值，以避免系统资源耗尽或导致其他问题。

这个问题确实是macOS的设置引发的，我将`ulimit -n <new_limit>`写入.zshrc后便修复了问题2。多谢😆
