### ISSUE TITLE
怎么编译成可直接在linux-x64上执行的文件？

### ISSUE THREAD

**Issue by haskermiller** [nilaoda/N_m3u8DL-RE#287]
没弄过C#，搜了几个教程跟着做一直失败

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-RE/releases

**Comment by loginovglczeduard548** [comment]
我也有同样的问题，改了源码要重新构建部署到Ubuntu 20.04上面
需要在Windows还是Linux下面构建？
构建要用到哪些工具？
还希望作者能提点下

**Comment by nilaoda** [comment]
> 我也有同样的问题，改了源码要重新构建部署到Ubuntu 20.04上面 需要在Windows还是Linux下面构建？ 构建要用到哪些工具？ 还希望作者能提点下

可以在Actions页面手动触发构建
