### ISSUE TITLE
錄製完不會自動混流，MP4不行，想混成ts

### ISSUE THREAD

**Issue by tvbent** [nilaoda/N_m3u8DL-RE#29]

**Comment by nilaoda** [comment]
具体描述你的需求

**Comment by tvbent** [comment]
即是视频和音频分开，并行下载后不会自动混流成ts或MP4，已经加上--mux-after-done&nbsp;或&nbsp;-M format=mp4都不行&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nilaoda/N_m3u8DL-RE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-RE] 錄製完不會自動混流，MP4不行，想混成ts (Issue #29)





 
具体描述你的需求

**Comment by nilaoda** [comment]
直播还是点播？目前直播没有实现实时混流
