### ISSUE TITLE
请问用什么工具把webrtc直播源下载MP4视频

### ISSUE THREAD

**Issue by rufan321** [nilaoda/N_m3u8DL-RE#290]
老大，

https://www.taoguba.com.cn/weblive/userLiveView/2271

Fiddler 抓包得到下面的地址：
str_stream_url=webrtc://tpull.taoguba.com.cn/live/6130889A2271_TD1080?txSecret=ae4ee4e84634da85d19d5a50bad97935&txTime=65201ECD
请问用什么工具把webrtc直播源下载MP4视频

**Comment by nilaoda** [comment]
目前不支持

**Comment by rufan321** [comment]
谢谢老大，但请问你知道用什么工具能下载吗？
