### ISSUE TITLE
这么获取腾讯视频的m3u8地址

### ISSUE THREAD

**Issue by zimq** [nilaoda/N_m3u8DL-RE#293]
iOS或者极光TV的 可以选择画质

**Comment by CrymanChen** [comment]
m3u8地址隐藏了。我的办法是查看下面这个POST请求，响应中有m3u8数据。  
`response = requests.post('https://vd6.l.qq.com/proxyhttp', cookies=cookies, headers=headers, data=data)`
先在浏览器中选择画质再捕获对应的网络请求即可  
但m3u8数据缺少baseURL 需要再从proxyhttp中寻找 最后做个分割即可  
`last_slash = baseURL_raw.rfind('/')
if last_slash_index != -1:
    base_url = baseURL_raw[:last_slash + 1]
else:
...`  
调用N_m3u8DL-RE即可 注意添加“--base-url <base_url>”  
`command = f're.exe {filename}.m3u8 --base-url {base_url}'`

**Comment by CrymanChen** [comment]
m3u8地址被隐藏了。
我的办法是查看下面这个POST请求，响应中有m3u8数据。
`response = requests.post('https://vd6.l.qq.com/proxyhttp', cookies=cookies, headers=headers, data=data)`
先在浏览器中选择画质再捕获对应的网络请求即可。但m3u8数据缺少baseURL 需要再从proxyhttp中寻找 最后做个分割即可

```
last_slash = baseURL_raw.rfind('/')
if last_slash_index != -1:
    base_url = baseURL_raw[:last_slash + 1]
else:
...
```
调用N_m3u8DL-RE即可 注意添加“--base-url <base_url>”
`command = f're.exe {filename}.m3u8 --base-url {base_url}'`

**Comment by nilaoda** [comment]
```ts
try {
    var _json = JSON.parse(localStorage.__thumbplayer_vod_flow_report__);
    var _vdata = Array.from(Object.keys(_json)).filter(x => _json[x]['data']['vid'] == __PINIA__.global.currentVid).map(x => _json[x]['data'])[0];
    var _drm = _vdata.drm;
    if (_drm != 0) { alert("不支持DRM视频"); }
    else {
        var _m3u8 = _vdata.vurl;
        var _title = __PINIA__.global.videoInfo.title;
        var a = prompt(_title, _m3u8);
    }
} catch (error) {
    alert("解析失败");
}
```
![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/20772925/189efa71-0fd8-4368-9c5c-e05c99e1e1b0)

**Comment by zimq** [comment]
> ```ts
> try {
>     var _json = JSON.parse(localStorage.__thumbplayer_vod_flow_report__);
>     var _vdata = Array.from(Object.keys(_json)).filter(x => _json[x]['data']['vid'] == __PINIA__.global.currentVid).map(x => _json[x]['data'])[0];
>     var _drm = _vdata.drm;
>     if (_drm != 0) { alert("不支持DRM视频"); }
>     else {
>         var _m3u8 = _vdata.vurl;
>         var _title = __PINIA__.global.videoInfo.title;
>         var a = prompt(_title, _m3u8);
>     }
> } catch (error) {
>     alert("解析失败");
> }
> ```
> ![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/20772925/189efa71-0fd8-4368-9c5c-e05c99e1e1b0)

我用iOS客户端和模拟器极光tv都抓到了，re默认合成的杜比视界是ts格式的，cl合并的杜比视界mp4用iOS的下载链接解码器id是正常的，可以用win11自带视频观看，cl用极光tv合成的mp4解码器id好像有问题，id只有一个数字，只能用energy media player解码观看

**Comment by nilaoda** [comment]
RE通常会自动判断杜比视界的封装后决定最后的文件后缀，你可以使用 [DoviMuxer](https://github.com/nilaoda/DoViMuxer/) 将 TS 文件转换到 MP4

**Comment by zimq** [comment]
> ```ts
> try {
>     var _json = JSON.parse(localStorage.__thumbplayer_vod_flow_report__);
>     var _vdata = Array.from(Object.keys(_json)).filter(x => _json[x]['data']['vid'] == __PINIA__.global.currentVid).map(x => _json[x]['data'])[0];
>     var _drm = _vdata.drm;
>     if (_drm != 0) { alert("不支持DRM视频"); }
>     else {
>         var _m3u8 = _vdata.vurl;
>         var _title = __PINIA__.global.videoInfo.title;
>         var a = prompt(_title, _m3u8);
>     }
> } catch (error) {
>     alert("解析失败");
> }
> ```
> ![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/20772925/189efa71-0fd8-4368-9c5c-e05c99e1e1b0)
 我昨天正好下了个繁城第一集的4k杜比视界，用re下的然后FFmpeg ts转的mp4，re的网速显示好像有点问题，显示的mbps，实际网速是mb/s

**Comment by nilaoda** [comment]
MBps = MB/s

**Comment by zimq** [comment]
> MBps = MB/s

看了下好像确实是这样，但是维基百科说一般用后面这个，有点像1g本来是等于1000m这个事
