### ISSUE TITLE
如何进行 "不下载只合并"操作

### ISSUE THREAD

**Issue by raddyfiy** [nilaoda/N_m3u8DL-RE#301]
有时候分片都下载完了，程序进入合并阶段，此时由于别的原因进程被杀死，且下载url已过期。重新执行旧命令会提示url访问失败，就算加了
--skip-download   True  --check-segments-count False
也不行，照样会访问url。
我知道ffmpeg可以手动合并，但总感觉不如用N_m3u8。
有什么命令能够强制软件不访问URL，直接从文件夹里找分片合并呢？
谢谢

**Comment by nilaoda** [comment]
可以直接`copy /b *.ts ALL`

**Comment by raddyfiy** [comment]
好的，谢谢

**Comment by MarvinXu** [comment]
我的下载文件没有 `.ts`，结构是这样的：
```
│  meta.json
│  meta_selected.json
│  raw.m3u8
│
└─0____
        1712816052.m4s
        1712816054.m4s
        1712816056.m4s
        1712816060.m4s
        1712816062.m4s
        1712816064.m4s
        1712816074.m4s
        1712816076.m4s
        1712816078.m4s
        1712816080.m4s
        1712816082.m4s
        1712816084.m4s
        1712816088.m4s
        1712816090.m4s
        1712816092.m4s
        1712816096.m4s
        1712816098.m4s
        1712816100.m4s
        1712816102.m4s
        1712816104.m4s
        1712816106.m4s
        1712816110.m4s
        1712816112.m4s
        1712816114.m4s
        _init.mp4
```

**Comment by MarvinXu** [comment]
尝试了 `copy /b *.m4s all.mp4`，合并了但播放没有图像，只有呲呲啦啦的声音

**Comment by raddyfiy** [comment]
反馈一下，我的解决了，把 _init.mp4和其他m4s按顺序合并就行。

**Comment by raddyfiy** [comment]
> 尝试了 `copy /b *.m4s all.mp4`，合并了但播放没有图像，只有呲呲啦啦的声音

这说明是加密视频，需要先解密后再合并

**Comment by raddyfiy** [comment]
close

**Comment by MarvinXu** [comment]
可以说下怎么操作吗

> > 尝试了 `copy /b *.m4s all.mp4`，合并了但播放没有图像，只有呲呲啦啦的声音
> 
> 这说明是加密视频，需要先解密后再合并

**Comment by MarvinXu** [comment]
成功了。命令是 `copy /b _init.mp4 + /b *.m4s all.mp4`

**Comment by zimq** [comment]
> 可以直接`copy /b *.ts ALL`

如果是杜比视界的ts怎么合并
