### ISSUE TITLE
能否在完成下载完成后混流为mp4格式

### ISSUE THREAD

**Issue by 1299172402** [nilaoda/N_m3u8DL-RE#309]
目前下载完成后就是ts文件，对于一些在线播放（OneDrive）的情况不是很友好，例如无法正确获取当前播放的时间，或者无法获取总时间，无法快进快退视频。所以想问下作者有没有相关选项，不胜感激

**Comment by nilaoda** [comment]
默认就是混流到MP4的……

或者尝试使用 `-M mp4`

**Comment by 1299172402** [comment]
按照你说的办法成功了，谢谢作者
