### ISSUE TITLE
实测使用此工具的问题

### ISSUE THREAD

**Issue by whp98** [nilaoda/N_m3u8DL-RE#31]
1.j a b l e . t v 
此网站m3u8就在主页代码中提取出来下载在老版能下载，新版就会少文件，不断有超时重试

2. 文件合并问题
大于 1800分片 合并不了 命令过长

基于以上两点，我目前在ubuntu 20.04 上还无法正常使用

**Comment by whp98** [comment]
以上是和我用windows对比出来的
不懂为啥要完全重做
按理说都是 C#代码应该可以移植的

而且老代码也有更稳定功能相对完善的有点

**Comment by nilaoda** [comment]
因为旧版下载器完全没有考虑多轨道下载，要想在原来的代码上支持基本上也相当于重写了。还不如干脆重新写，更容易增加功能，也更容易维护。

1800分片的问题属于已知问题，超时重试的问题我晚点看看……

**Comment by whp98** [comment]
感谢！期待！

**Comment by nilaoda** [comment]
#7
