### ISSUE TITLE
[Bug] 无法下载得到的音频

### ISSUE THREAD

**Issue by ac1982** [nilaoda/N_m3u8DL-RE#33]
感谢开发者。老版本可以正常下载dedao.cn的音频，但是新版本会卡住，然后就没有然后了。我即便设置了--log-level debug 也没拿到什么有效错误信息。
示例地址：https://m.igetget.com/ddmedia/public/v1/m3u8/3403820841304864/52/m.m3u8
卡住的位置：
```
17:15:04.338 DEBUG : 7E E9 09 0A B0 00 42 05 C7 2B 06 8E AE 94 80 1C
17:15:04.363 INFO  : 已解析, 共计 1 条媒体流, 基本流 1 条, 可选音频流 0 条, 可选字幕流 0 条
17:15:04.409 INFO  : Vid *AES_128 Kbps | 48 Segments | ~11m54s
17:15:04.415 INFO  : 已选择的流:
17:15:04.416 INFO  : Vid *AES_128 Kbps | 48 Segments | ~11m54s
```

**Comment by nilaoda** [comment]
```
N_m3u8DL-RE.exe "https://m.igetget.com/ddmedia/public/v1/m3u8/3403820841304864/52/m.m3u8"
```

![image](https://user-images.githubusercontent.com/20772925/192093558-aebcf793-56ce-4866-b7a5-9785e0774fcd.png)

**Comment by ac1982** [comment]
> ```
> N_m3u8DL-RE.exe "https://m.igetget.com/ddmedia/public/v1/m3u8/3403820841304864/52/m.m3u8"
> ```
> 
> ![image](https://user-images.githubusercontent.com/20772925/192093558-aebcf793-56ce-4866-b7a5-9785e0774fcd.png)

我仍然卡在我提交的进度，是因为我编译的是win-arm64版本么？确实我编译X64版本就没有这个问题。请问我在哪里看日志，提供更多的信息给你？

**Comment by nilaoda** [comment]
如果你是用户的话，直接在[actions](https://github.com/nilaoda/N_m3u8DL-RE/actions)中下载编译好的版本就可以了。如果你想自己编译，请编译Release而非Debug。

**Comment by ac1982** [comment]
很感谢你的积极回复。我是想通过这个项目实际练练手，我通过dotnet publish -r win10-arm64编译失败，请教这是什么问题呢，谢谢nilaoda：
```
    正在创建库 bin\Debug\net7.0\win10-arm64\native\N_m3u8DL-RE.lib 和对象 bin\Debug\net
  7.0\win10-arm64\native\N_m3u8DL-RE.exp
  系统找不到指定的路径。
```

**Comment by nilaoda** [comment]
@ac1982 dotnet publish -r win-arm64 -c Release
