### ISSUE TITLE
Padding is invalid and cannot be removed.

### ISSUE THREAD

**Issue by yf718** [nilaoda/N_m3u8DL-RE#335]
./N_m3u8DL-RE https://1080p.jszyplay.com/play/7e5oO0vb/index.m3u8 下载时候报了个错然后中断了
 ERROR: Padding is invalid and cannot be removed.

**Comment by RikaCelery** [comment]
重复issue

> 这个错误可能来自于错误的解密密钥或者解密算法的错误

请参考以下issue
+ #51
+ #121
+ #246
+ #279

**Comment by ningsibuqu** [comment]
> [RikaCelery](/RikaCelery)
换cli可下载，不知道为啥

**Comment by RikaCelery** [comment]
> > [RikaCelery](/RikaCelery)
> 
> 换cli可下载，不知道为啥
> 

最新的pr修复一个继续下载文件时重复解密的bug，你可以去我actions看看能不能用

**Comment by ningsibuqu** [comment]
> > > [RikaCelery](/RikaCelery)
> > 
> > 
> > 换cli可下载，不知道为啥
> 
> 最新的pr修复一个继续下载文件时重复解密的bug，你可以去我actions看看能不能用

昨天就是用你的版本试的，不行，后面用cli发现其实也不行

发现原因是音轨的其中一个分片无法解密，就一直 m4s.tmp，m3u8 的，其他分片都正常解密
