### ISSUE TITLE
本地文件被多次解密导致报错 The input data is not a complete block

### ISSUE THREAD

**Issue by BlueHtml** [nilaoda/N_m3u8DL-RE#345]
你好，我发现 当前逻辑会优先使用`本地已经下载好的文件`（参见[代码1](https://github.com/nilaoda/N_m3u8DL-RE/blob/8fdb6bc90ba128b91bff32d32ed6152f88584374/src/N_m3u8DL-RE/Downloader/SimpleDownloader.cs#L89)和[代码2](https://github.com/nilaoda/N_m3u8DL-RE/blob/8fdb6bc90ba128b91bff32d32ed6152f88584374/src/N_m3u8DL-RE/Downloader/SimpleDownloader.cs#L37)）。它存在一个问题，就是会把这个本地文件再走一遍解密流程。但是这个文件可能已经解密过了，再次解密就会报错`The input data is not a complete block.`。

我修复了一下([PR](https://github.com/nilaoda/N_m3u8DL-RE/pull/344))，把`改名操作`作为整个处理流程(下载和解密)的最后一步，**改名完成**即认为该文件已经是**最终文件**了。当再次下载时，如果本地已经存在分片文件，就直接返回，不再走处理逻辑(下载和解密)。

## 详细说明

**当前逻辑**：
1. 判断**本地**是否已经存在 *正式文件`file.m3u8`*：
    - **存在**：使用**本地**已经下载好的 *正式文件`file.m3u8`*。
    - **不存在**：重新下载。
        1. 创建临时文件`file.m3u8.tmp`；
        2. 下载文件并写入；
        3. 改名为正式文件`file.m3u8`；
2. 判断是否加密：
    - **加密**：处理并重写  *正式文件`file.m3u8`*（解密->Image头处理->Gzip解压）。
    - **未加密**：跳过。
3. 返回 *正式文件`file.m3u8`*。

**修复后的逻辑**：
1. 判断**本地**是否已经存在 *正式文件`file.m3u8`*：
    - **存在**：使用**本地**已经下载好的 *正式文件`file.m3u8`*。
    - **不存在**：重新下载，并做处理。
        1. 创建临时文件`file.m3u8.tmp`；
        2. 下载文件并写入；
        3. 判断是否加密：
            - **加密**：处理并重写  *临时文件`file.m3u8.tmp`*（解密->Image头处理->Gzip解压）。
            - **未加密**：跳过。
        4. 改名为正式文件`file.m3u8`；
2. 返回 *正式文件`file.m3u8`*。

## 相关图片

**当前逻辑：重复下载时会报错`The input data is not a complete block.`**：

![re1](https://github.com/nilaoda/N_m3u8DL-RE/assets/17940898/3f182426-d8eb-4f7a-bf32-8d8d75799fc3)

**修复后的逻辑：会重用本地已经下载好的分片文件，不会报错**：

![re](https://github.com/nilaoda/N_m3u8DL-RE/assets/17940898/b34e73a1-8a73-4d6d-b8c0-e41bda799d39)

**Comment by nilaoda** [comment]
#344
