### ISSUE TITLE
求教mpd的key怎么抓取

### ISSUE THREAD

**Issue by bryanyeong97** [nilaoda/N_m3u8DL-RE#348]
有大佬知道吗，我要下载的视频是日本mgstage官网的，是mpd加密格式，要怎么抓取视频的key，然后使用此软件下载，求教，先谢谢了

**Comment by violetteflutter** [comment]
留个邮箱，帮你下

**Comment by violetteflutter** [comment]
虽然但是，看不到你的邮箱

**Comment by missdgsn** [comment]
就是这样，然后那样，最后这样，然后用mp4decrypt解密，嗯，不用回我，不教人

**Comment by wnpllrzodiac** [comment]
抓key这种事还明目张胆的要人教。。。
