### ISSUE TITLE
max x64下运行  mp4decrypt 找不到是什么问题

### ISSUE THREAD

**Issue by baicaiit** [nilaoda/N_m3u8DL-RE#35]
我在mac下运行 报了一下错误
`01:29:49.366 ERROR : mp4decrypt not found!`

**Comment by nilaoda** [comment]
如果你需要解密加密mp4文件 需要自行准备mp4decrypt文件

**Comment by nilaoda** [comment]
`brew install bento4`

或下载二进制文件：https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-639.universal-apple-macosx.zip
