### ISSUE TITLE
能否增加去掉分片广告的功能，不能自动手工也可以，请看详细说明。

### ISSUE THREAD

**Issue by fwtomail** [nilaoda/N_m3u8DL-RE#353]
现在大多数m3u8的视频网站，都会在m3u8的分片中加入广告的分片。虽然是独立于正常视频存在的，但用N_m3u8DL下载时，正常情况会把所有分片进行合并成一个整体。
我想，能不能加入一个开关功能，在开启状态下，下载m3u8文件时，能手工修改m3u8文件内容，这样可以避免广告的分片也一起合并。
下面图片中红框就是广告，正常情况下无法手工删除。
![Snipaste_2024-02-13_23-23-39](https://github.com/nilaoda/N_m3u8DL-RE/assets/50854659/392f69e4-f590-45d2-8567-a3cf50a1c009)

**Comment by fwtomail** [comment]
使用正则排除也可以。好多视频都是有规律的。

**Comment by RikaCelery** [comment]
先下载，编辑后再使用下载器

正则功能我记得已经有了

**Comment by fwtomail** [comment]
已解决，成功去掉广告。
