### ISSUE TITLE
Errors during  last source's build

### ISSUE THREAD

**Issue by endmarsfr** [nilaoda/N_m3u8DL-RE#354]
Hello,

I tried `dotnet build src/N_m3u8DL-RE -r win-x64 -c Release -o artifact-x64 to build latest source.`

Seems Spectre.Console, PublishAotCompressed , ... and other packages are missing.
but when i tried `dotnet add package Spectre.Console` in project " N_m3u8DL-RE.Common.
I had an error : "No version available for package Spectre.Console"

Could you please help me to solve that ?

Regards

here are the log messages  :
`D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Parser\N_m3u8DL-RE.Parser.csproj : error NU1100: Impossible de résoudre 'Spectre.Console (>= 0.47.1-preview.0.11)' pour 'net7.0'. [D:\N_m3u8DL-RE\src\N_m3u8DL
-RE\N_m3u8DL-RE.csproj]
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'PublishAotCompressed (>= 1.0.0)' pour 'net8.0'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Common\N_m3u8DL-RE.Common.csproj : error NU1100: Impossible de résoudre 'Spectre.Console (>= 0.47.1-preview.0.11)' pour 'net7.0'. [D:\N_m3u8DL-RE\src\N_m3u8DL
-RE\N_m3u8DL-RE.csproj]
D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Parser\N_m3u8DL-RE.Parser.csproj : error NU1100: Impossible de résoudre 'Spectre.Console (>= 0.47.1-preview.0.11)' pour 'net7.0/win-x64'. [D:\N_m3u8DL-RE\src\
N_m3u8DL-RE\N_m3u8DL-RE.csproj]
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'NiL.JS (>= 2.5.1600)' pour 'net8.0'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Common\N_m3u8DL-RE.Common.csproj : error NU1100: Impossible de résoudre 'Spectre.Console (>= 0.47.1-preview.0.11)' pour 'net7.0/win-x64'. [D:\N_m3u8DL-RE\src\
N_m3u8DL-RE\N_m3u8DL-RE.csproj]
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'System.CommandLine (>= 2.0.0-beta4.22272.1)' pour 'net8.0'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'Microsoft.DotNet.ILCompiler (>= 8.0.2)' pour 'net8.0'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'Microsoft.NET.ILLink.Tasks (>= 8.0.2)' pour 'net8.0'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'Spectre.Console (>= 0.47.1-preview.0.11)' pour 'net8.0'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'PublishAotCompressed (>= 1.0.0)' pour 'net8.0/win-x64'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'NiL.JS (>= 2.5.1600)' pour 'net8.0/win-x64'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'System.CommandLine (>= 2.0.0-beta4.22272.1)' pour 'net8.0/win-x64'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'Microsoft.DotNet.ILCompiler (>= 8.0.2)' pour 'net8.0/win-x64'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'Microsoft.NET.ILLink.Tasks (>= 8.0.2)' pour 'net8.0/win-x64'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'Spectre.Console (>= 0.47.1-preview.0.11)' pour 'net8.0/win-x64'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE\N_m3u8DL-RE.csproj : error NU1100: Impossible de résoudre 'runtime.win-x64.Microsoft.DotNet.ILCompiler (= 8.0.2)' pour 'net8.0'.
D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Common\N_m3u8DL-RE.Common.csproj : error NU1100: Impossible de résoudre 'Microsoft.NETCore.App.Ref (= 7.0.16)' pour 'net7.0'. [D:\N_m3u8DL-RE\src\N_m3u8DL-RE\
N_m3u8DL-RE.csproj]
D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Parser\N_m3u8DL-RE.Parser.csproj : error NU1100: Impossible de résoudre 'Microsoft.NETCore.App.Ref (= 7.0.16)' pour 'net7.0'. [D:\N_m3u8DL-RE\src\N_m3u8DL-RE\
N_m3u8DL-RE.csproj]
D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Common\N_m3u8DL-RE.Common.csproj : error NU1100: Impossible de résoudre 'Microsoft.WindowsDesktop.App.Ref (= 7.0.16)' pour 'net7.0'. [D:\N_m3u8DL-RE\src\N_m3u
8DL-RE\N_m3u8DL-RE.csproj]
D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Parser\N_m3u8DL-RE.Parser.csproj : error NU1100: Impossible de résoudre 'Microsoft.WindowsDesktop.App.Ref (= 7.0.16)' pour 'net7.0'. [D:\N_m3u8DL-RE\src\N_m3u
8DL-RE\N_m3u8DL-RE.csproj]
D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Common\N_m3u8DL-RE.Common.csproj : error NU1100: Impossible de résoudre 'Microsoft.AspNetCore.App.Ref (= 7.0.16)' pour 'net7.0'. [D:\N_m3u8DL-RE\src\N_m3u8DL-
RE\N_m3u8DL-RE.csproj]
D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Parser\N_m3u8DL-RE.Parser.csproj : error NU1100: Impossible de résoudre 'Microsoft.AspNetCore.App.Ref (= 7.0.16)' pour 'net7.0'. [D:\N_m3u8DL-RE\src\N_m3u8DL-
RE\N_m3u8DL-RE.csproj]`

`  Writing C:\Users\jtomeh\AppData\Local\Programs\msys64\tmp\tmp2fagni.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Ajout de PackageReference pour le package 'Spectre.Console' dans le projet 'D:\N_m3u8DL-RE\src\N_m3u8DL-RE.Common\N_m3u8DL-RE.Common.csproj'.
error: Aucune version n'est disponible pour le package 'Spectre.Console'.`

**Comment by RikaCelery** [comment]
**Comment <PublishAot>true</PublishAot> ＆ build**

*（I use .Net8)*

---

Btw, github actions can build with `PublishAot` and trim.

Just use actions.^ω^

**Comment by endmarsfr** [comment]
Hi RikaCelery,

Thanks for your help
I am using .Net 8 too.
I commented `<PublishAot>true</PublishAot>` and tried to rebuild but still in error for me.

**Comment by endmarsfr** [comment]
Hi

I solved, i can build latest sources without commenting `<PublishAot>true</PublishAot>`
I used too .Net 8 too.
Nuget source was missing on my device.

Here is the way i used to build latest :

`git clone https://github.com/nilaoda/N_m3u8DL-RE.git

dotnet nuget add source "https://api.nuget.org/v3/index.json" --name "nuget.org"

dotnet nuget list source

cd N_m3u8DL-RE

dotnet build src/N_m3u8DL-RE -r win-x64 -c Release -o artifact-x64`
