### ISSUE TITLE
Download multiple streams

### ISSUE THREAD

**Issue by pokemaster974** [nilaoda/N_m3u8DL-RE#357]
We can select multiple same streams (for example multiples videos or multiples audios) :
![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/28442699/46d93fe6-1917-45cd-b0dd-7420144f9948)

But we can't do this manually with `--select-audio lang="fr+en"` (tried with operator "+", ",", ";" and directly with the id) :
![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/28442699/42047a8d-1992-4dd4-a782-21f800a514b3)

Is it expected or a bug ?

**Comment by simonbcn** [comment]
Same problem.
I want to download 4K and 1080p video formats from the same source but I cannot automate this process because there is no option for this.

**Comment by nilaoda** [comment]
`--select-audio lang="fr|en"`

**Comment by nilaoda** [comment]
> Same problem. I want to download 4K and 1080p video formats from the same source but I cannot automate this process because there is no option for this.

See select-video more help.

**Comment by simonbcn** [comment]
> See select-video more help.

I will try it, but in this case `morehelp`'s output does not help: 

```
$ n-m3u8dl-re --morehelp select-video
More Help:

--select-video

Select video streams by regular expressions. OPTIONS is a colon separated list of:

id=REGEX:lang=REGEX:name=REGEX:codec=REGEX:res=REGEX:frame=REGEX
segsMin=number:segsMax=number:ch=REGEX:range=REGEX:url=REGEX
plistDurMin=hms:plistDurMax=hms:for=FOR

* for=FOR: Select type. best[number], worst[number], all (Default: best)

Examples:
# select best video
-sv best
# select 4K+HEVC video
-sv res="3840*":codec=hvc1:for=best
# Select best video with duration longer than 1 hour 20 minutes 30 seconds
-sv plistDurMin="1h20m30s":for=best
```
There is no example where the `|` operator is used.
