### ISSUE TITLE
Error 500  Response status code

### ISSUE THREAD

**Issue by andremxmx** [nilaoda/N_m3u8DL-RE#368]
Exception  => Response status code does not indicate success: 500 (Internal Server Error).

I get this error with n_m3u8DL-RE but when i use the same channel with

https://chromewebstore.google.com/detail/reproductor-mpdm3u8m3uepg/opmeopcambhfimffbomjgemehjkbbmji

all work good with the extension

LINK for extension working channel

https://sam-py-edge02.tigo.com.py/VMX4_widevine/rolling-buffer/TigoSportsHD/TigoSportsHD/transmux/index.mpd?ck=eyJiNTJhN2ZhOTFmYjAzMWEzZDZmMmE1MDU0MTRiNmZjZCI6ImE2NTVhMjJmOWMwYTY2NTc0YjVkOTVkZWUyMTJmYmY5In0%3D

there is the log file of erros

01:38:18.899 EXTRA: Ah oh!
RetryCount => 100
Exception  => Response status code does not indicate success: 500 (Internal Server Error).
Url        => https://sam-py-edge02.tigo.com.py/ccur-session/01_3943293394/VMX4_widevine/rolling-buffer/TigoSports3HDPY/TigoSports3HDPY/transmux/CCURStream_TigoSports3HDPY1-10_-2564402223.cmfa
01:38:18.927 EXTRA: Ah oh!
RetryCount => 100
Exception  => Response status code does not indicate success: 500 (Internal Server Error).
Url        => https://sam-py-edge02.tigo.com.py/ccur-session/01_3943293394/VMX4_widevine/rolling-buffer/TigoSports3HDPY/TigoSports3HDPY/transmux/CCURStream_TigoSports3HDPY1-10_-2564402222.cmfa
01:38:18.962 EXTRA: Ah oh!
RetryCount => 100
Exception  => Response status code does not indicate success: 500 (Internal Server Error).
Url        => https://sam-py-edge02.tigo.com.py/ccur-session/01_3943293394/VMX4_widevine/rolling-buffer/TigoSports3HDPY/TigoSports3HDPY/transmux/CCURStream_TigoSports3HDPY1-1_-2564402223.cmfv

command used

./N_m3u8DL-RE --live-real-time-merge --live-take-count 3 --live-keep-segments false --check-segments-count false --live-wait-time 10 --write-meta-json False --download-retry-count 100 --tmp-dir /www/wwwroot/xxxxxxx/bin/temp/data/ --thread-count 12 --del-after-done --live-pipe-mux --log-level OFF -sa all -sv best https://sam-py-edge02.tigo.com.py/VMX4_widevine/rolling-buffer/TigoSports3HDPY/TigoSports3HDPY/transmux/index.mpd -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" --key f62e93559765dfa6a89d2842b2b6d64a:9f6a8cf0bcb1d17ce79ea93d0d9c3d83

![photo_2024-03-04_22-54-06](https://github.com/nilaoda/N_m3u8DL-RE/assets/10226983/04fe604c-2d45-4a52-97ba-07201a06c8e3)

**Comment by futbolparaguayotv** [comment]
> Exception => Response status code does not indicate success: 500 (Internal Server Error).
> 
> I get this error with n_m3u8DL-RE but when i use the same channel with
> 
> https://chromewebstore.google.com/detail/reproductor-mpdm3u8m3uepg/opmeopcambhfimffbomjgemehjkbbmji
> 
> all work good with the extension
> 
> LINK for extension working channel
> 
> https://sam-py-edge02.tigo.com.py/VMX4_widevine/rolling-buffer/TigoSportsHD/TigoSportsHD/transmux/index.mpd?ck=eyJiNTJhN2ZhOTFmYjAzMWEzZDZmMmE1MDU0MTRiNmZjZCI6ImE2NTVhMjJmOWMwYTY2NTc0YjVkOTVkZWUyMTJmYmY5In0%3D
> 
> there is the log file of erros
> 
> 01:38:18.899 EXTRA: Ah oh! RetryCount => 100 Exception => Response status code does not indicate success: 500 (Internal Server Error). Url => https://sam-py-edge02.tigo.com.py/ccur-session/01_3943293394/VMX4_widevine/rolling-buffer/TigoSports3HDPY/TigoSports3HDPY/transmux/CCURStream_TigoSports3HDPY1-10_-2564402223.cmfa 01:38:18.927 EXTRA: Ah oh! RetryCount => 100 Exception => Response status code does not indicate success: 500 (Internal Server Error). Url => https://sam-py-edge02.tigo.com.py/ccur-session/01_3943293394/VMX4_widevine/rolling-buffer/TigoSports3HDPY/TigoSports3HDPY/transmux/CCURStream_TigoSports3HDPY1-10_-2564402222.cmfa 01:38:18.962 EXTRA: Ah oh! RetryCount => 100 Exception => Response status code does not indicate success: 500 (Internal Server Error). Url => https://sam-py-edge02.tigo.com.py/ccur-session/01_3943293394/VMX4_widevine/rolling-buffer/TigoSports3HDPY/TigoSports3HDPY/transmux/CCURStream_TigoSports3HDPY1-1_-2564402223.cmfv
> 
> command used
> 
> ./N_m3u8DL-RE --live-real-time-merge --live-take-count 3 --live-keep-segments false --check-segments-count false --live-wait-time 10 --write-meta-json False --download-retry-count 100 --tmp-dir /www/wwwroot/xxxxxxx/bin/temp/data/ --thread-count 12 --del-after-done --live-pipe-mux --log-level OFF -sa all -sv best https://sam-py-edge02.tigo.com.py/VMX4_widevine/rolling-buffer/TigoSports3HDPY/TigoSports3HDPY/transmux/index.mpd -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" --key f62e93559765dfa6a89d2842b2b6d64a:9f6a8cf0bcb1d17ce79ea93d0d9c3d83
> 
> ![photo_2024-03-04_22-54-06](https://private-user-images.githubusercontent.com/10226983/309957602-04fe604c-2d45-4a52-97ba-07201a06c8e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNjUxMjEsIm5iZiI6MTcxMDM2NDgyMSwicGF0aCI6Ii8xMDIyNjk4My8zMDk5NTc2MDItMDRmZTYwNGMtMmQ0NS00YTUyLTk3YmEtMDcyMDFhMDZjOGUzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDIxMjAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NjJiOTZiN2Q4YjRiMDkzODhlZjNkYWFhZTJhMTViNWYyNGQyNDkzZjg3YzgwYTEwYzU1N2FiYTg4ZWJjYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xtgFl9usseAu7gXFroSNpCdsZqVADlfhbJuHo_1U08U)
Hello, do you have the tigosportplus keys?

**Comment by GioAtv** [comment]
Good afternoon,
I would like to contact you if it is feasible. Confirm me to leave you my contact number or leave me yours

**Comment by andremxmx** [comment]
> Good afternoon, I would like to contact you if it is feasible. Confirm me to leave you my contact number or leave me yours

@strix_Dev telegram

**Comment by americagameslm-jpg** [comment]
contacto
