### ISSUE TITLE
问2个问题

### ISSUE THREAD

**Issue by superen7527** [nilaoda/N_m3u8DL-RE#371]
抱歉不知道去哪里问 占用一下issue

1.看旧项目介绍，好像是自动合并视频？我用re版本设置链接和输出目录 结果下载以后没有看到视频文件，反而在临时目录里面看到一大堆ts，请问是新版 是需要用mux-after-done合并吗？我看介绍是合并音视频 而且是附加命令，感觉不像是合并ts。我是Linux用的带宽有点小下载了好久才下载完，本来我应该自己试一下这个附加命令，但是重新下载要好久，我就想问一下。

2.二进制合并那个选项只是针对合成ts而不是合成视频的吧？想问一下是通过ffmpeg合成ts还是raw直接二进制合成比较好？我有下载ffmpeg，但是如果raw二进制合成效率和成品效果质量比较好我可能想用raw 耗时久一点倒是无所谓。不过如果合成以后都是一样的md5那我觉得可能ffmpeg比较快一点，是这样理解吗？

**Comment by RikaCelery** [comment]
+ mux-after-done为旧版参数，新版会自动合并，对于直播你需要`--live-real-time-merge`
+ 视频下载合并和删除是自动的
+ ffmpeg可以合并，失败了会提示你，不清楚为什么你没有找到视频，请尝试指定输出目录后试试`--save-dir <save-dir>`
+ ffmpeg做的事情叫重新封装，而不是转吗，所以质量不会有损失，至于是否二进制比较玄学，你试试哪个效果好，我倾向于ffmpeg因为会自动修复时间轴
