### ISSUE TITLE
伪装png的ts好像还没处理

### ISSUE THREAD

**Issue by yf718** [nilaoda/N_m3u8DL-RE#38]
https://github.com/nilaoda/N_m3u8DL-CLI/issues/237

**Comment by yf718** [comment]
https://data.cache.m3u8.lscsfw.com:3395/cache/2022-09-29/4249/e518d62e23f712de846543851225b1ba.m3u8?st=DKC8rKvs8fEHbenjeoxjnA&e=1664454226

**Comment by nilaoda** [comment]
还没有处理
