### ISSUE TITLE
dmm的dcv原档可以破解了

### ISSUE THREAD

**Issue by ghost** [nilaoda/N_m3u8DL-RE#383]
![捕获](https://github.com/nilaoda/N_m3u8DL-RE/assets/139627402/36920607-43af-4c7c-bdd5-b57a3020516f)

之前用的hls流，一来下载慢，二来有些人说和dcv原档还是不同，所以索性研究了下dcv，成功了。
买dmm高级月额，直接在播放界面下dcv，下载速度很快，然后找出key用ffmpeg解码就行了。
比hls的m3u8好太多。

这个软件考虑添加吗？毕竟dcv也挺容易解决的。
不过相对于m3u8的真破解，dcv整个流程我觉得还是称作“伪造破解”更恰当。
但总归出来的都是原档，这就很香。

所以截至目前，dmm的m3u8和dcv都可以破解，完美还原出mp4原档随便播放。

**Comment by 592767809** [comment]
你说有没有一种可能nilaoda已经出过这样的工具，还有一个问题就是key怎么来的？

**Comment by YUIIUY** [comment]
4k的dcv稍微难一点点

**Comment by 592767809** [comment]
> 4k的dcv稍微难一点点

一样的，所有的类型都能解密

**Comment by YUIIUY** [comment]
多了几个kid，获取pssh要比单kid的麻烦点...解密也要用不同的key...
--
从Mail.ru的Android专用app所发送 星期五, 26 四月 2024, 08:55上午 +08:00 发件人 漁滒  ***@***.*** :

**Comment by bryanyeong97** [comment]
> 为了证明我说的是真的，给一个资源的key吧：
> 
> 坂井なるは SSIS-378 01c18623d16693e553f5fe7b8dbc1ed0
> 
> 有号可以买片的自己去试试，不确定是不是每个号的dcv加密都不同。 破解用ffmpeg，这是命令：
> 
> ffmpeg.exe -decryption_key 这里放那一串key字符 -i ./这里放影片的DCV文件.dcv -codec copy ./DeCode.mp4

请问你是怎么把16bytes的key文件转换成一串字符

**Comment by 592767809** [comment]
> > 为了证明我说的是真的，给一个资源的key吧：
> > 坂井なるは SSIS-378 01c18623d16693e553f5fe7b8dbc1ed0
> > 有号可以买片的自己去试试，不确定是不是每个号的dcv加密都不同。 破解用ffmpeg，这是命令：
> > ffmpeg.exe -decryption_key 这里放那一串key字符 -i ./这里放影片的DCV文件.dcv -codec copy ./DeCode.mp4
> 
> 请问你是怎么把16bytes的key文件转换成一串字符

二进制转十六进制就可以

**Comment by bryanyeong97** [comment]
> > > 为了证明我说的是真的，给一个资源的key吧：
> > > 坂井なるは SSIS-378 01c18623d16693e553f5fe7b8dbc1ed0
> > > 有号可以买片的自己去试试，不确定是不是每个号的dcv加密都不同。 破解用ffmpeg，这是命令：
> > > ffmpeg.exe -decryption_key 这里放那一串key字符 -i ./这里放影片的DCV文件.dcv -codec copy ./DeCode.mp4
> > 
> > 
> > 请问你是怎么把16bytes的key文件转换成一串字符
> 
> 二进制转十六进制就可以

有在线转换链接吗

**Comment by bryanyeong97** [comment]
> > > 为了证明我说的是真的，给一个资源的key吧：
> > > 坂井なるは SSIS-378 01c18623d16693e553f5fe7b8dbc1ed0
> > > 有号可以买片的自己去试试，不确定是不是每个号的dcv加密都不同。 破解用ffmpeg，这是命令：
> > > ffmpeg.exe -decryption_key 这里放那一串key字符 -i ./这里放影片的DCV文件.dcv -codec copy ./DeCode.mp4
> > 
> > 
> > 请问你是怎么把16bytes的key文件转换成一串字符
> 
> 二进制转十六进制就可以

大佬，请问可以加个电报联系交流吗

**Comment by YUIIUY** [comment]
你说的key文件属于clearkey,dcv的key是widevine的...
--
从Mail.ru的Android专用app所发送 星期六, 27 四月 2024, 07:02下午 +08:00 发件人 bryanyeong97  ***@***.*** :

**Comment by bryanyeong97** [comment]
> 你说的key文件属于clearkey,dcv的key是widevine的... -- 从Mail.ru的Android专用app所发送 星期六, 27 四月 2024, 07:02下午 +08:00 发件人 bryanyeong97 ***@***.*** :
> […](#)
> >为了证明我说的是真的，给一个资源的key吧： >坂井なるは SSIS-378 01c18623d16693e553f5fe7b8dbc1ed0 >有号可以买片的自己去试试，不确定是不是每个号的dcv加密都不同。 破解用ffmpeg，这是命令： >ffmpeg.exe -decryption_key 这里放那一串key字符 -i ./这里放影片的DCV文件.dcv -codec copy ./DeCode.mp4 请问你是怎么把16bytes的key文件转换成一串字符 — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you commented. Message ID: @ github . com>

你知道怎么弄吗，可以加个电报聊聊吗

**Comment by 9DA73860** [comment]
> 你可能弄错了，dcv破解整个过程不需要二进制。 https://tool.oschina.net/hexconvert 就算需要，随便搜搜就有很方便的工具可以用。 或者去问chatgpt，可以直接拿结果。

大佬 可以透露一個 dcv 是用那個license server 其他技術我都有 就差這個資料

**Comment by 9DA73860** [comment]
> 你可能弄错了，dcv破解整个过程不需要二进制。 https://tool.oschina.net/hexconvert 就算需要，随便搜搜就有很方便的工具可以用。 或者去问chatgpt，可以直接拿结果。

會了....最麻煩 是 生成一個pssh

**Comment by 9DA73860** [comment]
> 为了证明我说的是真的，给一个资源的key吧：
> 
> 坂井なるは SSIS-378 01c18623d16693e553f5fe7b8dbc1ed0
> 
> 有号可以买片的自己去试试，不确定是不是每个号的dcv加密都不同。 破解用ffmpeg，这是命令：
> 
> ffmpeg.exe -decryption_key 这里放那一串key字符 -i ./这里放影片的DCV文件.dcv -codec copy ./DeCode.mp4

你也可以驗證一下

snis00172hhb.dcv
f49e59a487b33b6fb8e210f1a929e9f0:9c2aa2848743e82bf79e2aab0229f249

**Comment by Chris0256** [comment]
老铁可以跟你要结月的dcv吗 有偿

**Comment by bryanyeong97** [comment]
目前dmm已更换所有的m3u8至mpd的clearkey加密，也属于widevine加密，全站基本都能破解，例如vr，4k，普通1080P等等，有需要可以联系我：t.me/bryan_yeong97

**Comment by bryanyeong97** [comment]
> > 目前dmm已更换所有的m3u8至mpd的clearkey加密，也属于widevine加密，全站基本都能破解，例如vr，4k，普通1080P等等，有需要可以联系我：t.me/bryan_yeong97
> 
> 兄弟，先搞清楚什么是ClearKey再来吧XD

我已经搞得很清楚了，我说的没错啊clearkey也属于widevine加密，破解出来也是KID:KEY，要搞清楚的是你吧

**Comment by bryanyeong97** [comment]
> > > > 目前dmm已更换所有的m3u8至mpd的clearkey加密，也属于widevine加密，全站基本都能破解，例如vr，4k，普通1080P等等，有需要可以联系我：t.me/bryan_yeong97
> > > 
> > > 
> > > 兄弟，先搞清楚什么是ClearKey再来吧XD
> > 
> > 
> > 我已经搞得很清楚了，我说的没错啊clearkey也属于widevine加密，破解出来也是KID:KEY，只不过4k的有4个KID和4个KEY罢了
> 
> [https://dashif.org/identifiers/content_protection/](url) 少说两句多学习比较不丢人~


> > > > 目前dmm已更换所有的m3u8至mpd的clearkey加密，也属于widevine加密，全站基本都能破解，例如vr，4k，普通1080P等等，有需要可以联系我：t.me/bryan_yeong97
> > > 
> > > 
> > > 兄弟，先搞清楚什么是ClearKey再来吧XD
> > 
> > 
> > 我已经搞得很清楚了，我说的没错啊clearkey也属于widevine加密，破解出来也是KID:KEY，只不过4k的有4个KID和4个KEY罢了
> 
> [https://dashif.org/identifiers/content_protection/](url) 少说两句多学习比较不丢人~

我的回复你不喜欢看可以不要看，回复什么淋，不要在这边瞎逼逼，我看你是欠屌

**Comment by bryanyeong97** [comment]
> dcv hls这些是不同格式吗

dcv解密出来和hls下的格式是一样的

**Comment by BBplux** [comment]
> > 为了证明我说的是真的，给一个资源的key吧：
> > 坂井なるは SSIS-378 01c18623d16693e553f5fe7b8dbc1ed0
> > 有号可以买片的自己去试试，不确定是不是每个号的dcv加密都不同。 破解用ffmpeg，这是命令：
> > ffmpeg.exe -decryption_key 这里放那一串key字符 -i ./这里放影片的DCV文件.dcv -codec copy ./DeCode.mp4
> 
> 你也可以驗證一下
> 
> snis00172hhb.dcv f49e59a487b33b6fb8e210f1a929e9f0:9c2aa2848743e82bf79e2aab0229f249

这key是怎么得来的

**Comment by zlyMaster** [comment]
![Image](https://github.com/user-attachments/assets/3d33a239-781f-4294-bf4f-63bcf6565cf0)
开了月度会员，在线播放视频如图提示有知道怎么解决的吗？

我用的梯子是自己用vps+v2ray搭建的，有几个日本ip都试过了，dmm.co.jp能访问，但是一在线播放视频就报这个错误。
tv.dmm.co.jp访问会显示地区不支持服务，但是我是日本的ip很奇怪，我尝试用vps直接访问也是一样的结果。

**Comment by zlyMaster** [comment]
![Image](https://github.com/user-attachments/assets/5214ffe5-2485-4353-9a0c-1b8ce4f6ce1a)
上面是开了google翻译的，原始是这张图的错误。

**Comment by NateChow** [comment]
> ![Image](https://github.com/user-attachments/assets/5214ffe5-2485-4353-9a0c-1b8ce4f6ce1a) 上面是开了google翻译的，原始是这张图的错误。

代理的问题，换其他的IP看看

**Comment by tsf0823** [comment]
> 多了几个kid，获取pssh要比单kid的麻烦点...解密也要用不同的key...
> --
> 从Mail.ru的Android专用app所发送 星期五, 26 四月 2024, 08:55上午 +08:00 发件人 漁滒  ***@***.*** :
> […](#)
> 
> >4k的dcv稍微难一点点
> 一样的，所有的类型都能解密
> —
> Reply to this email directly,  view it on GitHub , or  unsubscribe .
> You are receiving this because you commented. Message ID:  @ github . com>



> 你说的key文件属于clearkey,dcv的key是widevine的...
> --
> 从Mail.ru的Android专用app所发送 星期六, 27 四月 2024, 07:02下午 +08:00 发件人 bryanyeong97  ***@***.*** :
> […](#)

求教下，我拿到了四个key，需要用什么解密啊，shaka读取不了，mp4decrypt只能解密部分…

**Comment by tardysun** [comment]
> 有什么推荐的日本家宽VPS吗？

没用的，现在只要是用代理都不行的。以前倒是还可以

**Comment by chongloufeixue** [comment]
我在DMM购买了大量的影片,本来想拿去PT站造福大家的....可是不知道怎么转成 MP4

**Comment by alexanderfs** [comment]
我最近买了一个影片，结果我这个代理死活下不下来，有谁能帮我一下吗，非常感谢

**Comment by 9DA73860** [comment]
Telegram 加我試試吧 p2ekaboo
VR 我不會

> 我在DMM购买了大量的影片,本来想拿去PT站造福大家的....可是不知道怎么转成 MP4



> 我最近买了一个影片，结果我这个代理死活下不下来，有谁能帮我一下吗，非常感谢

**Comment by BBplux** [comment]
> 我在DMM购买了大量的影片,本来想拿去PT站造福大家的....可是不知道怎么转成 MP4

p站上有个软件能解，不过收费但是也不是很贵

**Comment by MapleRedbean** [comment]
非常有效的办法，已经解决了dcv的转换，十分感谢

**Comment by MapleRedbean** [comment]
> 我最近买了一个影片，结果我这个代理死活下不下来，有谁能帮我一下吗，非常感谢

用surfshark，有7天免费试用，我用这个搞定了

**Comment by tungtung0417** [comment]
有大哥能教教我如何獲得那個key嗎?

**Comment by ZhongHongLi** [comment]
> 有大哥能教教我如何獲得那個key嗎?
 那个key 视频打开 f12 播放的时候有一个接口就有

**Comment by tungtung0417** [comment]
> > 有大哥能教教我如何獲得那個key嗎?
> > 那个key 视频打开 f12 播放的时候有一个接口就有

4k的影片有四個key 那樣應該怎麼弄?
