### ISSUE TITLE
dmm的tv也可以破解啊

### ISSUE THREAD

**Issue by ghost** [nilaoda/N_m3u8DL-RE#384]
在旧的N_m3u8DL-CLI里看有些人问tv能不能破，刚试了下可以破。
![捕获](https://github.com/nilaoda/N_m3u8DL-RE/assets/139627402/37b11155-09c2-40a3-af81-efe2c54e8f70)

破的是柯南的第一集，就只是提取mpd，获取key，这个N_m3u8DL-RE就可以做。
是我out了还是？

反正……https://tv.dmm.com/vod的都可以破，谁需要自己去研究吧。

**Comment by YUIIUY** [comment]
一直都可以，旧版本的是和第三方合作的（应该是videomarket），也是widevine加密，现在dmm自己搞了
