### ISSUE TITLE
mp4decrypt not found!

### ISSUE THREAD

**Issue by baiduyys** [nilaoda/N_m3u8DL-RE#389]
新手，win64，缺少mp4decrypt，是否有人可以给我帮助

**Comment by CR1571** [comment]
do you have the mp4decrypt.exe file placed in the same folder with the tool?

**Comment by baiduyys** [comment]
> do you have the mp4decrypt.exe file placed in the same folder with the tool?

Yes, the problem has been resolved. Thank you
