### ISSUE TITLE
custom range 无法选择指定时间范围

### ISSUE THREAD

**Issue by hrpaven** [nilaoda/N_m3u8DL-RE#404]
![image](https://github.com/nilaoda/N_m3u8DL-RE/assets/31646294/19b81dae-af90-4449-8d85-b7a6747cdfb2)
使用custom-range会无法选择时间范围导致报错

**Comment by hrpaven** [comment]
使用分段范围的话，会报错sequence

**Comment by nilaoda** [comment]
新版还有这个问题吗

**Comment by hrpaven** [comment]
新版已解决这个问题
