### ISSUE TITLE
希望能够自动填写key和iv

### ISSUE THREAD

**Issue by erikaemma** [nilaoda/N_m3u8DL-RE#411]
最近下载的视频地址是“http://demo.com/a.m3u8?auto_key=123”，然后文件中有如下内容：

#EXT-X-KEY:METHOD=AES-128,URI="https://demo2.com/crypt.key?auth_key=123",IV=0x456

crypt.key下载后需要使用base64转码：
data:application/octet-stream;base64,abcdefg==

也就是说这个key（abcdefg==）和iv（0x456）都能够自动获得。而且这个网站非常变态，视频无论是否正在播放，这个key是随时变化的，有时候手工操作根本来不及

**Comment by wnpllrzodiac** [comment]
你自己做个nginx代理处理下，再给 N_m3u8DL-RE ?
感觉不是媒体侧标准行为

**Comment by nilaoda** [comment]
软件已经提供了[HLSKeyProcessor](https://github.com/nilaoda/N_m3u8DL-RE/blob/main/src/N_m3u8DL-RE.Parser/Processor/KeyProcessor.cs)来实现自定义KEY解析逻辑。

示例代码：
https://github.com/nilaoda/N_m3u8DL-RE/blob/6cc09fa373d1330cf1796349c68f7b1c0894641b/src/N_m3u8DL-RE/Processor/DemoProcessor2.cs#L16-L30

https://github.com/nilaoda/N_m3u8DL-RE/blob/6cc09fa373d1330cf1796349c68f7b1c0894641b/src/N_m3u8DL-RE/Program.cs#L187-L194

你可以自行修改源码来实现针对某网站的特殊行为。

---

目前尚未构想如何不修改源代码实现“插件”功能。欢迎讨论。
