### ISSUE TITLE
Video and Audio have Two different keys for decryption

### ISSUE THREAD

**Issue by furkyto** [nilaoda/N_m3u8DL-RE#421]
What command to use if the video and audio of the stream have two different keys to decryption?

**Comment by nilaoda** [comment]
You can pass multi KID-KEY pairs:
```
--key KID1:KEY1 --key KID2:KEY2
```

**Comment by furkyto** [comment]
But i want to mux with -M format=mp4  in one file after decryption the video and audio

**Comment by furkyto** [comment]
thank you , it is working :)

**Comment by captaindooley** [comment]
I'm seeing some videos with four pairs — do I need to specify which one goes with which stream or will the program determine this on it's own?
