### ISSUE TITLE
求助，这个直播源下载不了

### ISSUE THREAD

**Issue by yyxiaofeng** [nilaoda/N_m3u8DL-RE#43]
从这个直播网页[https://maxsport.one/stream453.php提取直播源https://webudi.openhd.lol/ddy1/premium453/tracks-v1a1/mono.m3u8到re里下载不了](https://maxsport.one/stream453.php%E6%8F%90%E5%8F%96%E7%9B%B4%E6%92%AD%E6%BA%90https://webudi.openhd.lol/ddy1/premium453/tracks-v1a1/mono.m3u8%E5%88%B0re%E9%87%8C%E4%B8%8B%E8%BD%BD%E4%B8%8D%E4%BA%86)

**Comment by yyxiaofeng** [comment]
从这个直播网页https://maxsport.one/stream453.php提取直播源https://webudi.openhd.lol/ddy1/premium453/tracks-v1a1/mono.m3u8到re里下载不了

**Comment by nilaoda** [comment]
```
N_m3u8DL-RE.exe -H "origin: https://streamservicehd.click" -H "referer: https://streamservicehd.click/premiumtv/sportkart.php?id=453" "https://webudi.openhd.lol/ddy1/premium453/index.m3u8"
```

**Comment by yyxiaofeng** [comment]
昨晚录制出现错误
[img]https://pic1.imgdb.cn/item/6348a0e316f2c2beb1169e56.png[/img]

**Comment by yyxiaofeng** [comment]
大概录制了1小时左右，就报错了

**Comment by nilaoda** [comment]
我抽空看下
