### ISSUE TITLE
ERROR: 分片数量校验不通过

### ISSUE THREAD

**Issue by thisisjin** [nilaoda/N_m3u8DL-RE#442]
通过猫抓获取的m3u8连接，调用m3u8dl-re进行下载。会在下载完成后不出现合并信息，直接消失。
查询日志发现是片段没有下载完全。
日志信息：
Exception  => Response status code does not indicate success: 503 (Service Temporarily Unavailable).
Url        => https://vip.kuaikan-cdn3.com/20230406/LvfFPIAX/hls/hOF1e8ke.ts
09:58:22.465 EXTRA: Ah oh!
RetryCount => 3
Exception  => Response status code does not indicate success: 503 (Service Temporarily Unavailable).
Url        => https://vip.kuaikan-cdn3.com/20230406/LvfFPIAX/hls/RwRV1lHx.ts
09:58:23.557 EXTRA: Ah oh!
RetryCount => 3
Exception  => Response status code does not indicate success: 503 (Service Temporarily Unavailable).
Url        => https://vip.kuaikan-cdn3.com/20230406/LvfFPIAX/hls/UutQjVor.ts
09:58:25.904 ERROR: 分片数量校验不通过, 共2037个,已下载2034.
09:58:25.906 ERROR: Failed

尝试多次也是同样结果，好奇出现的原因

**Comment by nilaoda** [comment]
看起来是服务器不稳定，可以尝试多次重试。如果依旧无法下载，可以关闭分片数量校验。

`--check-segments-count false`
