### ISSUE TITLE
下载的视频无法播放

### ISSUE THREAD

**Issue by HLB201803** [nilaoda/N_m3u8DL-RE#446]
大佬，下载下来的视频没办法播放是为什么啊

F:\Software\IDM>.\N_m3u8DL-RE "https://mv.aura-el.com/1b257b1fdc93406c8f8edeb510d75782/8338552a4b3f41b48c55456c2af503e7-9f835d8b42caa44d0d9e18f93920845e-sd-encrypt-stream.m3u8" --save-name _test
22:06:05.389 INFO : N_m3u8DL-RE (Beta version) 20240630
22:06:05.398 INFO : 加载URL: https://mv.aura-el.com/1b257b1fdc93406c8f8edeb510d75782/8338552a4b3f41b48c55456c2af503e7-9f835d8b42caa44d0d9e18f93920845e-sd-encrypt-stream.m3u8
22:06:06.461 INFO : 内容匹配: HTTP Live Streaming
22:06:06.461 INFO : 正在解析媒体信息...
22:06:07.174 WARN : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
retryCount: 3
22:06:09.500 WARN : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
retryCount: 2
22:06:11.787 WARN : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
retryCount: 1
22:06:14.226 WARN : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
retryCount: 0
22:06:15.230 ERROR: 获取KEY失败，忽略读取.: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
22:06:15.240 WARN : 写出meta json
22:06:15.262 INFO : 已解析, 共计 1 条媒体流, 基本流 1 条, 可选音频流 0 条, 可选字幕流 0 条
22:06:15.263 INFO : Vid *UNKNOWN Kbps | 30 Segments | ~04m53s
22:06:15.264 WARN : 检测到无法识别的加密方式，自动开启二进制合并
22:06:15.265 INFO : 已选择的流:
22:06:15.266 INFO : Vid *UNKNOWN Kbps | 30 Segments | ~04m53s
22:06:15.266 WARN : 写出meta json
22:06:15.267 INFO : 保存文件名: _test
22:06:15.269 INFO : 开始下载...Vid Kbps
22:06:17.487 WARN : 读取媒体信息...
22:06:17.567 INFO : [0x100]: Video, h264 ([27][0][0][0])
22:06:17.568 INFO : [0x101]: Audio, aac (SSR) ([15][0][0][0])
22:06:23.704 INFO : 二进制合并中...
22:06:23.774 INFO : Done

**Comment by TraderWagon** [comment]
写着加密的
