### ISSUE TITLE
The proxy tunnel request to proxy failed with status code '407' error :(

### ISSUE THREAD

**Issue by ArxSilentium** [nilaoda/N_m3u8DL-RE#449]
![screenshot_175](https://github.com/user-attachments/assets/dd47dfdf-7175-458c-bcb5-ff33995fc921)

I encounter this error when I want to download content from a website opened with a Lan proxy. What can I do to solve the problem?

I add this to the command line but it doesn't work, --use-system-proxy

**Comment by nilaoda** [comment]
check the proxy, maybe need authentication.

**Comment by nilaoda** [comment]
> @nilaoda
> 
> > check the proxy, maybe need authentication.
> 
> "Is there a way to use multiple proxies for downloading? The .m3u8 file has restricted access."

No, only one proxy accepted.
