### ISSUE TITLE
audio not in sync with video

### ISSUE THREAD

**Issue by fogers777** [nilaoda/N_m3u8DL-RE#45]
Hello,

first of all, thank you for great application and efforts to maintain it!

I have some issues with running mpd url of live stream and merging the audio with video. The audio is not in sync with video. 
```
./N_m3u8DL-RE-beta --save-name test "https://url/index.mpd" --mp4-real-time-decryption --live-real-time-merge --key 000000:000000000 --use-shaka-packager
ffmpeg -readrate 1 -i test.mp4 -i test.m4a -c:v copy -c:a copy test_merged.mp4
```

Also tried stopping the N_m3u8DL-RE and did merging without -readrate 1, like vod audio/video merge, but sound is still out of sync. Any suggestions what might be wrong?

Thank you!

**Comment by nilaoda** [comment]
Send me the mpd link

**Comment by nilaoda** [comment]
I tried it, the audio and video are synchronized, no problem found

**Comment by nilaoda** [comment]
try latest version
