### ISSUE TITLE
mux to mp4 Dosnt work 

### ISSUE THREAD

**Issue by xGhostOfSparta** [nilaoda/N_m3u8DL-RE#455]
there is any way to save live dash to mp4 file while its recording ? 

command i have used `RE "Manifest_link.mpd" --live-real-time-merge --live-pipe-mux -M format=mp4`

still getting .ts file

**Comment by nilaoda** [comment]
Actually, the `-M` option doesn't work when recording live streams. It only kicks in for VOD content.

**Comment by xGhostOfSparta** [comment]
> Actually, the `-M` option doesn't work when recording live streams. It only kicks in for VOD content.

When download is done I’m just running 

`ffmpeg -I video.ts -c copy output.mp4`

There is any way to do it when download the file or run it automatically when finish?

Thanks.
