### ISSUE TITLE
作者考虑更改下载逻辑吗？

### ISSUE THREAD

**Issue by sdfva121** [nilaoda/N_m3u8DL-RE#456]
目前的下载逻辑不是真正的多线程，下载某些网站的资源的时候，速度比浏览器还慢

**Comment by nilaoda** [comment]
M3U8大部分是多个切片的，程序并发下载他们是比较合理的行为，如果针对每个切片都去多线程下载会导致更大概率的分片损坏。

目前程序只对有且只有一个切片的情况会进行“真正的”多线程下载（http range）。

**Comment by sdfva121** [comment]
> M3U8大部分是多个切片的，程序并发下载他们是比较合理的行为，如果针对每个切片都去多线程下载会导致更大概率的分片损坏。
> 
> 目前程序只对有且只有一个切片的情况会进行“真正的”多线程下载（http range）。

不，我的意思是mpd，mpd只有一个http文件，但是没有达到多线程下载
