### ISSUE TITLE
下载mpd遇到音画不同步的问题

### ISSUE THREAD

**Issue by yyxiaofeng** [nilaoda/N_m3u8DL-RE#46]
在下载某个mpd直播流时，我的命令是  N_m3u8DL-RE.exe --save-name test1 --append-url-params --live-real-time-merge "https://dizf8i52j4sep.cloudfront.net/out/v1/148af6c03e6d48b0a725611fae5ed3a7/index.mpd"  
生成视频文件时长4分多钟，音频文件8分多钟，这样合并起来有可能导致音画不同步，请问怎么解决呢？
https://pic1.imgdb.cn/item/6350179816f2c2beb1fab18d.png

**Comment by nilaoda** [comment]
可以测试一下最新版是否有缓解这个问题
