### ISSUE TITLE
使用key下载加密视频后,视频依然无法观看

### ISSUE THREAD

**Issue by aeioudaa** [nilaoda/N_m3u8DL-RE#461]
N_m3u8DL-RE.exe "https://cfvod.kaltura.com/edash/p/513551/sp/51355100/serveFlavor/entryId/1_xypzjq1w/v/1/pv/1/ev/13/f lavorId/1_,ztkgrrtx,brp7xjup,13ot0ta6,bami08qw,33jc2k7l,szhozh7z,eppnbpra,i0515wfi,gownfywl,wzd8vou0,/forceproxy/true/name/a.mp4.urlset/manifest.mpd" --key 2efd6c3f7bc60beab83198b603150aff:ca48d3468a1c1ae8138aa14b74a9fb0c

这个是mpd加密的视频.原视频链接为https://www.freetv.com/shows/800-words/season/1/episode/2
key是正确的
使用该命令下载下来的视频无法观看,这是什么原因呢

**Comment by sdfva121** [comment]
使用shaka解密，--use-shaka-packager，https://github.com/shaka-project/shaka-packager/releases/download/v3.2.0/mpd_generator-win-x64.exe，下载完成后更名为shaka-packager与N_m3u8DL-RE.exe放在同一个文件夹使用

**Comment by aeioudaa** [comment]
> 使用shaka解密,--use-shaka-packager，下载完成后更名为shaka-packager.exe与N_m3u8DL-RE.exe放在同一个文件夹上使用 https://github.com/shaka-project/shaka-packager/releases/download/v3.2.0/packager-win-x64.exe

问题已解决,感谢大佬指点!!!!
