### ISSUE TITLE
为什么输出格式没办法是设成 ts，有什么方式最终输出合并好的 ts 格式呢？

### ISSUE THREAD

**Issue by 785386804** [nilaoda/N_m3u8DL-RE#462]
像这样子MP4就可以：
N_m3u8DL-RE "https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/6191645753001/625c5856-63ab-4f74-beaa-3dc26a780c22/10s/master.m3u8?fastly_token=NjcxMWMzNjdfN2MyZDA5OGYyNGExZmZhMGJiNTdiZjJlNmQ5MzUxMmIwYTJmNjM1NTQyNDYwNjA0M2I4NTg1Zjg2NzhhZWFmMA%3D%3D" --save-name "001" -M format=mp4

但ts格式就不行：
N_m3u8DL-RE "https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/6191645753001/625c5856-63ab-4f74-beaa-3dc26a780c22/10s/master.m3u8?fastly_token=NjcxMWMzNjdfN2MyZDA5OGYyNGExZmZhMGJiNTdiZjJlNmQ5MzUxMmIwYTJmNjM1NTQyNDYwNjA0M2I4NTg1Zjg2NzhhZWFmMA%3D%3D" --save-name "001" -M format=ts

目前只能不设置输出格式，下载好再用FFmpeg合并成 ts ，但比较麻烦，想知道如何用N_m3u8DL-RE直接下载合并成 ts 格式

**Comment by 785386804** [comment]
> 像这样子MP4就可以： N_m3u8DL-RE "https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/6191645753001/625c5856-63ab-4f74-beaa-3dc26a780c22/10s/master.m3u8?fastly_token=NjcxMWMzNjdfN2MyZDA5OGYyNGExZmZhMGJiNTdiZjJlNmQ5MzUxMmIwYTJmNjM1NTQyNDYwNjA0M2I4NTg1Zjg2NzhhZWFmMA%3D%3D" --save-name "001" -M format=mp4
> 
> 但ts格式就不行： N_m3u8DL-RE "https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/6191645753001/625c5856-63ab-4f74-beaa-3dc26a780c22/10s/master.m3u8?fastly_token=NjcxMWMzNjdfN2MyZDA5OGYyNGExZmZhMGJiNTdiZjJlNmQ5MzUxMmIwYTJmNjM1NTQyNDYwNjA0M2I4NTg1Zjg2NzhhZWFmMA%3D%3D" --save-name "001" -M format=ts
> 
> 目前只能不设置输出格式，下载好再用FFmpeg合并成 ts ，但比较麻烦，想知道如何用N_m3u8DL-RE直接下载合并成 ts 格式

**Comment by nilaoda** [comment]
后续加入对TS封装的支持。
