### ISSUE TITLE
一台电脑用过N_m3u8DL-CLI，如何切换至N_m3u8DL-RE？

### ISSUE THREAD

**Issue by yige38** [nilaoda/N_m3u8DL-RE#463]
我此前一直在用旧的N_m3u8DL-CLI，cmd 运行N_m3u8DL-CLI_v3.0.2.exe --registerUrlProtocol 注册协议。

现在我想转而使用N_m3u8DL-RE，应该怎么做？

**Comment by nilaoda** [comment]
目前还没有相关功能。

N_m3u8DL-CLI用户无法平滑切换至N_m3u8DL-RE，命令行是不兼容的。你可以尝试使用第三方工具来进行转换，例如：

https://rikacelery.github.io/N_m3u8DL-RE_Command_Generator/cli2re.html
