### ISSUE TITLE
图形化(GUI)版本

### ISSUE THREAD

**Issue by SAOJSM** [nilaoda/N_m3u8DL-RE#48]
<img width="254" alt="042442rfbebbcu6cgitegu" src="https://user-images.githubusercontent.com/46414240/197251492-1a7ad519-7cb8-4854-bc94-54f9f4ef3067.png">
在恩山上看到您出了GUI版本，能不能早日更新在github上，顺便放个赞助码，可以支持下您的repo

**Comment by nilaoda** [comment]
这个只是临时的程序 没有什么价值……不会放在这里

赞助的话，可以 [img](https://nilaoda.github.io/N_m3u8DL-CLI/source/images/alipay.png)
