### ISSUE TITLE
请教TS合并问题

### ISSUE THREAD

**Issue by shiyan1012** [nilaoda/N_m3u8DL-RE#480]
请问在程序中ts分片是如何合并成MP4文件的，我尝试使用ffmpeg -y -hide_banner -f concat -safe 0 -i filelist.txt 去合并，结果最小帧率很奇怪，直接使用本程序下载自动合并的则为恒定帧率。能否告知，谢谢

**Comment by nilaoda** [comment]
```
ffmpeg -i concat:"01.ts|02.ts|03.ts" -c copy ...
```

https://github.com/nilaoda/N_m3u8DL-RE/blob/7d8e7c6402498485df4fb16ec195f3defb8a9b78/src/N_m3u8DL-RE/Util/MergeUtil.cs#L104
