### ISSUE TITLE
下载的视频无法正常解密合并

### ISSUE THREAD

**Issue by yuzukiss** [nilaoda/N_m3u8DL-RE#495]
![20241120222959](https://github.com/user-attachments/assets/938ef6a1-153f-4f90-b182-c23f1cadf558)
情况如图
看下载过程是正常解密的，但实际下载的视频无法播放。也试过不混流，下载下来的视频和音频也是未解密的版本。请问是哪里出问题了呢（本人虽然这个软件用了很多年但依旧是小白，视频解密方面基本是白纸，希望大家不吝赐教。非常感谢。）

**Comment by nilaoda** [comment]
你需要知道视频的KEY并使用`--key`传给下载器，下载器才能进行解密
