### ISSUE TITLE
mux some audio using mkvmerge get failed

### ISSUE THREAD

**Issue by khanh666** [nilaoda/N_m3u8DL-RE#497]
C:\TOOLS> RE --save-dir E:\Fille --save-name 008 -M format=mkv:muxer=mkvmerge --sub-format SRT -mt "https://playlist-vip.vieon.vn/playlist/content/vieon/cb711e8c-a8bf-4979-b8b7-f24f6e89d263/1732296944000/db6640e9dc03f4b5989dd0ba55837ca6/h264/playlist.m3u8?is_global=0&model=&pkgs=180&platform=web&play_trial=0&uid=22b51803-9060-d60b-2a02-c4f209a58f26&user_type=1&sn=sgn-fpt-002&rid=8"
00:57:20.892 INFO : N_m3u8DL-RE (Beta version) 20230628
00:57:20.904 INFO : Loading URL: https://playlist-vip.vieon.vn/playlist/content/vieon/cb711e8c-a8bf-4979-b8b7-f24f6e89d263/1732296944000/db6640e9dc03f4b5989dd0ba55837ca6/h264/playlist.m3u8?is_global=0&model=&pkgs=180&platform=web&play_trial=0&uid=22b51803-9060-d60b-2a02-c4f209a58f26&user_type=1&sn=sgn-fpt-002&rid=8
00:57:21.019 INFO : Content Matched: HTTP Live Streaming
00:57:21.020 INFO : Parsing streams...
00:57:21.022 WARN : Master List detected, try parse all streams
00:57:21.049 WARN : Writing meta json
00:57:21.052 INFO : Extracted, there are 7 streams, with 4 basic streams, 2 audio streams, 1 subtitle streams
00:57:21.054 INFO : Vid 1920x1080 | 4158 Kbps | 25 | avc1.640028
00:57:21.055 INFO : Vid 1280x720 | 1762 Kbps | 25 | avc1.64001F
00:57:21.057 INFO : Vid 854x480 | 980 Kbps | 25 | avc1.4D401E
00:57:21.067 INFO : Vid 640x360 | 594 Kbps | 25 | avc1.4D401E
00:57:21.073 INFO : Aud audio/mp4a | Ti?ng G?c | tg
00:57:21.076 INFO : Aud audio/mp4a | Thuy?t Minh | tm
00:57:21.077 INFO : Sub subs | vi | Ti?ng Vi?t
00:57:21.081 INFO : New version detected! v0.2.1-beta
00:57:31.116 INFO : Parsing streams...
00:57:31.485 INFO : Selected streams:
00:57:31.487 INFO : Vid 640x360 | 594 Kbps | 25 | avc1.4D401E | 335 Segments | ~22m16s
00:57:31.488 INFO : Aud audio/mp4a | Thuy?t Minh | tm | 335 Segments | ~22m16s
00:57:31.499 INFO : Sub subs | vi | Ti?ng Vi?t | 1 Segment | ~00m30s
00:57:31.500 WARN : Writing meta json
00:57:31.506 INFO : Save Name: 008
00:57:31.507 WARN : MuxAfterDone is detected, binary merging is automatically enabled
00:57:31.510 INFO : Start downloading...Vid 640x360 | 594 Kbps | 25 | avc1.4D401E
00:57:31.511 INFO : Start downloading...Aud audio/mp4a | Thuy?t Minh | tm
00:57:31.554 WARN : Reading media info...
00:57:31.570 WARN : Reading media info...
00:57:31.605 INFO : [0x1]: Video, h264 (avc1), 640x360
00:57:31.606 INFO : [0x1]: Audio, aac (mp4a), 191 kb/s
00:57:31.642 INFO : Start downloading...Sub subs | vi | Ti?ng Vi?t
00:57:31.783 WARN : Reading media info...
00:57:31.846 INFO : NaN: Subtitle, webvtt
00:57:31.848 WARN : Extracting VTT(raw) subtitle...
00:57:31.851 INFO : Binary merging...
00:57:35.597 INFO : Binary merging...
00:57:35.597 INFO : Binary merging...
00:57:37.224 WARN : 008.mp4
00:57:37.224 WARN : 008.tm.m4a
00:57:37.225 WARN : 008.vi.srt
00:57:37.225 WARN : Muxing to 008.MUX.mkv
00:57:37.285 ERROR: Mux failed
00:57:37.286 ERROR: Failed

**Comment by nilaoda** [comment]
Use the `--log-level DEBUG` to check the command line of `mkvmerge`, then execute it manually to see the specific error.

**Comment by khanh666** [comment]
> Use the `--log-level DEBUG` to check the command line of `mkvmerge`, then execute it manually to see the specific error.

'tm' is not a valid IETF BCP 47/RFC 5646 language tag in '--language 0:tm'. Additional information from the parser: The value 'tm' is not a valid ISO 639 language code.
can i disable language tag in mkvmerge

**Comment by khanh666** [comment]
> Try latest build: https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/11995415607

can you give me a guild to use this i very noob in this

**Comment by nilaoda** [comment]
> > Try latest build: https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/11995415607
> 
> can you give me a guild to use this i very noob in this

go to Artifacts, then download

**Comment by khanh666** [comment]
> > > Try latest build: https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/11995415607
> > 
> > 
> > can you give me a guild to use this i very noob in this
> 
> go to Artifacts, then download

damn thank u so much

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-RE/pull/508
