### ISSUE TITLE
ts视频过多导致合并失败

### ISSUE THREAD

**Issue by colafun** [nilaoda/N_m3u8DL-RE#50]
视频地址：https://vod.hoy.tv/BW05270HA/HOYTVHLS/BW05270HA.m3u8，切片数：1344，合并时提示“Too many open files”，合并失败。

**Comment by nilaoda** [comment]
什么系统？在Windows下是每1800个分片切割

**Comment by ethan-202285** [comment]
这个是系统打开文件数限制，不是程序问题.修改系统限制即可
ulimit -S -n 40960

**Comment by colafun** [comment]
> 

ubuntu

**Comment by nilaoda** [comment]
好的
