### ISSUE TITLE
设置--del-after-done false时，音视频分离的m3u8，视频和音频轨的m3u8还是被删除了

### ISSUE THREAD

**Issue by dfvips** [nilaoda/N_m3u8DL-RE#500]
![image](https://github.com/user-attachments/assets/a09095a6-cacf-493c-b171-52a416ecd8f5)
![image](https://github.com/user-attachments/assets/ee77f492-ff34-4a4f-ae4b-861136dbe4fa)
![image](https://github.com/user-attachments/assets/fb963bc0-ff10-44f6-91d5-71f4b255abe8)
![image](https://github.com/user-attachments/assets/0a49606b-c099-4a3a-8971-e384ea8256fc)
![image](https://github.com/user-attachments/assets/79f4c2bc-565a-4938-9343-18a716e66e9f)

**Comment by dfvips** [comment]
> ![image](https://private-user-images.githubusercontent.com/21048630/389183937-a09095a6-cacf-493c-b171-52a416ecd8f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTA1MDAsIm5iZiI6MTczMjM1MDIwMCwicGF0aCI6Ii8yMTA0ODYzMC8zODkxODM5MzctYTA5MDk1YTYtY2FjZi00OTNjLWIxNzEtNTJhNDE2ZWNkOGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA4MjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODE4NTFmZjZkYmRiYTI3ODg2MGVlMDI3ZTJkM2ViN2EwNWI2Yjg3N2Q0YjBmZGI5MmExZGI1ODdhNTBhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o0mxE5HqmmFQbt735In50W_6517XiZmi2F686QL5MRk) ![image](https://private-user-images.githubusercontent.com/21048630/389183833-ee77f492-ff34-4a4f-ae4b-861136dbe4fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTA1MDAsIm5iZiI6MTczMjM1MDIwMCwicGF0aCI6Ii8yMTA0ODYzMC8zODkxODM4MzMtZWU3N2Y0OTItZmYzNC00YTRmLWFlNGItODYxMTM2ZGJlNGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA4MjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMTgxNmFjZWIyNjI4MDI5MGQ0NmI5YTY4M2FlYzgyY2QwZDg0MDA1OTk0NTQzMTQ2MGFhNzljMjk4MmU4OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VYiJIeoi6dn5VSl0q3jZo8gt0BLpe1bPZ_1jwxXxeqs) ![image](https://private-user-images.githubusercontent.com/21048630/389183839-fb963bc0-ff10-44f6-91d5-71f4b255abe8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTA1MDAsIm5iZiI6MTczMjM1MDIwMCwicGF0aCI6Ii8yMTA0ODYzMC8zODkxODM4MzktZmI5NjNiYzAtZmYxMC00NGY2LTkxZDUtNzFmNGIyNTVhYmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA4MjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzY2Q0NGRiZTNiNjg5MDUxZjFhNjdmNTk4ZjA1OGM0MmY4ZDM5OGUxZWVlZDQ2NDcyNmE0MWUwYzcxMjg5ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FahJ4xCQPFa3EMfIWLgg6jv4616Iyt3F8jTWgObJ6Ys) ![image](https://private-user-images.githubusercontent.com/21048630/389183904-0a49606b-c099-4a3a-8971-e384ea8256fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTA1MDAsIm5iZiI6MTczMjM1MDIwMCwicGF0aCI6Ii8yMTA0ODYzMC8zODkxODM5MDQtMGE0OTYwNmItYzA5OS00YTNhLTg5NzEtZTM4NGVhODI1NmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA4MjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNjRjMzMyOTZmNjY2ZDU1YWE0MzI0MGExMzdjMWRlYmM0OWFkN2Y4MTM3YjIzMzcxYzVkMjMxZTgwNTM2YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MFiZxWRzLsE6Ivgn7fBKurGEgR70moch1p80DZmIle4) ![image](https://private-user-images.githubusercontent.com/21048630/389183878-79f4c2bc-565a-4938-9343-18a716e66e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTA1MDAsIm5iZiI6MTczMjM1MDIwMCwicGF0aCI6Ii8yMTA0ODYzMC8zODkxODM4NzgtNzlmNGMyYmMtNTY1YS00OTM4LTkzNDMtMThhNzE2ZTY2ZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA4MjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNWRkMTUxOTc3YWU4M2M0ZGU2NzY1ODdlNDQzMTQxMWMwM2I5YWYzYzI5YTVmNmVkODA2YjY5Y2ViN2NkOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tIwyaAHJb7mhGEZCAlGlMrrjImVQRQ-PXhYU94NNcWc) 而且多Map的m3u8无法正常完整下载 [https://github.com/nilaoda/N_m3u8DL-RE/issues/433](url)

**Comment by nilaoda** [comment]
增加`--allow-hls-multi-ext-map`

临时允许识别多个#EXT-X-MAP标签，但软件可能无法正常处理多init的情况，仅实验性功能。
