### ISSUE TITLE
在openwrt上运行

### ISSUE THREAD

**Issue by zhengqwe** [nilaoda/N_m3u8DL-RE#512]
如题，目前软件还无法在openwrt上运行，提示not found，能否实现软件在openwrt上运行？这样一来下载就不用开电脑了，直接用计划任务和软件的--live-record-limit参数就能实现定时开始和停止下载了
架构ARM64
![image](https://github.com/user-attachments/assets/b33f4700-90f1-4c5a-9735-fd61f607bf1f)

**Comment by nilaoda** [comment]
`ldd /tmp/N_m3u8DL-RE`看看缺啥东西

**Comment by nilaoda** [comment]
@zhengqwe 到[这里](https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/12056276070#artifacts)翻到页面底部下载`linux-musl-arm64`版本测试下能不能运行

**Comment by nilaoda** [comment]
@zhengqwe 可使用nohup
