### ISSUE TITLE
FFmpeg nonfree as replacement for mp4decrypt

### ISSUE THREAD

**Issue by trimechee** [nilaoda/N_m3u8DL-RE#521]
Hi, i see that our beloved N_m3u8DL-RE migrates from mp4decrypt to ffmpeg to fix bug related with Chinese characters.....while maintaining the support of mp4decrypt  with the command --use-mp4decrypt 💯 🥇 

so i found a "nonfree" ffmpeg that seems to overcome some of the limitations of the official classic ffmpeg.....maybe be it can help the project :

Automated nonfree builds of FFmpeg for Windows using GitHub Actions:

https://github.com/AnimMouse/ffmpeg-autobuild
https://www.animmouse.com/projects/ffmpeg-autobuild/

other builds of FFmpeg built by others :

https://www.animmouse.com/p/ffmpeg-binaries/

**Comment by nilaoda** [comment]
I have reverted to using mp4decrypt as the default decryption tool.

**Comment by trimechee** [comment]
and just to inform, i saw users say hldl fix some bugs present in ffmpeg .... may be it will be good idea to integrate hlsdl in  N_m3u8DL-RE : 

https://github.com/selsta/hlsdl
