### ISSUE TITLE
Latest version broke decryption

### ISSUE THREAD

**Issue by knowpwr** [nilaoda/N_m3u8DL-RE#529]
@nilaoda  The latest version just released broke decryption. I think that is caused by the fix to remedy mp4decrypt not being able to handle chinese characters. Keep in mind that files/folders with asciii only names are also affected.

**Comment by GeoHopper** [comment]
"the default decryption program in this software has been switched to ffmpeg"

This don't work for me (no chinese) - needed special ffmpeg release?

I've multiple batch files for different providers
and should now add in all --use-mp4decrypt ?
(of course shaka-packager works too)

Or is there a way (default config) to set this option?

**Comment by nilaoda** [comment]
@knowpwr Now, regardless of whether special characters are included, the same logic is applied. Could this cause any other issues?

**Comment by nilaoda** [comment]
@GeoHopper the default decryption program still mp4decrypt

**Comment by nilaoda** [comment]
Fixed in v0.2.3, thx for response
