### ISSUE TITLE
 Invalid URI: The Uri string is too long

### ISSUE THREAD

**Issue by yyc9392** [nilaoda/N_m3u8DL-RE#54]
使用的版本是0.0.7

在录制直播时，录制一段时间后出现报错如下提示并重试了几次.

 Invalid URI: The Uri string is too long. retryCount: 1

![image](https://user-images.githubusercontent.com/30689352/198981393-46e150e3-cda3-48b8-b6be-10dc887b19ce.png)

**Comment by nilaoda** [comment]
请发给我直播链接

**Comment by yyc9392** [comment]
之后会有回放，届时通过邮箱联系您
