### ISSUE TITLE
Alternate (audio description) tab name?

### ISSUE THREAD

**Issue by sk8ordi3** [nilaoda/N_m3u8DL-RE#548]
what is the tab name for the Alternate (audio description)?

wanna to use with regex to drop out every Alternate audio track

```
INFO : Aud *CENC a12 | 642 Kbps | ec-3 | en-US | 6CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a13 | 258 Kbps | ec-3 | en-US | 6CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a15 | 258 Kbps | ec-3 | en-US | 6CH | 1 Segment | Alternate | ~01h03m25s
INFO : Aud *CENC a6 | 258 Kbps | ec-3 | es-ES | 6CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a34 | 258 Kbps | ec-3 | fr-FR | 6CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a2 | 130 Kbps | ec-3 | cs | 2CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a3 | 130 Kbps | ec-3 | cs | 2CH | 1 Segment | Alternate | ~01h03m25s
INFO : Aud *CENC a24 | 130 Kbps | ec-3 | es-419 | 2CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a19 | 130 Kbps | ec-3 | hu | 2CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a22 | 130 Kbps | ec-3 | hu | 2CH | 1 Segment | Alternate | ~01h03m25s
INFO : Aud *CENC a17 | 130 Kbps | ec-3 | lvs | 2CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a32 | 130 Kbps | ec-3 | pl | 2CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a29 | 130 Kbps | ec-3 | pl | 2CH | 1 Segment | Alternate | ~01h03m25s
INFO : Aud *CENC a11 | 130 Kbps | ec-3 | pt-BR | 2CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a8 | 130 Kbps | ec-3 | ru | 2CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a26 | 130 Kbps | ec-3 | sk | 2CH | 1 Segment | ~01h03m25s
INFO : Aud *CENC a27 | 130 Kbps | ec-3 | th | 2CH | 1 Segment | ~01h03m25s
```

**Comment by nilaoda** [comment]
`role=Alternate`

**Comment by sk8ordi3** [comment]
> `role=Alternate`

this only gives me Alternate
I don't need Alternate audio tracks

**Comment by nilaoda** [comment]
@sk8ordi3 `-da role=Alternate `

**Comment by sk8ordi3** [comment]
@nilaoda nilaoda

i using this version:
N_m3u8DL-RE (Beta version) 20241203

i know that, and i see this in the --morehelp:
```
--morehelp select-audio
```

`-sa role="main":for=best`

so i try this too:
`-da role=Alternate`

but it didn't work

i explain to you what i want to achive and maybe you know what command i need to use

want to select it with command the best audio what is for:  (first audio) : cs | (second audio): en_US or en_GB  
(if maybe the en_US is not availble, than en_GB picked)
and nothing from Alternate audio
than i think this is the command for that:
`-da role="Alternate" -sa "lang=cs|en_US|en_GB:for=best2"`

maybe i messed up something with the command, but can you try it?
you can reach the mpd from this link:
https://p.darklab.sh/?0de05e82bd00225e#EqQjNBFD4Uu1gAKRrdoUwWFvxQ2i6P5h6mkbUdR5fRvC
