### ISSUE TITLE
v0.3.0-beta 20241203 自动解密合并失败

### ISSUE THREAD

**Issue by LidoCKT** [nilaoda/N_m3u8DL-RE#550]
当强制以点播方式下载直播流时，无法输出可播放内容。

> N_m3u8DL-RE "https://bcovlive-a.akamaihd.net/17789746e9e8477dbcdf8ceb96926d3b/ap-northeast-1/6160987587001/profile_0/chunklist_wv.m3u8" --key 98fe2cc47352f0170a03d2eeb41d0488:9b35588ce16dc0894af4fdd5a01abcb5 --custom-range 0:00:00-0:00:50 --mp4-real-time-decryption --live-perform-as-vod -M format=mp4 --save-name test
> 04:03:15.112 INFO : N_m3u8DL-RE (Beta version) 20241203
> 04:03:15.141 INFO : 加载URL: https://bcovlive-a.akamaihd.net/17789746e9e8477dbcdf8ceb96926d3b/ap-northeast-1/6160987587001/profile_0/chunklist_wv.m3u8
> 04:03:15.654 INFO : 内容匹配: HTTP Live Streaming
> 04:03:15.657 INFO : 正在解析媒体信息...
> 04:03:15.662 WARN : 写出meta json
> 04:03:15.666 INFO : 已解析, 共计 1 条媒体流, 基本流 1 条, 可选音频流 0 条, 可选字幕流 0 条
> 04:03:15.667 INFO : Vid *SAMPLE_AES_CTR Kbps | 3 Segments | ~00m18s
> 04:03:15.668 INFO : 用户自定义下载范围：0:00:00-0:00:50
> 04:03:15.670 WARN : 请注意，自定义下载范围有时会导致音画不同步
> 04:03:15.673 INFO : 已选择的流:
> 04:03:15.675 INFO : Vid *SAMPLE_AES_CTR Kbps | 3 Segments | ~00m18s
> 04:03:15.676 WARN : 写出meta json
> 04:03:15.679 INFO : 保存文件名: test
> 04:03:15.680 WARN : 你已开启下载完成后混流，自动开启二进制合并
> 04:03:15.681 WARN : 启用实时解密时，建议用shaka-packager而非mp4decrypt/ffmpeg
> 04:03:15.684 INFO : 开始下载...Vid Kbps
> 04:03:15.863 WARN : Type: cenc
> 04:03:15.866 WARN : PSSH(WV):
> CAESEJj+LMRzUvAXCgPS7rQdBIgaCGNhc3RsYWJzIlxleUpoYzNObGRFbGtJam9pTVRjM09EazNORFpsT1dVNE5EYzNaR0pqWkdZNFkyVmlPVFk1TWpaa00y
> SWlMQ0oyWVhKcFlXNTBTV1FpT2lKa1pXWmhkV3gwSW4wPTIHZGVmYXVsdA==
> 04:03:15.868 WARN : KID: 98fe2cc47352f0170a03d2eeb41d0488
> 04:03:15.870 WARN : 读取媒体信息...
> 04:03:15.968 INFO : [0x2]: Audio, aac (mp4a), 189 kb/s
> 04:03:15.970 INFO : [0x1]: Video, h264 (avc1), 1920x1080
> 04:03:16.774 INFO : 二进制合并中...
> 04:03:16.782 ERROR: Could not find file 'D:\test\0____\_init.mp4'.

疑似未留存 init.mp4 导致合并时找不到。
v0.2.1-beta 20240630 中无此问题。

**Comment by nilaoda** [comment]
![image](https://github.com/user-attachments/assets/427e544d-012e-4bbc-af66-41044b4a2663)

该m3u8的`#EXT-X-MAP`标签之前并未出现`#EXT-X-KEY`，所以认为init是没有加密的，由于[这个改动](https://github.com/nilaoda/N_m3u8DL-RE/commit/8095c6e1723f4bdb8572fb49fb5470f932a665b1)导致没有进入解密流程。你可以手动设置一下加密方式让程序进入解密逻辑：
```
--custom-hls-method UNKNOWN
```

这种情况下合法的m3u8长这个样子：
![image](https://github.com/user-attachments/assets/8f8361a6-85df-4b81-8a9a-606a0fb39bc8)

**Comment by nilaoda** [comment]
已经做了兼容处理. 可取用最新的[Actions](https://github.com/nilaoda/N_m3u8DL-RE/actions/workflows/build_latest.yml)版本进行测试

**Comment by LidoCKT** [comment]
> 04:03:15.681 WARN : 启用实时解密时，建议用shaka-packager而非mp4decrypt/ffmpeg

顺带一提 该网站如果按推荐使用shaka-packager的话只能输出几百K的文件
如果用mp4decrypt和ffmpeg都无问题
