### ISSUE TITLE
带EXT-X-MAP标签，请求头问题

### ISSUE THREAD

**Issue by SueSongHao** [nilaoda/N_m3u8DL-RE#551]
播放页面
https://www.hkanime.com.hk/animal/780x1x2

M3U8地址
https://cdn.hkanimal.com/ok/%E5%8A%87%E5%A0%B4%E7%89%88/EVANGELION/,lang/yue/Q.srt,Q.mp4,.urlset/index-f2-v1.m3u8

M3U8文件标签
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-MAP:URI="init-f2-v1.mp4"
#EXTINF:10.427,
seg-1-f2-v1.m4s
#EXTINF:10.427,
seg-4-f2-v1.m4s
(剩下的省略)

我一开始尝试用N_m3u8DL-RE去下载
**N_m3u8DL-RE.exe "https://cdn.hkanimal.com/ok/%E5%8A%87%E5%A0%B4%E7%89%88/EVANGELION/,lang/yue/Q.srt,Q.mp4,.urlset/index-f2-v1.m3u8"**
显示“WARN : Response status code does not indicates success: 403 (Forbidden).”

后来我添加了请求头
**-H "Referer: https://www.hkanime.com.hk/animal/780x1x2"**

**-H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"**

**-H "Cookie: __dtsu=6D0017322035833E183945BB3761FF84; PHPSESSID=kf32259daiiun34shpfu6i0avi; __cf_bm=myQw6B4aXT3KlDDX9TBLySU.zrMA6.P2jIzp7ZLBPwI-1733506279-1.0.1.1-QjC58gRFvKlQx46itzr2xIZHqe_KkjyILnEBWz2RGlQAgGf3i6UlotHfhrJbYda9HFe6LRGnYjUvuYWudGIB_Q; cf_clearance=RexXpQUsD4hNoJ6zIwcb_ZQGJl5wJkz2upNwEreX4qA-1733506279-1.2.1.1-gwp9M4Ov4ItfJfIAoPUWN8mrvWIQLP6njSPmmbFccSGI6slzaRRR6lRBLLI_VZmzU1L41wpGQWbVw5rukzhBVi5HF_m4xrLxZLcN63BxFtCVRmCMJ9.6AgpQmlmS2paAd5t2zqRTbkmGjLufkPSsdoyVblKiiZ61YGS0QqeDH8gLg_ATv1VCejAxQRXJ5237Mj57T3T5SdtWDJPV4hCai0zwk2W5F4v9E.bQbepv6MPiCz4xrRabdWdYLnKIQcUooFenKE9Xi7qn86h9CEvBdOZLgwP0v_WCdYe3W8JIMfeMUdRNafD5oPDo3lxamRKapSP0n0raXFN_3EUyKtf2d75RdTRnrCGfhzyIG1vgeNBySIqy2qXCtZ0GbnY0xfsgjp._l97XvqpHaXEJTukceQ; __gads=ID=5cc2fb05f1159392:T=1718039478:RT=1733506599:S=ALNI_MZXQtTlArS9wI4DrvjgxV58y4fd9w; __gpi=UID=00000e45ee6c1cd5:T=1718039478:RT=1733506599:S=ALNI_MbB1A6R07AXrlGNHhuN0YIDKT2oAQ; __eoi=ID=f6867fb05f07a05b:T=1718039478:RT=1733506599:S=AA-AfjbeuRQqvPO5j98w_PhPn9_n; FCNEC=%5B%5B%22AKsRol8LBmC4qv2jH6cUQz11gvYqyMb95YMzclGdAyVc80GhPZdxSYUX5CarvltnM8Ge8ECqs_Wa1wStjJFoRLQ1K7SPKyQTQeeCjJ2zllVVNUndfrMLGPmNf4swwsmaHuwxYuHkmU8d5adWJvNy1iYndQ_xvqmjFA%3D%3D%22%5D%2Cnull%2C%5B%5B2%2C%22%5B%5B%5B%5B1%2Cnull%2C%5B1733590605%2C877017000%5D%2C10%5D%5D%5D%2C%5Bnull%2C78%2C%5B1732807290%2C948478000%5D%5D%5D%22%5D%5D%5D; _cc_id=ca3b5e8c41b182fd4ae019078bde351; panoramaId_expiry=1734111669802; panoramaId=ea25fdf61327f2674c7df7cbe498185ca02c7f99d30fbe82bc3e1f8fd68dd3d7; panoramaIdType=panoDevice"**

Cookie我是这里拿的，提问的时候换了电脑，所以跟上面的Cookie不一样
![微信图片_20241207143840](https://github.com/user-attachments/assets/ddab3215-ccfe-4a57-b815-1cd8250a6746)

最终结果还是显示“WARN : Response status code does not indicates success: 403 (Forbidden).”

恳请各位大佬指点下迷津。

**Comment by hkanime** [comment]
求下大佬放過我哋!!我哋係小眾網站!!我哋經營困難

**Comment by SueSongHao** [comment]
> 求下大佬放过我哋！！我哋系小众网站！！我哋经营困难

唔会白罗资源，比个联系方式，我给你送资源
