### ISSUE TITLE
功能建议（支持文件蜈蚣的浏览器拓展）

### ISSUE THREAD

**Issue by yudong2ao** [nilaoda/N_m3u8DL-RE#556]
当前N-m3u8-re的文件下载能力已经很出色了，只是缺乏浏览器端的可视化媒体嗅探扩展，文件蜈蚣是另一款国人开发的综合下载工具，其自带的浏览器扩展具有非常强的网页视频嗅探能力而且页面风格设计也比较美观简洁，现在文件蜈蚣浏览器扩展嗅探到的音视频地址只能通过文件蜈蚣软件本体下载，文件蜈蚣的作者大大说技术上可以支持把文件蜈蚣扩展嗅探到的网页音视频地址传递给N-m3u8-re来下载，但是希望到时候N-m3u8-re可以在主页推荐文件蜈蚣的浏览器拓展（或者可以和文件蜈蚣作者一起合作完成N-m3u8-re和文件蜈蚣浏览器扩展的互相调用支持），让更多人知道文件蜈蚣拓展结合N-m3u8-re可以达到很好的使用效果，也算是对N-m3u8-re的能力补齐。

**Comment by he852100** [comment]
猫抓

**Comment by nilaoda** [comment]
需要url schema支持，后续补全
