### ISSUE TITLE
Mr Adeii has just compiled for me the latest version of N_m3u8DL-RE for my windows 7 os 32 bits, should we install .NET 9 to download videos please?

### ISSUE THREAD

**Issue by trimechee** [nilaoda/N_m3u8DL-RE#559]
Hello, we know great Mr Niloada has generously added the support of windows 7 but I could not find the executable version .exe for my windows 7, so I asked great Mr Adeii to compile for me the latest version of N_m3u8DL-RE for my windows 7 os 32 bits and Mr @adeii has generously achieved this exceptional feat !!

This is what Mr Adeii told me: "

New version need .NET 9 for compiling. I don't know does it is needed for work/downloading.

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-9.0.101-windows-x86-binaries

https://github.com/adeii/Qt6Win7/releases/download/Tests/N_m3u8DL-RE-dec24.7z v.0.3.0.0 "

https://github.com/adeii/Qt6Win7/issues/5#issuecomment-2543312793

So Mr @nilaoda please, should we install .NET 9 on windows 7 os 32 bits to download videos please?

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.3.0-beta/N_m3u8DL-RE_v0.3.0-beta_win-NT6.0-x86_20241203.zip

This is NT6.0 version.
