### ISSUE TITLE
v0.0.8-beta 直播录制到达限制后不会自动合并

### ISSUE THREAD

**Issue by 65887166** [nilaoda/N_m3u8DL-RE#56]
设置了“录制直播时的录制时长限制”，在停止直播后不会自动合并，这种情况是要设置“录制直播时实时合并”吗

**Comment by nilaoda** [comment]
N_m3u8DL-RE --morehelp mux-after-done

**Comment by 65887166** [comment]
但这不是二进制合并吧？

**Comment by nilaoda** [comment]
你说的合并如果是指把分片合起来的话，需要开启“录制直播时实时合并”。

**Comment by 65887166** [comment]
> 你说的合并如果是指把分片合起来的话，需要开启“录制直播时实时合并”。

好的，以后能不能支持一下自动合并分片？因为对于像电视台的m3u8源这样的，会用到录制时长限制，但是在录制结束后不会合并分片🤣

**Comment by nilaoda** [comment]
直播场景 建议使用 `--live-real-time-merge` 比录制结束再合并更好用。如果不需要临时分片可以配合 `--live-keep-segments false`

**Comment by 65887166** [comment]
谢谢大佬，明白了，既然都这样说了👌
