### ISSUE TITLE
not working with Tubi tv

### ISSUE THREAD

**Issue by tsm3u8** [nilaoda/N_m3u8DL-RE#566]
not combine video and m4a audio, both free movie and DRM protected ones. 
play url : https://tubitv.com/movies/100005746/florence-nightingale

![2024-12-21_202114](https://github.com/user-attachments/assets/9f67704d-6519-4f76-a8a5-132b092e72cc)

**Comment by tsm3u8** [comment]
![2024-12-21_202114](https://github.com/user-attachments/assets/4ebfa669-e20d-4ee9-b27e-7176517ebb6e)

**Comment by CrymanChen** [comment]
Use `-M mp4` or `-M mkv` to mux the video stream and audio stream.  
Also, don't forget passing the key to decrypt the video and audio:  
`1e0f06a348c6451eaa43e9ba5e5e55e4:b6c7cb9d23147d088c9c6c0880aa9664`

**Comment by tsm3u8** [comment]
thank you a lot and how to get DRM key?

**Comment by CrymanChen** [comment]
I think my repo may help you.
