### ISSUE TITLE
I find new updated real original Vxkex and new Vxkex projects that may help to keep support of windows 7 os 32 bits,   so we hope please support of N_m3u8DL-RE fo windows 7 os 32 bits will continue please !

### ISSUE THREAD

**Issue by trimechee** [nilaoda/N_m3u8DL-RE#568]
Hi, the great project Vxkex that allows windows 7 os to use windows 10/11 os software has been removed from github, some say microsoft fears this project so they banned it from github...

So today I find new october update of real Vxkex and also nes  projects of Vxkex forks  that add updates features, fix bugs, add support for new softwares for windos 7 os 32 bits and 64 bits !! 

may be the new version of vxkex and the  new updated forks can help the great N_m3u8DL-RE/  to keep support of our windows 7 os 32 bits please ! and obviously I think wndows 7 os users will be happy to install Vxkex which is very easy to use and without risk for the os!

and again huge thanks and gratitude to great generous Mr @nilaoda  for the rare heroic generous support of windows 7 OS 32 bits :) 💯 🥇

https://github.com/i486/VxKex (the  original project with the new update of october )

https://github.com/i486/VxKex/issues/36 (YuZhouRen86 fork updated)

https://github.com/Aqua-Vision/MgKex (fork updated)

and also :

extended kernel by Mr dotexe1337
http://www.dotexe.cf/extended/
https://web.archive.org/web/20241006001741/https://www.dotexe.cf/extended/
https://github.com/kernel-extenders/nt61

windows 7 os improve usuablility 32 bits (use with caution, prudence)
https://github.com/winrevive/win7-sp2
https://sp2.winrevive.xyz/

**Comment by nilaoda** [comment]
This project already provides a version that supports running on Windows 7, so this issue should be closed.

**Comment by trimechee** [comment]
Exactly Mr Niloada, I searched but I can't find out which version to install, it says this version is for windows vista and later so incompatible with windows 7 os?

https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.3.0-beta/N_m3u8DL-RE_v0.3.0-beta_win-NT6.0-x86_20241203.zip

where is the version for windows 7 os please?


I thought maybe N_m3u8DL-RE couldn't make a version for Windows 7 32-bit that's why I suggested using vxkex....

**Comment by trimechee** [comment]
*compatible only for windows vista and  subsequent (before windows vista)

**Comment by nilaoda** [comment]
win-NT6.0-x86_20241203.zip can run on Windows Vista and above. (Include Windows 7)

**Comment by trimechee** [comment]
Great, thanks 💯 🥇
