### ISSUE TITLE
mp4decrypt not found!报错

### ISSUE THREAD

**Issue by yyxiaofeng** [nilaoda/N_m3u8DL-RE#59]
N_m3u8DL-RE.exe --save-name test1 "https://staging-linearjitp-playback.astro.com.my/dash-wv/linear/601/default_primary.mpd" --key 6d2d84310d3fb9230404a1fbf5b33d10:8be93a0a6b41efad87096080bc55211a
出现mp4decrypt not found!报错
<img src="https://pic1.imgdb.cn/item/636b75ea16f2c2beb12a3de5.png">

**Comment by nilaoda** [comment]
那就下载mp4decrypt😂

https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-639.x86_64-microsoft-win32.zip

**Comment by yyxiaofeng** [comment]
大佬，录制的mpd，实时合并的mp4文件108M，播放时为啥只有2s呢

**Comment by yyxiaofeng** [comment]
N_m3u8DL-RE.exe --save-name 1 --live-real-time-merge "https://dizf8i52j4sep.cloudfront.net/out/v1/148af6c03e6d48b0a725611fae5ed3a7/index.mpd"生成的mp4文件播放时为啥只有2s呢
