### ISSUE TITLE
萌新想求一个工具

### ISSUE THREAD

**Issue by cgq342501** [nilaoda/N_m3u8DL-RE#61]
最近发现这个解决了我录制HBO源的需求，但是发现录制的时候会停在1小时就会断掉，还有就是录制没办法自己设定开始时间和结束时间，不知道有没有大佬求教

**Comment by cgq342501** [comment]
还有就是有办法做到录制完以后自动合并视频音轨和字幕吗？

**Comment by cgq342501** [comment]
![1O(E1HRH1JTG`R087F1{0@V](https://user-images.githubusercontent.com/94751683/201332600-93d4ad22-e622-4295-98b7-5ae712608a2d.png)
到1小时就会自动停。不知道什么情况

**Comment by nilaoda** [comment]
可以设置录制时长。也可以开启录制后混流，看一下help。断掉我无法判断啥原因 可能mpd有效期只有一小时？
