### ISSUE TITLE
Linux x64 not merging to complete file

### ISSUE THREAD

**Issue by A-nglea** [nilaoda/N_m3u8DL-RE#63]
The indivudual part files are left unmerged despite the program claiming merging is complete.

When I used this:- fmpeg -i The_Brennan_Girl.mp4 -i The_Brennan_Girl.en.m4a -i The_Brennan_Girl.en.srt -acodec copy -vcodec copy -c:s mov_text -metadata:s:s:0 language=english  TheBrennanGirl.mp4    ffmpeg works just fine.

command: N_m3u8DL-RE --save-name The_Brennan_Girl "https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/6272132012001/7eb6136c-d985-4c29-a278-a8e602c92960/6s/master.m3u8?fastly_token=NjM2ZmM4ODNfNjUxZDEwNDlhMWEwMTY4Yzg0YTNlMGU4OTViNzMxZTM3ZmRkYjQ3Y2FhMTQ1YjliZjA2ZDRhNDdjODkyZWRhOQ%3D%3D&bcov_auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NpZCI6IjYyNzIxMzIwMTIwMDEifQ.kfwThZX49U2WSqRYLANL5xP-1CkNYut8YFBgMMwc6fY"  gave three files audio, video, subtitle with no merged output

**Comment by nilaoda** [comment]
Add `-M mp4`
