### ISSUE TITLE
retryCount无法退出程序 Unable to read data from the transport connection:  远程主机强迫关闭了一个现有的连接。. retryCount: 3

### ISSUE THREAD

**Issue by dixtdf** [nilaoda/N_m3u8DL-RE#66]
02:27:02.424 INFO  : N_m3u8DL-RE (Beta version) 20221111
02:27:02.444 INFO  : 加载URL: 
02:27:02.498 INFO  : 内容匹配: HTTP Live Streaming
02:27:02.499 INFO  : 正在解析媒体信息...
02:27:02.817 INFO  : 已解析, 共计 1 条媒体流, 基本流 1 条, 可选音频流 0 条, 可选字幕流 0 条
02:27:02.817 INFO  : Vid Kbps | 128 Segments | ~24m58s
02:27:02.817 INFO  : 已选择的流:
02:27:02.817 INFO  : Vid Kbps | 128 Segments | ~24m58s
02:27:02.817 INFO  : 保存文件名: 
gzc_1000102_0b53gmac4aaamialvpbzpnrmam6dfy2qaksa.f322016.ts_2022-11-13_02-27-02
02:27:02.818 INFO  : 开始下载...Vid Kbps
02:27:03.098 WARN  : 读取媒体信息...
02:27:03.651 INFO  : [0x100]: Video, hevc ([36][0][0][0]), 3840x1636, 25 fps
02:27:03.651 INFO  : [0x101]: Audio, aac ([15][0][0][0]), 123 kb/s
Vid Kbps: 1%
Vid Kbps: 26%
02:27:14.299 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:15.075 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:15.419 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:15.634 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
Vid Kbps: 53%
02:27:17.791 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:17.801 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:17.851 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:18.108 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:18.515 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:20.347 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
Vid Kbps: 79%
02:27:21.089 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:21.411 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:21.736 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
02:27:22.178 WARN  : Unable to read data from the transport connection: 
远程主机强迫关闭了一个现有的连接。. retryCount: 3
Vid Kbps: 96%
Vid Kbps: 99%
Vid Kbps: 99%
Vid Kbps: 99%
Vid Kbps: 99%
Vid Kbps: 99%
Vid Kbps: 99%

**Comment by nilaoda** [comment]
这个没影响 估计你下载速度太快了
