### ISSUE TITLE
windows 64位版本，有病毒告警

### ISSUE THREAD

**Issue by lvchunxiao** [nilaoda/N_m3u8DL-RE#67]
下载64位版本时，360提示有病毒木马告警

**Comment by nilaoda** [comment]
如果不放心可以自己看代码，还不放心可以不用

**Comment by 592767809** [comment]
> 下载64位版本时，360提示有病毒木马告警

建议卸载360，那就看不到警告了

**Comment by nsnail** [comment]
> 下载64位版本时，360提示有病毒木马告警

用360的人也知道gayhub ？
