### ISSUE TITLE
Bug:无法合并ts文件

### ISSUE THREAD

**Issue by dsus4wang** [nilaoda/N_m3u8DL-RE#7]
17:30:01.505 INFO  : Content Matched: HTTP Live Streaming
17:30:01.505 INFO  : Parsing streams...
17:30:01.864 WARN  : Writing meta json
17:30:01.898 INFO  : Extracted, there are 1 streams, with 1 basic streams, 0 audio streams, 0 subtitle streams
17:30:01.899 INFO  : Vid *AES_128 Kbps | 1771 Segments | ~01h58m05s
17:30:01.901 WARN  : Writing meta json
17:30:01.939 INFO  : Selected streams:
17:30:01.941 INFO  : Vid *AES_128 Kbps | 1771 Segments | ~01h58m05s
17:30:01.944 INFO  : Start downloading...Vid Kbps
17:30:04.678 WARN  : Reading media info...                       
17:30:05.131 INFO  : [0x100]: Video, h264 (High) ([27][0][0][0]), 1280x720, 97 fps
17:30:05.136 INFO  : [0x101]: Audio, aac (LC) ([15][0][0][0]), 142 kb/s
17:34:04.784 INFO  : ffmpeg merging...                           
17:34:05.257 INFO  : Done
没有报错信息,没有合并,临时文件夹还在,里面的ts文件可以正常打开.
请问哪里可以看到日志嘛?
环境是Linux Debian arm64
试着下载另一个小视频 可以正常合并

**Comment by nilaoda** [comment]
刚才新发了一个版本 看看有没有打印错误日志出来

**Comment by dsus4wang** [comment]
谢谢,不过请问怎么编译呢?我是Arm64+Linux的配置
对了,我在老版本运行的后面加上了binarymerge选项,可以成功合并了.

**Comment by dsus4wang** [comment]
报错:Too many open files
另:用BinaryMerge=True可以正常合并

**Comment by dsus4wang** [comment]
您好:
我找到解决方案了,这个问题是Linux系统本身导致的:某些系统对进程调用文件数量有限制
解决办法 ulimit -n unlimited即可
https://stackoverflow.com/questions/30023574/how-to-fix-too-many-open-files-error-when-aggregating-billions-of-records

不过,想请教下BinaryMerge和默认的区别是?

**Comment by dsus4wang** [comment]
另:目前最新代码编译出来的程序,使用-h命令显示的帮助里未出现--download-retry-count的选项(不过应该是可以用的)

**Comment by dsus4wang** [comment]
又出现新的问题了……不合并也不报错……

**Comment by nilaoda** [comment]
超多文件调用ffmpeg的合并目前确实没考虑到，需要后续优化（旧下载器倒是考虑了）
