### ISSUE TITLE
下载了N_m3u8DL-RE_Beta_linux-arm64_20221117.tar.gz执行报错

### ISSUE THREAD

**Issue by yf718** [nilaoda/N_m3u8DL-RE#71]
错误信息：
./N_m3u8DL-RE: cannot execute binary file: Exec format error

系统版本:
$ cat /proc/version
Linux version 5.4.0-96-generic (buildd@lgw01-amd64-051) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022

**Comment by yjiawqgj** [comment]
老弟解决了吗？我也遇到了这样的错误了
