### ISSUE TITLE
下载后的视频音频无法合并

### ISSUE THREAD

**Issue by kedyao** [nilaoda/N_m3u8DL-RE#76]
出现下列问题有多次了 无法合并视频音频
 ![4](https://user-images.githubusercontent.com/47054558/204699288-6cd46436-0448-4c57-88d1-ebc494ad515e.png)

于是手动拖入下载好的文件到mkvtool V52.0  拖入视频音频均提示
![111](https://user-images.githubusercontent.com/47054558/204698851-85124fd2-f9b5-4541-ba60-be9528ddb1e7.png)

然后目前解决方法是用压制软件复制一次就可以导入mkvtool了
![2](https://user-images.githubusercontent.com/47054558/204698854-966f0d9c-5bb9-438e-93b0-1facde37f6e0.png)

那么推断就是下载器的文件有问题
![3](https://user-images.githubusercontent.com/47054558/204698857-c4d07479-c129-4fa8-af22-c04fce63fdb1.png)

视频地址是
 .\N_m3u8DL-RE.exe "https://theater.kktv.com.tw/02/01000602010007_9055c97495a0def087a8b728f53fa547/1669766037ec9eea6603_sub_dash.mpd"  --save-name 绽放7 --save-dir J:\widevine-L3-WEB-DL-Script-main --sub-format SRT --custom-proxy "http://127.0.0.1:7890"  --header "referer:https://kktv.me/" --key f0e73596552cb4b4f1b68e5b0e2411fd:1429d4e37750ceb0461a2aea36e2f627  -M format=mkv:muxer=mkvmerge

**Comment by nilaoda** [comment]
这是 v0.1.2 (**20221120**) 中的一次优化导致的bug。已经在 [v0.1.3](https://github.com/nilaoda/N_m3u8DL-RE/releases) 中 修正了。

**Comment by kedyao** [comment]
> 这是 v0.1.2 (**20221120**) 中的一次~优化~导致的bug。已经在 [v0.1.3](https://github.com/nilaoda/N_m3u8DL-RE/releases) 中 修正了。
下载video.friday.tw视频也不能合并 但文件是正常的可通过mkvtool合并为mkv 文件已上传至 https://t.wss.ink/f/9wyrie9pzu2 复制链接到浏览器打开2天有效

**Comment by nilaoda** [comment]
使用新版本即可，这是20221120版本的独有BUG。

**Comment by MyGoodbye** [comment]
请问friday 的视频你是怎么下载的
