### ISSUE TITLE
直播开始下载后，怎么手动停止？

### ISSUE THREAD

**Issue by lweo** [nilaoda/N_m3u8DL-RE#78]
如果没有指定录制时长，怎么在已经开始后停止录制并合并已下载的分片？

比如这种情况，我可以输入什么命令呢？
![image](https://user-images.githubusercontent.com/2786659/205025446-b36af74b-6458-452d-89b0-bda796a2b2d9.png)

**Comment by nilaoda** [comment]
直接关闭

**Comment by nilaoda** [comment]
另外请升级到最新版本。20221120版本存在已知的明显BUG。

**Comment by lweo** [comment]
> 直接关闭 或者ctrl c即可

这么做会不会导致视频没有时间戳？

有的下载视频，不能快进或者不能正确显示视频时长，显示的时长超过了实际时长，拖到后面就直接结束播放。不知道跟这个有关吗

**Comment by nilaoda** [comment]
程序逻辑是直接下载然后附加到文件后面 直接关闭也一样的
