### ISSUE TITLE
加密的直播好像无法实时解密

### ISSUE THREAD

**Issue by 362227** [nilaoda/N_m3u8DL-RE#88]
加密的直播好像无法实时解密，更无法实时合并？

**Comment by nilaoda** [comment]
请确保你的KEY正确。

**Comment by 362227** [comment]
> 请确保你的KEY正确。

这个肯定是对的。如果设置--live-perform-as-vod  true  就会下载后解密，不过只是很短的片段

**Comment by 362227** [comment]
`N_m3u8DL-RE --custom-proxy http://127.0.0.1:1086    https://live-npd.cdn.plus.nhk.jp/7fe0-0400/simul/cenc/manifest_m1500.m3u8  -sv best -sa best  --live-keep-segments  --mp4-real-time-decryption true --use-shaka-packager  true --key  1fcc4144490a4b5eace926d4c1f41dce:69d0df9e53ba7b13ba40abc56e22a243 `

如果不加 `-sv best -sa best`  会报错
19:24:30.175 INFO : N_m3u8DL-RE (Beta version) 20221221
19:24:30.196 INFO : 加载URL: https://live-npd.cdn.plus.nhk.jp/7fe0-0400/simul/cenc/manifest_m1500.m3u8
19:24:30.874 INFO : 内容匹配: HTTP Live Streaming
19:24:30.874 INFO : 正在解析媒体信息...
19:24:30.875 WARN : 检测到Master列表，开始解析全部流信息
19:24:30.889 INFO : 已解析, 共计 14 条媒体流, 基本流 8 条, 可选音频流 4 条, 可选字幕流 2 条
19:24:30.889 INFO : Vid 1564 Kbps | mp4a.40.2
19:24:30.890 INFO : Vid 1564 Kbps | mp4a.40.2
19:24:30.890 INFO : Vid 832 Kbps | mp4a.40.2
19:24:30.890 INFO : Vid 832 Kbps | mp4a.40.2
19:24:30.891 INFO : Vid 448 Kbps | mp4a.40.2
19:24:30.891 INFO : Vid 448 Kbps | mp4a.40.2
19:24:30.892 INFO : Vid 256 Kbps | mp4a.40.2
19:24:30.892 INFO : Vid 256 Kbps | mp4a.40.2
19:24:30.892 INFO : Aud l0 | main | ja
19:24:30.893 INFO : Aud l0-s | main | ja
19:24:30.893 INFO : Aud l0 | sub | ja
19:24:30.893 INFO : Aud l0-s | sub | ja
19:24:30.895 INFO : Sub subtitle | ja | Japanese
19:24:30.896 INFO : Sub subtitle-s | ja | Japanese
19:24:30.897 ERROR: Sequence contains no matching element

**Comment by 362227** [comment]
已经成功了

**Comment by nilaoda** [comment]
启用`--live-perform-as-vod`会使用录播的逻辑
