### ISSUE TITLE
Operation is not supported on this platform.

### ISSUE THREAD

**Issue by Marvll** [nilaoda/N_m3u8DL-RE#9]
> 00:35:49.550 INFO  : 正在解析媒体信息...
00:35:49.551 WARN  : 写出meta json
00:35:49.567 INFO  : 已选择的流:
00:35:49.568 INFO  : Vid *CENC 3840x2160 | 15000 Kbps | video_5 | hvc1.1.6.L150.90 | 1954 Segments | ~02h10m14s
00:35:49.568 INFO  : Aud *CENC audio_aac_eng_6 | 56 Kbps | mp4a.40.2 | eng | 1954 Segments | ~02h10m14s
00:35:49.573 INFO  : 开始下载...Vid 3840x2160 | 15000 Kbps | video_5 | hvc1.1.6.L150.90
00:35:49.573 WARN  : 检测到CENC加密方式，自动开启二进制合并
00:35:50.605 ERROR : Operation is not supported on this platform.00:35:49.550 INFO  : 正在解析媒体信息...
00:35:49.551 WARN  : 写出meta json
00:35:49.567 INFO  : 已选择的流:
00:35:49.568 INFO  : Vid *CENC 3840x2160 | 15000 Kbps | video_5 | hvc1.1.6.L150.90 | 1954 Segments | ~02h10m14s
00:35:49.568 INFO  : Aud *CENC audio_aac_eng_6 | 56 Kbps | mp4a.40.2 | eng | 1954 Segments | ~02h10m14s
00:35:49.573 INFO  : 开始下载...Vid 3840x2160 | 15000 Kbps | video_5 | hvc1.1.6.L150.90
00:35:49.573 WARN  : 检测到CENC加密方式，自动开启二进制合并
00:35:50.605 ERROR : Operation is not supported on this platform.

N_m3u8DL-RE_Beta_win-x64

**Comment by nilaoda** [comment]
增加参数`--log-level DEBUG` 再运行一次

**Comment by aaaeeeo** [comment]
N_m3u8DL-RE_Beta_win-x64
Same issue. `--log-level DEBUG` added.

```
21:00:11.069 INFO  : Content Matched: Dynamic Adaptive Streaming over HTTP
21:00:11.070 INFO  : Parsing streams...
21:00:11.203 WARN  : Writing meta json
21:00:11.265 INFO  : Extracted, there are 9 streams, with 8 basic streams, 1 audio streams, 0 subtitle streams
21:00:11.265 INFO  : Vid *CENC 1920x1080 | 5671 Kbps | 8 | 23.976 | avc1.640028 | 2910 Segments | ~01h37m04s
21:00:11.266 INFO  : Vid *CENC 1920x1080 | 4171 Kbps | 7 | 23.976 | avc1.640028 | 2910 Segments | ~01h37m04s
21:00:11.266 INFO  : Vid *CENC 1280x720 | 3371 Kbps | 6 | 23.976 | avc1.4D401F | 2910 Segments | ~01h37m04s
21:00:11.266 INFO  : Vid *CENC 1280x720 | 2621 Kbps | 5 | 23.976 | avc1.4D401F | 2910 Segments | ~01h37m04s
21:00:11.266 INFO  : Vid *CENC 720x406 | 1621 Kbps | 4 | 23.976 | avc1.42C01F | 2910 Segments | ~01h37m04s
21:00:11.267 INFO  : Vid *CENC 720x406 | 971 Kbps | 3 | 23.976 | avc1.42C01E | 2910 Segments | ~01h37m04s
21:00:11.267 INFO  : Vid *CENC 512x288 | 571 Kbps | 2 | 23.976 | avc1.42C01E | 2910 Segments | ~01h37m04s
21:00:11.267 INFO  : Vid *CENC 384x216 | 271 Kbps | 1 | 23.976 | avc1.42C01E | 2910 Segments | ~01h37m04s
21:00:11.267 INFO  : Aud *CENC 9 | 128 Kbps | mp4a.40.2 | eng | 2CH | 2910 Segments | ~01h37m04s
21:00:12.685 INFO  : Parsing streams...
21:00:12.686 WARN  : Writing meta json
21:00:12.706 INFO  : Selected streams:
21:00:12.706 INFO  : Vid *CENC 1920x1080 | 5671 Kbps | 8 | 23.976 | avc1.640028 | 2910 Segments | ~01h37m04s
21:00:12.707 INFO  : Aud *CENC 9 | 128 Kbps | mp4a.40.2 | eng | 2CH | 2910 Segments | ~01h37m04s
21:00:12.707 DEBUG : dirName: 1_8_avc1.640028_; tmpDir: C:\...\N_m3u8DL-RE_Beta_win-x64\1_8_avc1.640028_; saveDir: C:\...\N_m3u8DL-RE_Beta_win-x64; saveName: 1.VIDEO
21:00:12.707 INFO  : Start downloading...Vid 1920x1080 | 5671 Kbps | 8 | 23.976 | avc1.640028
21:00:12.708 WARN  : When CENC encryption is detected, binary merging is automatically enabled
21:00:12.710 ERROR : Operation is not supported on this platform.
```

**Comment by Marvll** [comment]
> 增加参数`--log-level DEBUG` 再运行一次

Action自动构建的不能使用，release版本正常

**Comment by nilaoda** [comment]
确实有问题 我等会儿看看

**Comment by nilaoda** [comment]
@Marvll @aaaeeeo Try this: https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/2894806363

**Comment by aaaeeeo** [comment]
> @Marvll @aaaeeeo Try this: https://github.com/nilaoda/N_m3u8DL-RE/actions/runs/2894806363

Working now, tks
