### ISSUE TITLE
Sokmil视频下载

### ISSUE THREAD

**Issue by SAOJSM** [nilaoda/N_m3u8DL-RE#94]
您好
在sokmil上购买了视频
因为是mpd/dash
所以用RE没用CLI
抓了mpd网址后发现有加密
下载的都是纯色画面
回去查看开发者模式
发现有个strict when across origin
意思是不在官网播放就会被限制
想请问这个是否有办法可以解
以及怎么抓取解密金钥呢
谢谢

PS:需要帐号可以提供让您测试

**Comment by nilaoda** [comment]
你需要在GitHub上搜索Widevine等关键字以了解具体信息。

**Comment by SAOJSM** [comment]
@nilaoda 已尝试搜索Widevine，但因为google DMCA的关系，所有的repo都封存或删库了，以至于无法了解，是否哪里有详细的教学可以看呢，谢谢
