### ISSUE TITLE
Is there any way to support sdk scheme? Is it possible or not?

### ISSUE THREAD

**Issue by kurtn2005** [nilaoda/N_m3u8DL-RE#95]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/23029247/210504141-858a3ed8-e4e2-458b-81a4-1274d53f336d.png">

#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://ChDy656Hr-4xToOFUpIfaK4oEhDlvHJq1JVNUUK3TFDtlI22GpIBeyJ2IjoiMiIsImZpZCI6IjUzZHYwMTUyMSIsInN2aWQiOiJkaWdpdGFsIiwicGwiOiJleUp3YVdRaU9pSTFNMlIyTURFMU1qRWlMQ0prWld4cGRtVnllVjkwZVhCbElqb2ljM1FpZlEiLCJjcyI6IjA0M2VjN2RhNWE0NDdkM2Y5NTE5Y2VkZmQ3NzE5OTliIn0",IV=0xe5bc726ad4954d5142b74c50ed948db6,KEYFORMAT="com.apple.streamingkeydelivery"

Is it possible to support this or there is simply no way to do it now?

**Comment by nilaoda** [comment]
That is DRM protected stream, cant support directly.

**Comment by kurtn2005** [comment]
> That is DRM protected stream, cant support directly.

Good to know, thank you.
